% 
\documentclass[a4paper]{article}
\usepackage{Sweave}
\usepackage[latin1]{inputenc} %encodage du fichier source
\usepackage[T1]{fontenc}  %gestion des accents (pour les pdf) 
\usepackage[francais]{babel}
\usepackage{float}
\usepackage[section]{placeins}%The placeins package provides the command \FloatBarrier 
\usepackage{amsmath} % equation numbering
\usepackage[colorlinks=true,urlcolor=blue,linkcolor=black,citecolor=black]{hyperref}
\usepackage{wrapfig}
\usepackage{subcaption} % pour les subfigures
\usepackage{vmargin}
\setpapersize{A4}
\setmarginsrb{15mm}{15mm}{15mm}{15mm}{12pt}{0mm}{0pt}{11mm}
\pagestyle{empty}

\title{Sortie des paramètres Openbugs - Modèle
2017\_03\_23\_4zones\_Interaction}
\author{marion.legrand}

\begin{document}

\maketitle
<< init, echo=FALSE, eval=TRUE,results=hide >>=
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2015_10_07/CODA/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2015_10_07/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2015_10_07/"
#	datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2015_06_09/"
#	imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2015_06_09/"
#	tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2015_06_09/"
#	setwd("C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/script/lateX")
#	datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2015_01_24_thin200/"
#	imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2015_01_24_thin200/"
#	tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2015_01_24_thin200/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2015_11_26/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2015_11_26/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2015_11_26/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2015_12_02_PoutesCor/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2015_12_02_PoutesCor/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2015_12_02_PoutesCor/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2015_12_04_standard/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2015_12_04_standard/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2015_12_04_standard/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2016_01_18_0_dore/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2016_01_18_0_dore/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2016_01_18_0_dore/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2016_01_20_standard_thin200/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2016_01_20_standard_thin200/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2016_01_20_standard_thin200/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2016_01_20_Devalaison_AvecRho_poutes/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2016_01_20_Devalaison_AvecRho_poutes/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2016_01_20_Devalaison_AvecRho_poutes/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2016_10_14_Alagnon_adjust_p/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2016_10_14_Alagnon_adjust_p/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2016_10_14_Alagnon_adjust_p/"
#datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2016_12_06_Alagnon/"
#imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2016_12_06_Alagnon/"
#tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2016_12_06_Alagnon/"

datawd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2017_03_23_4zones_Interaction/"
imgwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2017_03_23_4zones_Interaction/"
tabwd<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/tab/2017_03_23_4zones_Interaction/"

	library(coda)
	library(lattice)
	library(boot)
	require(stringr)
	require(xtable)
	T=41
@

%=================================================================================
\section{sigma\_juv\_moy}
%=================================================================================
<< sigma_juv_moy, echo=FALSE,  eval=TRUE,results=hide >>=
sigma_juv_m=read.coda(str_c(datawd,"parameters/sigma_juv_moyCODAchain1.txt"),str_c(datawd,"/parameters/sigma_juv_moyCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_juv_moy.png"),width=800,height=800)
plot(sigma_juv_m)
dev.off()

sum=summary(sigma_juv_m, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_juv_moy",caption="Statistiques de sigma\\_juv\\moy")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_juv_moy.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)
		
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_juv_moy.png}%{a_juv.png}
     \caption{sigma\_juv\_moy}
     \label{sigma_juv_moy} 
\end{figure}

\input{\Sexpr{tabwd}sigma_juv_moy.tex}
\clearpage

%=================================================================================
\section{sigma\_wild\_moy}
%=================================================================================
<< sigma_wild_moy, echo=FALSE,  eval=TRUE,results=hide >>=
sigma_wild_m=read.coda(str_c(datawd,"/parameters/sigma_wild_moyCODAchain1.txt"),str_c(datawd,"/parameters/sigma_wild_moyCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_wild_moy.png"),width=800,height=800)
plot(sigma_wild_m)
dev.off()


sum=summary(sigma_wild_m, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_wild_moy",caption="Statistiques de sigma\\_wild\\moy")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_wild_moy.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_wild_moy.png}%{a_juv.png}
     \caption{sigma\_wild\_moy}
     \label{sigma_wild_moy} 
\end{figure}

\input{\Sexpr{tabwd}sigma_wild_moy.tex}
\clearpage

%=================================================================================
\section{sigma\_egg\_moy}
%=================================================================================
<< sigma_egg_moy, echo=FALSE,  eval=TRUE,results=hide >>=
sigma_egg_m=read.coda(str_c(datawd,"/parameters/sigma_egg_moyCODAchain1.txt"),str_c(datawd,"/parameters/sigma_egg_moyCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_egg_moy.png"),width=800,height=800)
plot(sigma_egg_m)
dev.off()


sum=summary(sigma_egg_m, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_egg_moy",caption="Statistiques de sigma\\_egg\\moy")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_egg_moy.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_egg_moy.png}%{a_juv.png}
     \caption{sigma\_egg\_moy}
     \label{sigma_egg_moy} 
\end{figure}

\input{\Sexpr{tabwd}sigma_egg_moy.tex}
\clearpage

%=================================================================================
\section{nu\_d}
%=================================================================================
<< nu_d, echo=FALSE, eval=TRUE,results=hide >>=
nu_d=read.coda(str_c(datawd,"nu_dCODAchain1.txt"),str_c(datawd,"nu_dCODAindex.txt"))
png(filename=str_c(imgwd,"nu_d.png"),width=800,height=800)
plot(nu_d)
dev.off()


sum=summary(nu_d, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl1<-sum$quantiles[1,]
tabl1["Mean"]<-sum$statistics[1]
tabl1["SD"]<-sum$statistics[1,"SD"]
tabl1=rbind(tabl1) #pour en faire une table
tabl2<-sum$quantiles[2,]
tabl2["Mean"]<-sum$statistics[2]
tabl2["SD"]<-sum$statistics[2,"SD"]
tabl2=rbind(tabl2)
tabl3<-sum$quantiles[3,]
tabl3["Mean"]<-sum$statistics[3]
tabl3["SD"]<-sum$statistics[3,"SD"]
tabl3=rbind(tabl3)
tabl4<-sum$quantiles[4,]
tabl4["Mean"]<-sum$statistics[4]
tabl4["SD"]<-sum$statistics[4,"SD"]
tabl4=rbind(tabl4)
tabl=rbind(tabl1,tabl2,tabl3,tabl4)
rownames(tabl)=c("nu_d_V","nu_d_A","nu_d_L","nu_d_P")

tab<-xtable(x=tabl,label="nu_d",caption="Statistiques de
nu\\_d")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"nu_d.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=TRUE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}nu_d.png}
     \caption{nu\_d}
     \label{nu_d} 
\end{figure}

\input{\Sexpr{tabwd}nu_d.tex}
\clearpage
%=================================================================================
\section{a}
%=================================================================================
<< a, echo=FALSE, eval=TRUE,results=hide >>=
a=read.coda(str_c(datawd,"aCODAchain1.txt"),str_c(datawd,"aCODAindex.txt"))
png(filename=str_c(imgwd,"a.png"),width=800,height=800)
plot(a)
dev.off()

sum=summary(a, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="a",caption="Statistiques de a")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"a.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}a.png}%{a_juv.png}
     \caption{a}
     \label{a} 
\end{figure}

\input{\Sexpr{tabwd}a.tex}
\clearpage

%=================================================================================
\section{a\_juv}
%=================================================================================
<< a_juv, echo=FALSE, eval=TRUE,results=hide >>=
a_juv=read.coda(str_c(datawd,"a_juvCODAchain1.txt"),str_c(datawd,"a_juvCODAindex.txt"))
png(filename=str_c(imgwd,"a_juv.png"),width=800,height=800)
plot(a_juv)
dev.off()


sum=summary(a_juv, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="a_juv",caption=c("Statistiques de a\\_juv","Maa"))#,align=c("L",rep("C",5))) 

o<-print(tab, file = str_c(tabwd,"a_juv.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}a_juv.png}%{a_juv.png}
     \caption{a\_juv}
     \label{a_juv} 
\end{figure}

\input{\Sexpr{tabwd}a_juv.tex}
\clearpage
%=================================================================================
\section{Rmax}
%=================================================================================
<< Rmax, echo=FALSE, eval=TRUE,results=hide >>=
Rmax=read.coda(str_c(datawd,"RmaxCODAchain1.txt"),str_c(datawd,"RmaxCODAindex.txt"))
png(filename=str_c(imgwd,"Rmax.png"),width=800,height=800)
plot(Rmax)
dev.off()


sum=summary(Rmax, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="Rmax",caption="Statistiques de Rmax")#,align=c("L",rep("C",5))) 

o<-print(tab, file = str_c(tabwd,"Rmax.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}Rmax.png}%{a_juv.png}
     \caption{Rmax}
     \label{Rmax} 
\end{figure}

\input{\Sexpr{tabwd}Rmax.tex}
\clearpage

%=================================================================================
\section{p\_Rmax}
%=================================================================================
%------------------------------------
\subsection{p\_Rmax\_V}
%------------------------------------
<< p_Rmax_V, echo=FALSE, eval=TRUE,results=hide >>=
p_Rmax_V=read.coda(str_c(datawd,"p_Rmax_VCODAchain1.txt"),str_c(datawd,"p_Rmax_VCODAindex.txt"))

sum=summary(p_Rmax_V, probs=seq(0,1,0.1))

p_Rmax_V_q<-sum$quantiles
annee_vide<-matrix(c(rep(NA,18*5)),nrow=18,ncol=5)
dimnames(annee_vide)<-list(c("p_Rmax[1,1]","p_Rmax[2,1]","p_Rmax[3,1]","p_Rmax[4,1]","p_Rmax[5,1]","p_Rmax[7,1]","p_Rmax[8,1]","p_Rmax[9,1]","p_Rmax[10,1]","p_Rmax[12,1]","p_Rmax[13,1]","p_Rmax[14,1]","p_Rmax[15,1]","p_Rmax[16,1]","p_Rmax[17,1]","p_Rmax[19,1]","p_Rmax[20,1]","p_Rmax[31,1]"))
p_Rmax_V_2<-rbind(p_Rmax_V_q,annee_vide)

ord<-c(seq(24,28,by=1),1,seq(29,32,by=1),2,seq(33,38,by=1),3,39,40,seq(4,13,by=1),41,seq(14,23,by=1))
p_Rmax_V_q<-p_Rmax_V_2[ord,]

mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"p_Rmax_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1),ylab="p_Rmax_V")

# trace l'axe des ordonnées
axis(2,at = seq(0,1,by=0.2),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 0.9,las =1,col = "grey55") # trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1: (T-1)){
	#whiskers
	#95%
	segments(i-0.15,p_Rmax_V_q[i,5],i+0.15,p_Rmax_V_q[i,5])
	segments(i,p_Rmax_V_q[i,4],i,p_Rmax_V_q[i,5])
	#5%
	segments(i-0.15,p_Rmax_V_q[i,1],i+0.15,p_Rmax_V_q[i,1])
	segments(i,p_Rmax_V_q[i,2],i,p_Rmax_V_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(p_Rmax_V_q[i,2],p_Rmax_V_q[i,2],p_Rmax_V_q[i,4],p_Rmax_V_q[i,4]),col="green")
	#mean
	#segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)

dev.off()

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}p_Rmax_V.png}
     \caption{p_Rmax_V}
     \label{p_Rmax_V} 
\end{figure}
\clearpage

%------------------------------------
\subsection{p\_Rmax\_A}
%------------------------------------
<< p_Rmax_A, echo=FALSE, eval=TRUE,results=hide >>=
p_Rmax_A=read.coda(str_c(datawd,"p_Rmax_ACODAchain1.txt"),str_c(datawd,"p_Rmax_ACODAindex.txt"))

sum=summary(p_Rmax_A, probs=seq(0,1,0.1))

p_Rmax_A_q<-sum$quantiles

annee_vide<-matrix(c(rep(NA,19*5)),nrow=19,ncol=5)
dimnames(annee_vide)<-list(c("p_Rmax[1,2]","p_Rmax[3,2]","p_Rmax[5,2]","p_Rmax[6,2]","p_Rmax[9,2]","p_Rmax[11,2]","p_Rmax[12,2]","p_Rmax[13,2]","p_Rmax[14,2]","p_Rmax[15,2]","p_Rmax[16,2]","p_Rmax[17,2]","p_Rmax[18,2]","p_Rmax[19,2]","p_Rmax[20,2]","p_Rmax[23,2]","p_Rmax[24,2]","p_Rmax[28,2]","p_Rmax[31,2]"))
p_Rmax_A_2<-rbind(p_Rmax_A_q,annee_vide)

ord<-c(23,1,24,2,25,26,3,4,27,5,seq(28,37,by=1),6,7,38,39,seq(8,10,by=1),40,11,12,41,seq(13,22,by=1))
p_Rmax_A_q<-p_Rmax_A_2[ord,]
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"p_Rmax_A.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1),ylab="p_Rmax_A")

# trace l'axe des ordonnées
axis(2,at = seq(0,1,by=0.2),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 0.9,las =1,col = "grey55") # trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1: (T-1)){
	#whiskers
	#95%
	segments(i-0.15,p_Rmax_A_q[i,5],i+0.15,p_Rmax_A_q[i,5])
	segments(i,p_Rmax_A_q[i,4],i,p_Rmax_A_q[i,5])
	#5%
	segments(i-0.15,p_Rmax_A_q[i,1],i+0.15,p_Rmax_A_q[i,1])
	segments(i,p_Rmax_A_q[i,2],i,p_Rmax_A_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(p_Rmax_A_q[i,2],p_Rmax_A_q[i,2],p_Rmax_A_q[i,4],p_Rmax_A_q[i,4]),col="green")
	#mean
	#segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)

dev.off()

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}p_Rmax_A.png}
     \caption{p_Rmax_A}
     \label{p_Rmax_A} 
\end{figure}
\clearpage

%------------------------------------
\subsection{p\_Rmax\_L}
%------------------------------------
<< p_Rmax_L, echo=FALSE, eval=TRUE,results=hide >>=
p_Rmax_L=read.coda(str_c(datawd,"p_Rmax_LCODAchain1.txt"),str_c(datawd,"p_Rmax_LCODAindex.txt"))

sum=summary(p_Rmax_L, probs=seq(0,1,0.1))

p_Rmax_L_q<-sum$quantiles

annee_vide<-matrix(c(rep(NA,28*5)),nrow=28,ncol=5)
dimnames(annee_vide)<-list(c("p_Rmax[1,3]","p_Rmax[2,3]","p_Rmax[3,3]","p_Rmax[4,3]","p_Rmax[5,3]","p_Rmax[7,3]","p_Rmax[8,3]","p_Rmax[9,3]","p_Rmax[10,3]","p_Rmax[11,3]","p_Rmax[12,3]","p_Rmax[13,3]","p_Rmax[14,3]","p_Rmax[15,3]","p_Rmax[16,3]","p_Rmax[18,3]","p_Rmax[19,3]","p_Rmax[20,3]","p_Rmax[25,3]","p_Rmax[33,3]","p_Rmax[34,3]","p_Rmax[35,3]","p_Rmax[36,3]","p_Rmax[37,3]","p_Rmax[38,3]","p_Rmax[39,3]","p_Rmax[40,3]","p_Rmax[41,3]"))
p_Rmax_L_2<-rbind(p_Rmax_L_q,annee_vide)

ord<-c(seq(14,18,by=1),1,seq(19,28,by=1),2,seq(29,31,by=1),seq(3,6,by=1),32,seq(7,13,by=1),seq(33,41,by=1))
p_Rmax_L_q<-p_Rmax_L_2[ord,]
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"p_Rmax_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1),ylab="p_Rmax_L")

# trace l'axe des ordonnées
axis(2,at = seq(0,1,by=0.2),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 0.9,las =1,col = "grey55") # trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1: (T-1)){
	#whiskers
	#95%
	segments(i-0.15,p_Rmax_L_q[i,5],i+0.15,p_Rmax_L_q[i,5])
	segments(i,p_Rmax_L_q[i,4],i,p_Rmax_L_q[i,5])
	#5%
	segments(i-0.15,p_Rmax_L_q[i,1],i+0.15,p_Rmax_L_q[i,1])
	segments(i,p_Rmax_L_q[i,2],i,p_Rmax_L_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(p_Rmax_L_q[i,2],p_Rmax_L_q[i,2],p_Rmax_L_q[i,4],p_Rmax_L_q[i,4]),col="green")
	#mean
	#segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)

dev.off()

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}p_Rmax_L.png}
     \caption{p_Rmax_L}
     \label{p_Rmax_L} 
\end{figure}
\clearpage

%------------------------------------
\subsection{p\_Rmax\_P}
%------------------------------------
<< p_Rmax_P, echo=FALSE, eval=TRUE,results=hide >>=
p_Rmax_P=read.coda(str_c(datawd,"p_Rmax_PCODAchain1.txt"),str_c(datawd,"p_Rmax_PCODAindex.txt"))

sum=summary(p_Rmax_P, probs=seq(0,1,0.1))

p_Rmax_P_q<-sum$quantiles

annee_vide<-matrix(c(rep(NA,26*5)),nrow=26,ncol=5)
dimnames(annee_vide)<-list(c("p_Rmax[1,4]","p_Rmax[2,4]","p_Rmax[3,4]","p_Rmax[4,4]","p_Rmax[5,4]","p_Rmax[6,4]","p_Rmax[7,4]","p_Rmax[8,4]","p_Rmax[9,4]","p_Rmax[10,4]","p_Rmax[11,4]","p_Rmax[12,4]","p_Rmax[13,4]","p_Rmax[14,4]","p_Rmax[15,4]","p_Rmax[16,4]","p_Rmax[17,4]","p_Rmax[26,4]","p_Rmax[34,4]","p_Rmax[35,4]","p_Rmax[36,4]","p_Rmax[37,4]","p_Rmax[38,4]","p_Rmax[39,4]","p_Rmax[40,4]","p_Rmax[41,4]"))
p_Rmax_P_2<-rbind(p_Rmax_P_q,annee_vide)

ord<-c(seq(16,32,by=1),seq(1,8,by=1),33,seq(9,15,by=1),seq(34,41,by=1))
p_Rmax_P_q<-p_Rmax_P_2[ord,]
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"p_Rmax_P.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1),ylab="p_Rmax_P")

# trace l'axe des ordonnées
axis(2,at = seq(0,1,by=0.2),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 0.9,las =1,col = "grey55") # trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1: (T-1)){
	#whiskers
	#95%
	segments(i-0.15,p_Rmax_P_q[i,5],i+0.15,p_Rmax_P_q[i,5])
	segments(i,p_Rmax_P_q[i,4],i,p_Rmax_P_q[i,5])
	#5%
	segments(i-0.15,p_Rmax_P_q[i,1],i+0.15,p_Rmax_P_q[i,1])
	segments(i,p_Rmax_P_q[i,2],i,p_Rmax_P_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(p_Rmax_P_q[i,2],p_Rmax_P_q[i,2],p_Rmax_P_q[i,4],p_Rmax_P_q[i,4]),col="green")
	#mean
	#segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)

dev.off()

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}p_Rmax_P.png}
     \caption{p_Rmax_P}
     \label{p_Rmax_P} 
\end{figure}
\clearpage


%=================================================================================
\section{sigma\_juv\_site}
%=================================================================================
<< sigma_juv_site, echo=FALSE,  eval=TRUE,results=hide >>=
sigma_juv_s=read.coda(str_c(datawd,"/parameters/sigma_juv_siteCODAchain1.txt"),str_c(datawd,"/parameters/sigma_juv_siteCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_juv_site.png"),width=800,height=800)
plot(sigma_juv_s)
dev.off()

sum=summary(sigma_juv_s, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_juv_site",caption="Statistiques de sigma\\_juv\\_site")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_juv_site.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_juv_site.png}%{a_juv.png}
     \caption{sigma\_juv\_site}
     \label{sigma_juv_site} 
\end{figure}

\input{\Sexpr{tabwd}sigma_juv_site.tex}
\clearpage

%=================================================================================
\section{sigma\_wild\_site}
%=================================================================================
<< sigma_wild_site, echo=FALSE,  eval=FALSE,results=hide >>=
sigma_wild_s=read.coda(str_c(datawd,"/parameters/sigma_wild_siteCODAchain1.txt"),str_c(datawd,"/parameters/sigma_wild_siteCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_wild_site.png"),width=800,height=800)
plot(sigma_wild_s)
dev.off()


sum=summary(sigma_wild_s, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_wild_site",caption="Statistiques de sigma\\_wild\\_site")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_wild_site.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_wild_site.png}%{a_juv.png}
     \caption{sigma\_wild\_site}
     \label{sigma_wild_site} 
\end{figure}

\input{\Sexpr{tabwd}sigma_wild_site.tex}
\clearpage

%=================================================================================
\section{sigma\_egg\_site}
%=================================================================================
<< sigma_egg_site, echo=FALSE,  eval=FALSE,results=hide >>=
sigma_egg_s=read.coda(str_c(datawd,"/parameters/sigma_egg_siteCODAchain1.txt"),str_c(datawd,"/parameters/sigma_egg_siteCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_egg_site.png"),width=800,height=800)
plot(sigma_egg_s)
dev.off()


sum=summary(sigma_egg_s, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_egg_site",caption="Statistiques de sigma\\_egg\\_site")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_egg_site.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_egg_site.png}%{a_juv.png}
     \caption{sigma\_egg\_site}
     \label{sigma_egg_site} 
\end{figure}

\input{\Sexpr{tabwd}sigma_egg_site.tex}
\clearpage

%=================================================================================
\section{adjust\_p\_A}
%=================================================================================
<< adjust_p_A, echo=FALSE, eval=FALSE,results=hide >>=
adjust_p_A=read.coda(str_c(datawd,"/simulation/adjust_p_ACODAchain1.txt"),str_c(datawd,"/simulation/adjust_p_ACODAindex.txt"))
png(filename=str_c(imgwd,"adjust_p_A.png"),width=800,height=800)
plot(adjust_p_A)
dev.off()


sum=summary(adjust_p_A, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="adjust_p_A",caption="Statistiques de adjust\\_p\\_A")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"adjust_p_A.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}adjust_p_A.png}%{a_juv.png}
     \caption{adjust\_p\_A}
     \label{adjust_p_A} 
\end{figure}

\input{\Sexpr{tabwd}adjust_p_A.tex}
\clearpage

%=================================================================================
\section{adjust\_p\_L}
%=================================================================================
<< adjust_p_L, echo=FALSE, eval=FALSE,results=hide >>=
adjust_p_L=read.coda(str_c(datawd,"/simulation/adjust_p_LCODAchain1.txt"),str_c(datawd,"/simulation/adjust_p_LCODAindex.txt"))
png(filename=str_c(imgwd,"adjust_p_L.png"),width=800,height=800)
plot(adjust_p_L)
dev.off()


sum=summary(adjust_p_L, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="adjust_p_L",caption="Statistiques de adjust\\_p\\_L")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"adjust_p_L.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}adjust_p_L.png}%{a_juv.png}
     \caption{adjust\_p\_L}
     \label{adjust_p_L} 
\end{figure}

\input{\Sexpr{tabwd}adjust_p_L.tex}
\clearpage

%=================================================================================
\section{adjust\_p\_P}
%=================================================================================
<< adjust_p_P, echo=FALSE, eval=FALSE,results=hide >>=
adjust_p_P=read.coda(str_c(datawd,"/simulation/adjust_p_PCODAchain1.txt"),str_c(datawd,"/simulation/adjust_p_PCODAindex.txt"))
png(filename=str_c(imgwd,"adjust_p_P.png"),width=800,height=800)
plot(adjust_p_P)
dev.off()


sum=summary(adjust_p_P, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="adjust_p_P",caption="Statistiques de adjust\\_p\\_P")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"adjust_p_P.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}adjust_p_P.png}%{a_juv.png}
     \caption{adjust\_p\_P}
     \label{adjust_p_P} 
\end{figure}

\input{\Sexpr{tabwd}adjust_p_P.tex}
\clearpage

%=================================================================================
\section{sigma\_p\_alagnon}
%=================================================================================
<< sigma_p_alagnon, echo=FALSE, eval=FALSE,results=hide >>=
sigma_p_alagnon=read.coda(str_c(datawd,"sigma_p_alagnonCODAchain1.txt"),str_c(datawd,"sigma_p_alagnonCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_p_alagnon.png"),width=800,height=800)
plot(sigma_p_alagnon)
dev.off()


sum=summary(sigma_p_alagnon, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_p_alagnon",caption="Statistiques de sigma\\_p\\_alagnon")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_p_alagnon.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_p_alagnon.png}%{a_juv.png}
     \caption{sigma\_p\_alagnon}
     \label{sigma_p_alagnon} 
\end{figure}

\input{\Sexpr{tabwd}sigma_p_alagnon.tex}
\clearpage

%=================================================================================
\section{sigma\_p\_langeac}
%=================================================================================
<< sigma_p_langeac, echo=FALSE, eval=FALSE,results=hide >>=
sigma_p_langeac=read.coda(str_c(datawd,"sigma_p_langeacCODAchain1.txt"),str_c(datawd,"sigma_p_langeacCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_p_langeac.png"),width=800,height=800)
plot(sigma_p_langeac)
dev.off()


sum=summary(sigma_p_langeac, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_p_langeac",caption="Statistiques de sigma\\_p\\_langeac")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_p_langeac.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_p_langeac.png}%{a_juv.png}
     \caption{sigma\_p\_langeac}
     \label{sigma_p_langeac} 
\end{figure}

\input{\Sexpr{tabwd}sigma_p_langeac.tex}
\clearpage

%=================================================================================
\section{sigma\_p\_poutes}
%=================================================================================
<< sigma_p_poutes, echo=FALSE, eval=FALSE,results=hide >>=
sigma_p_poutes=read.coda(str_c(datawd,"sigma_p_poutesCODAchain1.txt"),str_c(datawd,"sigma_p_poutesCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_p_poutes.png"),width=800,height=800)
plot(sigma_p_poutes)
dev.off()


sum=summary(sigma_p_poutes, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_p_poutes",caption="Statistiques de sigma\\_p\\_poutes")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_p_poutes.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_p_poutes.png}%{a_juv.png}
     \caption{sigma\_p\_poutes}
     \label{sigma_p_poutes} 
\end{figure}

\input{\Sexpr{tabwd}sigma_p_poutes.tex}
\clearpage

%=================================================================================
\section{rho\_station}
%=================================================================================
<< rho_station, echo=FALSE, eval=FALSE,results=hide >>=
rho_station=read.coda(str_c(datawd,"rho_stationCODAchain1.txt"),str_c(datawd,"rho_stationCODAindex.txt"))
png(filename=str_c(imgwd,"rho_station.png"),width=800,height=800)
plot(rho_station)
dev.off()


sum=summary(rho_station, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="rho_station",caption="Statistiques de rho\\_station")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"rho_station.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}rho_station.png}%{a_juv.png}
     \caption{rho\_station}
     \label{rho_station} 
\end{figure}

\input{\Sexpr{tabwd}rho_station.tex}
\clearpage

%=================================================================================
\section{hel\_effect}
%=================================================================================
<< hel_effect, echo=FALSE, eval=FALSE,results=hide >>=
hel_effect=read.coda(str_c(datawd,"hel_effectCODAchain1.txt"),str_c(datawd,"hel_effectCODAindex.txt"))
png(filename=str_c(imgwd,"hel_effect.png"),width=800,height=800)
plot(hel_effect)
dev.off()


sum=summary(hel_effect, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="hel_effect",caption="Statistiques de hel\\_effect")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"hel_effect.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}hel_effect.png}%{a_juv.png}
     \caption{hel\_effect}
     \label{hel_effect} 
\end{figure}

\input{\Sexpr{tabwd}hel_effect.tex}
\clearpage

%=================================================================================
\section{mu\_tau}
%=================================================================================
<< mu_tau, echo=FALSE,  eval=FALSE,results=hide >>=
mu_tau=read.coda(str_c(datawd,"parameters/mu_tauCODAchain1.txt"),str_c(datawd,"parameters/mu_tauCODAindex.txt"))
png(filename=str_c(imgwd,"mu_tau.png"),width=800,height=800)
plot(mu_tau)
dev.off()


sum=summary(mu_tau, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="mu_tau",caption="Statistiques de mu\\_tau",digits=c(0,6,6,6,6,6,6,6))#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"mu_tau.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}mu_tau.png}%{a_juv.png}
     \caption{mu\_tau}
     \label{mu_tau} 
\end{figure}

\input{\Sexpr{tabwd}mu_tau.tex}
\clearpage

%=================================================================================
\section{beta\_tau}
%=================================================================================
<< beta_tau, echo=FALSE,  eval=FALSE,results=hide >>=
beta_tau=read.coda(str_c(datawd,"parameters/beta_tauCODAchain1.txt"),str_c(datawd,"parameters/beta_tauCODAindex.txt"))
png(filename=str_c(imgwd,"beta_tau.png"),width=800,height=800)
plot(beta_tau)
dev.off()


sum=summary(beta_tau, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="beta_tau",caption="Statistiques de beta\\_tau")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"beta_tau.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}beta_tau.png}%{a_juv.png}
     \caption{beta\_tau}
     \label{beta_tau} 
\end{figure}

\input{\Sexpr{tabwd}beta_tau.tex}
\clearpage

%=================================================================================
\section{s\_juv2ad}
%=================================================================================
<< s_juv2ad, echo=FALSE, eval=FALSE,results=hide >>=
s_juv2ad=read.coda(str_c(datawd,"s_juv2adCODAchain1.txt"),str_c(datawd,"s_juv2adCODAindex.txt"))
png(filename=str_c(imgwd,"s_juv2ad.png"),width=800,height=800)
plot(s_juv2ad)
dev.off()


sum=summary(s_juv2ad, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="s_juv2ad",caption="Statistiques de s\\_juv2ad",digits=c(0,4,4,4,4,4,4,4))#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"s_juv2ad.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}s_juv2ad.png}%{a_juv.png}
     \caption{s\_juv2ad}
     \label{s_juv2ad} 
\end{figure}

\input{\Sexpr{tabwd}s_juv2ad.tex}
\clearpage

%=================================================================================
\section{level\_s}
%=================================================================================
<< level_s, echo=FALSE, eval=FALSE,results=hide >>=
level_s=read.coda(str_c(datawd,"simulation/level_sCODAchain1.txt"),str_c(datawd,"simulation/level_sCODAindex.txt"))
png(filename=str_c(imgwd,"level_s.png"),width=800,height=800)
plot(level_s)
dev.off()


sum=summary(level_s, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="level_s",caption="Statistiques de level\\_s")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"level_s.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}level_s.png}%{a_juv.png}
     \caption{level\_s}
     \label{level_s} 
\end{figure}

\input{\Sexpr{tabwd}level_s.tex}
\clearpage

%=================================================================================
\section{rho\_poutes}
%=================================================================================
<< rho_poutes, echo=FALSE, eval=FALSE,results=hide >>=
rho_poutes=read.coda(str_c(datawd,"rho_poutesCODAchain1.txt"),str_c(datawd,"rho_poutesCODAindex.txt"))
png(filename=str_c(imgwd,"rho_poutes.png"),width=800,height=800)
plot(rho_poutes)
dev.off()


sum=summary(rho_poutes, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="rho_poutes",caption="Statistiques de rho\\_poutes")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"rho_poutes.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}rho_poutes.png}%{a_juv.png}
     \caption{rho\_poutes}
     \label{rho_poutes} 
\end{figure}

\input{\Sexpr{tabwd}rho_poutes.tex}
\clearpage

%=================================================================================
\section{sigma\_vichy}
%=================================================================================
<< sigma_vichy, echo=FALSE, eval=FALSE,results=hide >>=
sigma_vichy=read.coda(str_c(datawd,"sigma_vichyCODAchain1.txt"),str_c(datawd,"sigma_vichyCODAindex.txt"))
png(filename=str_c(imgwd,"sigma_vichy.png"),width=800,height=800)
plot(sigma_vichy)
dev.off()


sum=summary(sigma_vichy, probs=seq(0,1,0.1))

# Pour voir le contenu de l'objet sum = str(sum)
#permet de savoir le nom des colonnes et tous les attributs (longueur, class, etc.) = attributes(sum)

#tabl=cbind(rbind(as.data.frame(sum[c(1)])[1,]),rbind(as.data.frame(sum[c(2)])[1:5,]))
#tabl=cbind(rbind(sum$statistics["Mean"]),rbind(sum$quantiles))

tabl<-sum$quantiles
tabl["Mean"]<-sum$statistics["Mean"]
tabl["SD"]<-sum$statistics["SD"]
tabl=rbind(tabl) #pour en faire une table

tab<-xtable(x=tabl,label="sigma_vichy",caption="Statistiques de sigma\\_vichy")#,align=c("L",rep("C",5)))

o<-print(tab, file = str_c(tabwd,"sigma_vichy.tex"), 
		table.placement = "htbp",
		caption.placement = "top",
		NA.string = "",
		include.rownames=FALSE
		)

cumuplot(sigma_vichy[412:10000],probs=c(0.05,0.5,0.95))
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}sigma_vichy.png}%{a_juv.png}
     \caption{sigma\_vichy}
     \label{sigma_vichy} 
\end{figure}

\input{\Sexpr{tabwd}sigma_vichy.tex}
\clearpage

%=================================================================================
\section{res\_p\_alagnon}
%================================================================================
<< res_p_alagnon, echo=FALSE, eval=FALSE,results=hide >>=
res_p_alagnon=read.coda(str_c(datawd,"simulation/res_p_alagnonCODAchain1.txt"),str_c(datawd,"simulation/res_p_alagnonCODAindex.txt"))
#Pour une raison mystérieuse la fonction quantiles utilisée par Guillaume D ne donne pas les mêmes
#résultats que le summary$quantiles. Après vérif du boxplot sous openbugs, le bon graph est celui utilisant la méthode summary
#Méthode quantiles : res_p_poutes_q=array(0,c(28,5))
#for (t in 1:28){	
#	res_p_langeac_q[t,]=quantile(res_p_langeac[t,],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
#}

sum=summary(res_p_alagnon, probs=seq(0,1,0.1))
res_p_alagnon_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])

png(filename=str_c(imgwd,"res_p_alagnon.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T+1),xlab="Years",ylim=c(-5,5),ylab="res_p_alagnon")

# trace l'axe des ordonnées
axis(2,at = seq(-5,5,by=0.5),labels=c(-5,-4.5,-4,-3.5,-3,-2.5,-2,-1.5,-1,-0.5,0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,1974+T)
axis(1,at = c(1,6,16,26,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#97,5%
	segments(i-0.15,res_p_alagnon_q[i,5],i+0.15,res_p_alagnon_q[i,5])
	segments(i,res_p_alagnon_q[i,4],i,res_p_alagnon_q[i,5])
	#2,5%
	segments(i-0.15,res_p_alagnon_q[i,1],i+0.15,res_p_alagnon_q[i,1])
	segments(i,res_p_alagnon_q[i,2],i,res_p_alagnon_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_p_alagnon_q[i,2],res_p_alagnon_q[i,2],res_p_alagnon_q[i,4],res_p_alagnon_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=-0.5,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_p_alagnon.png}%{a_juv.png}
     \caption{res\_p\_alagnon}
     \label{res_p_alagnon} 
\end{figure}

\clearpage


%=================================================================================
\section{res\_p\_langeac}
%================================================================================
<< res_p_langeac, echo=FALSE, eval=FALSE,results=hide >>=
res_p_langeac=read.coda(str_c(datawd,"simulation/res_p_langeacCODAchain1.txt"),str_c(datawd,"simulation/res_p_langeacCODAindex.txt"))
#Pour une raison mystérieuse la fonction quantiles utilisée par Guillaume D ne donne pas les mêmes
#résultats que le summary$quantiles. Après vérif du boxplot sous openbugs, le bon graph est celui utilisant la méthode summary
#Méthode quantiles : res_p_poutes_q=array(0,c(28,5))
#for (t in 1:28){	
#	res_p_langeac_q[t,]=quantile(res_p_langeac[t,],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
#}

sum=summary(res_p_langeac, probs=seq(0,1,0.1))
res_p_langeac_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])

png(filename=str_c(imgwd,"res_p_langeac.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T+1),xlab="Years",ylim=c(-2,2),ylab="res_p_langeac")

# trace l'axe des ordonnées
axis(2,at = seq(-2,2,by=0.5),labels=c(-2,-1.5,-1,-0.5,0,0.5,1,1.5,2),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,1974+T)
axis(1,at = c(1,6,16,26,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#97,5%
	segments(i-0.15,res_p_langeac_q[i,5],i+0.15,res_p_langeac_q[i,5])
	segments(i,res_p_langeac_q[i,4],i,res_p_langeac_q[i,5])
	#2,5%
	segments(i-0.15,res_p_langeac_q[i,1],i+0.15,res_p_langeac_q[i,1])
	segments(i,res_p_langeac_q[i,2],i,res_p_langeac_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_p_langeac_q[i,2],res_p_langeac_q[i,2],res_p_langeac_q[i,4],res_p_langeac_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=-0.5,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_p_langeac.png}%{a_juv.png}
     \caption{res\_p\_langeac}
     \label{res_p_langeac} 
\end{figure}

\clearpage

%=================================================================================
\section{res\_p\_poutes}
%================================================================================
<< res_p_poutes, echo=FALSE, eval=FALSE,results=hide >>=
res_p_poutes=read.coda(str_c(datawd,"simulation/res_p_poutesCODAchain1.txt"),str_c(datawd,"simulation/res_p_poutesCODAindex.txt"))

sum=summary(res_p_poutes, probs=seq(0,1,0.1))
res_p_poutes_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_p_poutes.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,(T-12+1)),xlab="Years",ylim=c(-4,4),ylab="res_p_poutes")

# trace l'axe des ordonnées
axis(2,at = seq(-4,4,by=1),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1986,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,(T-12)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-12)){
	#whiskers
	#95%
	segments(i-0.15,res_p_poutes_q[i,5],i+0.15,res_p_poutes_q[i,5])
	segments(i,res_p_poutes_q[i,4],i,res_p_poutes_q[i,5])
	#5%
	segments(i-0.15,res_p_poutes_q[i,1],i+0.15,res_p_poutes_q[i,1])
	segments(i,res_p_poutes_q[i,2],i,res_p_poutes_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_p_poutes_q[i,2],res_p_poutes_q[i,2],res_p_poutes_q[i,4],res_p_poutes_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=30,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_p_poutes.png}%{a_juv.png}
     \caption{res\_p\_poutes}
     \label{res_p_poutes} 
\end{figure}

\clearpage

%=================================================================================
\section{res\_vichy}
%================================================================================
<< res_vichy, echo=FALSE, eval=FALSE,results=hide >>=
res_vichy=read.coda(str_c(datawd,"simulation/res_vichyCODAchain1.txt"),str_c(datawd,"simulation/res_vichyCODAindex.txt"))

sum=summary(res_vichy, probs=seq(0,1,0.1))
res_vichy_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_vichy.png"),width=800,height=800)
plot(1,1,type="n",axes=FALSE,xlim=c(0,35),xlab="Years",ylim=c(-4,4),ylab="res_vichy")

# trace l'axe des ordonnées
axis(2,at = seq(-4,4,by=1),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1981,1990,2000,2010,1974+T)
axis(1,at = c(1,10,20,30,(T-6)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-6)){
	#whiskers
	#95%
	segments(i-0.15,res_vichy_q[i,5],i+0.15,res_vichy_q[i,5])
	segments(i,res_vichy_q[i,4],i,res_vichy_q[i,5])
	#5%
	segments(i-0.15,res_vichy_q[i,1],i+0.15,res_vichy_q[i,1])
	segments(i,res_vichy_q[i,2],i,res_vichy_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_vichy_q[i,2],res_vichy_q[i,2],res_vichy_q[i,4],res_vichy_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=35,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_vichy.png}%{a_juv.png}
     \caption{res\_vichy}
     \label{res_vichy} 
\end{figure}

\clearpage

%=================================================================================
\section{zone\_effect}
%================================================================================
%-------------------------------------------
\subsection{zone\_effect\_Vichy}
%-------------------------------------------
<< zone_effect_V, echo=FALSE, eval=FALSE,results=hide >>=
zone_effect_V=read.coda(str_c(datawd,"zone_effect_VCODAchain1.txt"),str_c(datawd,"zone_effect_VCODAindex.txt"))

sum=summary(zone_effect_V, probs=seq(0,1,0.1))
zone_effect_V_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"zone_effect_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-4,4),ylab="zone_effect_V")

# trace l'axe des ordonnées
axis(2,at = seq(-4,4,by=1),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,1974+T)
axis(1,at = c(1,6,16,26,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#95%
	segments(i-0.15,zone_effect_V_q[i,5],i+0.15,zone_effect_V_q[i,5])
	segments(i,zone_effect_V_q[i,4],i,zone_effect_V_q[i,5])
	#5%
	segments(i-0.15,zone_effect_V_q[i,1],i+0.15,zone_effect_V_q[i,1])
	segments(i,zone_effect_V_q[i,2],i,zone_effect_V_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_V_q[i,2],zone_effect_V_q[i,2],zone_effect_V_q[i,4],zone_effect_V_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}zone_effect_V.png}%{a_juv.png}
     \caption{zone\_effect\_V}
     \label{zone_effect_V} 
\end{figure}
\clearpage

<< zone_effect_A, echo=FALSE, eval=FALSE,results=hide >>=
zone_effect_A=read.coda(str_c(datawd,"zone_effect_ACODAchain1.txt"),str_c(datawd,"zone_effect_ACODAindex.txt"))

sum=summary(zone_effect_A, probs=seq(0,1,0.1))
zone_effect_A_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"zone_effect_A.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-4,4),ylab="zone_effect_A")

# trace l'axe des ordonnées
axis(2,at = seq(-4,4,by=1),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,1974+T)
axis(1,at = c(1,6,16,26,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#95%
	segments(i-0.15,zone_effect_A_q[i,5],i+0.15,zone_effect_A_q[i,5])
	segments(i,zone_effect_A_q[i,4],i,zone_effect_A_q[i,5])
	#5%
	segments(i-0.15,zone_effect_A_q[i,1],i+0.15,zone_effect_A_q[i,1])
	segments(i,zone_effect_A_q[i,2],i,zone_effect_A_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_A_q[i,2],zone_effect_A_q[i,2],zone_effect_A_q[i,4],zone_effect_A_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}zone_effect_A.png}%{a_juv.png}
     \caption{zone\_effect\_A}
     \label{zone_effect_A} 
\end{figure}
\clearpage


%-------------------------------------------
\subsection{zone\_effect\_Langeac}
%-------------------------------------------
<< zone_effect_L, echo=FALSE, eval=FALSE,results=hide >>=
zone_effect_L=read.coda(str_c(datawd,"zone_effect_LCODAchain1.txt"),str_c(datawd,"zone_effect_LCODAindex.txt"))

sum=summary(zone_effect_L, probs=seq(0,1,0.1))
zone_effect_L_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"zone_effect_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-4,4),ylab="zone_effect_L")

# trace l'axe des ordonnées
axis(2,at = seq(-4,4,by=1),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,1974+T)
axis(1,at = c(1,6,16,26,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#95%
	segments(i-0.15,zone_effect_L_q[i,5],i+0.15,zone_effect_L_q[i,5])
	segments(i,zone_effect_L_q[i,4],i,zone_effect_L_q[i,5])
	#5%
	segments(i-0.15,zone_effect_L_q[i,1],i+0.15,zone_effect_L_q[i,1])
	segments(i,zone_effect_L_q[i,2],i,zone_effect_L_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_L_q[i,2],zone_effect_L_q[i,2],zone_effect_L_q[i,4],zone_effect_L_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}zone_effect_L.png}%{a_juv.png}
     \caption{zone\_effect\_L}
     \label{zone_effect_L} 
\end{figure}
\clearpage
%-------------------------------------------
\subsection{zone\_effect\_Poutes}
%-------------------------------------------
<< zone_effect_P, echo=FALSE, eval=FALSE,results=hide >>=
zone_effect_P=read.coda(str_c(datawd,"zone_effect_PCODAchain1.txt"),str_c(datawd,"zone_effect_PCODAindex.txt"))

sum=summary(zone_effect_P, probs=seq(0,1,0.1))
zone_effect_P_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"zone_effect_P.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,29),xlab="Years",ylim=c(-4,4),ylab="zone_effect_P")

# trace l'axe des ordonnées
axis(2,at = seq(-4,4,by=1),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1986,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,(T-12)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-11)){
	#whiskers
	#95%
	segments(i-0.15,zone_effect_P_q[i,5],i+0.15,zone_effect_P_q[i,5])
	segments(i,zone_effect_P_q[i,4],i,zone_effect_P_q[i,5])
	#5%
	segments(i-0.15,zone_effect_P_q[i,1],i+0.15,zone_effect_P_q[i,1])
	segments(i,zone_effect_P_q[i,2],i,zone_effect_P_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_P_q[i,2],zone_effect_P_q[i,2],zone_effect_P_q[i,4],zone_effect_P_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=29,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}zone_effect_P.png}%{a_juv.png}
     \caption{zone\_effect\_P}
     \label{zone_effect_P} 
\end{figure}

\clearpage

%====================================
\section{N\_Vichy}
%====================================
<< N_vichy, echo=FALSE, eval=FALSE,results=hide >>=
N_vichy=read.coda(str_c(datawd,"N_vichyCODAchain1.txt"),str_c(datawd,"N_vichyCODAindex.txt"))

sum=summary(N_vichy, probs=seq(0,1,0.1))
N_vichy_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"N_vichy.png"),width=800,height=800)
plot(1,1,type="n",axes=FALSE,xlim=c(0,31),xlab="Years",ylim=c(0,15000),ylab="N_vichy")

# trace l'axe des ordonnées
axis(2,at = seq(0,15000,by=5000),labels=c(0,5000,10000,15000),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,6,16,26,30),
		labels=c(1975,1980,1990,2000,2004),
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:22){
	#whiskers
	#95%
	segments(i-0.15,N_vichy_q[i,5],i+0.15,N_vichy_q[i,5])
	segments(i,N_vichy_q[i,4],i,N_vichy_q[i,5])
	#5%
	segments(i-0.15,N_vichy_q[i,1],i+0.15,N_vichy_q[i,1])
	segments(i,N_vichy_q[i,2],i,N_vichy_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(N_vichy_q[i,2],N_vichy_q[i,2],N_vichy_q[i,4],N_vichy_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}
for(i in 30:30){
	#whiskers
	#95%
	segments(i-0.15,N_vichy_q[i-7,5],i+0.15,N_vichy_q[i-7,5])
	segments(i,N_vichy_q[i-7,4],i,N_vichy_q[i-7,5])
	#5%
	segments(i-0.15,N_vichy_q[i-7,1],i+0.15,N_vichy_q[i-7,1])
	segments(i,N_vichy_q[i-7,2],i,N_vichy_q[i-7,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(N_vichy_q[i-7,2],N_vichy_q[i-7,2],N_vichy_q[i-7,4],N_vichy_q[i-7,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i-7,],i+0.3,mean_res[i-7,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=31,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}N_vichy.png}%{a_juv.png}
     \caption{N\_vichy}
     \label{N_vichy} 
\end{figure}

\clearpage

%====================================
\section{N\_Alagnon}
%====================================
<< N_alagnon, echo=FALSE, eval=FALSE,results=hide >>=
N_alagnon=read.coda(str_c(datawd,"N_alagnonCODAchain1.txt"),str_c(datawd,"N_alagnonCODAindex.txt"))

sum=summary(N_alagnon, probs=seq(0,1,0.1))
N_alagnon_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"N_alagnon.png"),width=800,height=800)
plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1000),ylab="N_alagnon")

# trace l'axe des ordonnées
axis(2,at = seq(0,1000,by=200),labels=c(0,200,400,600,800,1000),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,6,16,26,36,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#95%
	segments(i-0.15,N_alagnon_q[i,5],i+0.15,N_alagnon_q[i,5])
	segments(i,N_alagnon_q[i,4],i,N_alagnon_q[i,5])
	#5%
	segments(i-0.15,N_alagnon_q[i,1],i+0.15,N_alagnon_q[i,1])
	segments(i,N_alagnon_q[i,2],i,N_alagnon_q[i,1])
#	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(N_alagnon_q[i,2],N_alagnon_q[i,2],N_alagnon_q[i,4],N_alagnon_q[i,4]),col="green")
#	#mean
#	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
	segments(i-0.3,N_alagnon_q[i,3],i+0.3,N_alagnon_q[i,3])
}


segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}N_alagnon.png}%{a_juv.png}
     \caption{N\_alagnon}
     \label{N_alagnon} 
\end{figure}

\clearpage

%====================================
\section{N\_Langeac}
%====================================
<< N_langeac, echo=FALSE, eval=FALSE,results=hide >>=
N_langeac=read.coda(str_c(datawd,"N_langeacCODAchain1.txt"),str_c(datawd,"N_langeacCODAindex.txt"))

sum=summary(N_langeac, probs=seq(0,1,0.1))
N_langeac_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"N_langeac.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,5000),ylab="N_langeac")

# trace l'axe des ordonnées
axis(2,at = seq(0,5000,by=1000),labels=c(0,1000,2000,3000,4000,5000),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1975,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,6,16,26,36,T),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:T){
	#whiskers
	#95%
	segments(i-0.15,N_langeac_q[i,5],i+0.15,N_langeac_q[i,5])
	segments(i,N_langeac_q[i,4],i,N_langeac_q[i,5])
	#5%
	segments(i-0.15,N_langeac_q[i,1],i+0.15,N_langeac_q[i,1])
	segments(i,N_langeac_q[i,2],i,N_langeac_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(N_langeac_q[i,2],N_langeac_q[i,2],N_langeac_q[i,4],N_langeac_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T+1,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}N_langeac.png}%{a_juv.png}
     \caption{N\_langeac}
     \label{N_langeac} 
\end{figure}

\clearpage

%====================================
\section{d\_wild\_moy}
%====================================
%------------------------------------
\subsection{d\_wild\_moy\_Vichy}
%------------------------------------
<< d_wild_moy_V, echo=FALSE, eval=FALSE,results=hide >>=
d_wild_moy_V=read.coda(str_c(datawd,"dmoywild_VCODAchain1.txt"),str_c(datawd,"dmoywild_VCODAindex.txt"))

sum=summary(d_wild_moy_V, probs=seq(0,1,0.1))
d_wild_moy_V_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"d_wild_moy_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,0.4),ylab="d_wild_moy_V")

# trace l'axe des ordonnées
axis(2,at = seq(0,0.4,by=0.1),labels=c(0,0.1,0.2,0.3,0.4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,d_wild_moy_V_q[i,5],i+0.15,d_wild_moy_V_q[i,5])
	segments(i,d_wild_moy_V_q[i,4],i,d_wild_moy_V_q[i,5])
	#5%
	segments(i-0.15,d_wild_moy_V_q[i,1],i+0.15,d_wild_moy_V_q[i,1])
	segments(i,d_wild_moy_V_q[i,2],i,d_wild_moy_V_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_wild_moy_V_q[i,2],d_wild_moy_V_q[i,2],d_wild_moy_V_q[i,4],d_wild_moy_V_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_wild_moy_V.png}%{a_juv.png}
     \caption{d\_wild\_moy\_V}
     \label{d_wild_moy_V} 
\end{figure}

\clearpage


%------------------------------------
\subsection{d\_wild\_moy\_Alagnon}
%------------------------------------
<< d_wild_moy_A, echo=FALSE, eval=FALSE,results=hide >>=
d_wild_moy_A=read.coda(str_c(datawd,"dmoywild_ACODAchain1.txt"),str_c(datawd,"dmoywild_ACODAindex.txt"))

sum=summary(d_wild_moy_A, probs=seq(0,1,0.1))
d_wild_moy_A_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"d_wild_moy_A.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1),ylab="d_wild_moy_A")

# trace l'axe des ordonnées
axis(2,at = seq(0,1,by=0.1),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,d_wild_moy_A_q[i,5],i+0.15,d_wild_moy_A_q[i,5])
	segments(i,d_wild_moy_A_q[i,4],i,d_wild_moy_A_q[i,5])
	#5%
	segments(i-0.15,d_wild_moy_A_q[i,1],i+0.15,d_wild_moy_A_q[i,1])
	segments(i,d_wild_moy_A_q[i,2],i,d_wild_moy_A_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_wild_moy_A_q[i,2],d_wild_moy_A_q[i,2],d_wild_moy_A_q[i,4],d_wild_moy_A_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_wild_moy_A.png}%{a_juv.png}
     \caption{d\_wild\_moy\_A}
     \label{d_wild_moy_A} 
\end{figure}

\clearpage

%------------------------------------
\subsection{d\_wild\_moy\_Langeac}
%------------------------------------
<< d_wild_moy_L, echo=FALSE, eval=FALSE,results=hide >>=
d_wild_moy_L=read.coda(str_c(datawd,"dmoywild_LCODAchain1.txt"),str_c(datawd,"dmoywild_LCODAindex.txt"))

sum=summary(d_wild_moy_L, probs=seq(0,1,0.1))
d_wild_moy_L_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"d_wild_moy_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,1),ylab="d_wild_moy_L")

# trace l'axe des ordonnées
axis(2,at = seq(0,1,by=0.2),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,d_wild_moy_L_q[i,5],i+0.15,d_wild_moy_L_q[i,5])
	segments(i,d_wild_moy_L_q[i,4],i,d_wild_moy_L_q[i,5])
	#5%
	segments(i-0.15,d_wild_moy_L_q[i,1],i+0.15,d_wild_moy_L_q[i,1])
	segments(i,d_wild_moy_L_q[i,2],i,d_wild_moy_L_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_wild_moy_L_q[i,2],d_wild_moy_L_q[i,2],d_wild_moy_L_q[i,4],d_wild_moy_L_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_wild_moy_L.png}%{a_juv.png}
     \caption{d\_wild\_moy\_L}
     \label{d_wild_moy_L} 
\end{figure}

\clearpage

%------------------------------------
\subsection{d\_wild\_moy\_Poutes}
%------------------------------------
<< d_wild_moy_P, echo=FALSE, eval=FALSE,results=hide >>=
d_wild_moy_P=read.coda(str_c(datawd,"dmoywild_PCODAchain1.txt"),str_c(datawd,"dmoywild_PCODAindex.txt"))

sum=summary(d_wild_moy_P, probs=seq(0,1,0.1))
d_wild_moy_P_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"d_wild_moy_P.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,(T-12+1)),xlab="Years",ylim=c(0,0.4),ylab="d_wild_moy_P")

# trace l'axe des ordonnées
axis(2,at = seq(0,0.4,by=0.1),labels=c(0,0.1,0.2,0.3,0.4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1987,1990,2000,2010,1974+T)
axis(1,at = c(1,4,14,24,(T-12)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-12)){
	#whiskers
	#95%
	segments(i-0.15,d_wild_moy_P_q[i,5],i+0.15,d_wild_moy_P_q[i,5])
	segments(i,d_wild_moy_P_q[i,4],i,d_wild_moy_P_q[i,5])
	#5%
	segments(i-0.15,d_wild_moy_P_q[i,1],i+0.15,d_wild_moy_P_q[i,1])
	segments(i,d_wild_moy_P_q[i,2],i,d_wild_moy_P_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_wild_moy_P_q[i,2],d_wild_moy_P_q[i,2],d_wild_moy_P_q[i,4],d_wild_moy_P_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=(T-12),col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_wild_moy_P.png}%{a_juv.png}
     \caption{d\_wild\_moy\_P}
     \label{d_wild_moy_P} 
\end{figure}

\clearpage

%====================================
\section{d\_juv\_moy}
%====================================
%------------------------------------
\subsection{d\_juv\_moy\_Vichy}
%------------------------------------
<< d_juv_moy_V, echo=FALSE, eval=FALSE,results=hide >>=
d_juv_moy_V=read.coda(str_c(datawd,"stocking_juv_VCODAchain1.txt"),str_c(datawd,"stocking_juv_VCODAindex.txt"))

#On a besoin de récupérer les données depuis Openbugs concernant les I_juv_moy
#pour ne pas les réécrire à la main et risquer de faire des erreurs

library(coda) 
bugs2jags(str_c(datawd,"data.txt"),"data_4zones_Interaction.R")
source("data_4zones_Interaction.R")
head(I_juv_moy) #ça marche !! :D

sum=summary(d_juv_moy_V, probs=seq(0,1,0.1))
d_juv_moy_V_q<-sum$quantiles
#On ne conserve que les lignes quand il y a déversement car sinon = à un tirage
#à blanc
d_juv_moy_V_q_dev<-d_juv_moy_V_q[I_juv_moy[2:41,1]==1,]

#On récupère les lignes quand I_juv_moy=0 et on met des NA partout
d_juv_moy_V_q_ss_dev<-d_juv_moy_V_q[I_juv_moy[2:41,1]==0,]
d_juv_moy_V_q_ss_dev_2<-matrix(rep(NA,17*5),nrow=17,ncol=5)
dimnames(d_juv_moy_V_q_ss_dev_2)<-dimnames(d_juv_moy_V_q_ss_dev)

#On fusionne les 2
d_juv_moy_V_q_2<-rbind(d_juv_moy_V_q_dev,d_juv_moy_V_q_ss_dev_2)
ord<-c(seq(24,27,by=1),1,seq(28,31,by=1),2,seq(32,37,by=1),3,38,39,seq(4,13,by=1),40,seq(14,23,by=1))
d_juv_moy_V_q<-d_juv_moy_V_q_2[ord,]

#On calcule les moyennes pour les années sans dev et on met NA partout
mean_res_na<-cbind(sum$statistics[I_juv_moy[2:41,1]==0,"Mean"])
mean_res_na_2<-matrix(c(rep(NA,nrow(mean_res_na))),nrow=17,ncol=1)
dimnames(mean_res_na_2)<-dimnames(mean_res_na)
#On fusionne les années avec et sans dev
mean_res<-rbind(cbind(sum$statistics[I_juv_moy[2:41,1]==1,"Mean"]),mean_res_na_2)
mean_res<-as.matrix(mean_res[ord,])


png(filename=str_c(imgwd,"d_juv_moy_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,0.3),ylab="d_juv_moy_V")

# trace l'axe des ordonnées
axis(2,at = seq(0,0.3,by=0.05),labels=c(0,0.05,0.1,0.15,0.2,0.25,0.3),cex.axis =
0.9,las = 1,col = "grey55") # trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,d_juv_moy_V_q[i,5],i+0.15,d_juv_moy_V_q[i,5])
	segments(i,d_juv_moy_V_q[i,4],i,d_juv_moy_V_q[i,5])
	#5%
	segments(i-0.15,d_juv_moy_V_q[i,1],i+0.15,d_juv_moy_V_q[i,1])
	segments(i,d_juv_moy_V_q[i,2],i,d_juv_moy_V_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_juv_moy_V_q[i,2],d_juv_moy_V_q[i,2],d_juv_moy_V_q[i,4],d_juv_moy_V_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res,na.rm=TRUE),y1=mean(mean_res,na.rm=TRUE),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_juv_moy_V.png}%{a_juv.png}
     \caption{d\_juv\_moy\_V}
     \label{d_juv_moy_V} 
\end{figure}

\clearpage

%------------------------------------
\subsection{d\_juv\_moy\_Alagnon}
%------------------------------------
<< d_juv_moy_A, echo=FALSE, eval=FALSE,results=hide >>=
d_juv_moy_A=read.coda(str_c(datawd,"stocking_juv_ACODAchain1.txt"),str_c(datawd,"stocking_juv_ACODAindex.txt"))

#On a besoin de récupérer les données depuis Openbugs concernant les I_juv_moy
#pour ne pas les réécrire à la main et risquer de faire des erreurs

library(coda) 
bugs2jags(str_c(datawd,"data.txt"),"data_4zones_Interaction.R")
source("data_4zones_Interaction.R")
head(I_juv_moy) #ça marche !! :D

sum=summary(d_juv_moy_A, probs=seq(0,1,0.1))
d_juv_moy_A_q<-sum$quantiles
#On ne conserve que les lignes quand il y a déversement car sinon = à un tirage
#à blanc
d_juv_moy_A_q_dev<-d_juv_moy_A_q[I_juv_moy[2:41,2]==1,]

#On récupère les lignes quand I_juv_moy=0 et on met des NA partout
d_juv_moy_A_q_ss_dev<-d_juv_moy_A_q[I_juv_moy[2:41,2]==0,]
d_juv_moy_A_q_ss_dev_2<-matrix(rep(NA,18*5),nrow=18,ncol=5)
dimnames(d_juv_moy_A_q_ss_dev_2)<-dimnames(d_juv_moy_A_q_ss_dev)

#On fusionne les 2
d_juv_moy_A_q_2<-rbind(d_juv_moy_A_q_dev,d_juv_moy_A_q_ss_dev_2)
ord<-c(1,23,2,24,25,3,4,26,5,seq(27,36,by=1),6,7,37,38,seq(8,10,
by=1),39,11,12,40,seq(13,22, by=1)) 

d_juv_moy_A_q<-d_juv_moy_A_q_2[ord,]

#On calcule les moyennes pour les années sans dev et on met NA partout
mean_res_na<-cbind(sum$statistics[I_juv_moy[2:41,2]==0,"Mean"])
mean_res_na_2<-matrix(c(rep(NA,nrow(mean_res_na))),nrow=18,ncol=1)
dimnames(mean_res_na_2)<-dimnames(mean_res_na)
#On fusionne les années avec et sans dev
mean_res<-rbind(cbind(sum$statistics[I_juv_moy[2:41,2]==1,"Mean"]),mean_res_na_2)
mean_res<-as.matrix(mean_res[ord,])



png(filename=str_c(imgwd,"d_juv_moy_A.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,2),ylab="d_juv_moy_A")

# trace l'axe des ordonnées
axis(2,at = seq(0,2,by=0.4),labels=c(0,0.4,0.8,1.2,1.6,2),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,d_juv_moy_A_q[i,5],i+0.15,d_juv_moy_A_q[i,5])
	segments(i,d_juv_moy_A_q[i,4],i,d_juv_moy_A_q[i,5])
	#5%
	segments(i-0.15,d_juv_moy_A_q[i,1],i+0.15,d_juv_moy_A_q[i,1])
	segments(i,d_juv_moy_A_q[i,2],i,d_juv_moy_A_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_juv_moy_A_q[i,2],d_juv_moy_A_q[i,2],d_juv_moy_A_q[i,4],d_juv_moy_A_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res,na.rm=TRUE),y1=mean(mean_res,na.rm=TRUE),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_juv_moy_A.png}%{a_juv.png}
     \caption{d\_juv\_moy\_A}
     \label{d_juv_moy_A} 
\end{figure}

\clearpage

%------------------------------------
\subsection{d\_juv\_moy\_Langeac}
%------------------------------------
<< d_juv_moy_L, echo=FALSE, eval=FALSE,results=hide >>=
d_juv_moy_L=read.coda(str_c(datawd,"stocking_juv_LCODAchain1.txt"),str_c(datawd,"stocking_juv_LCODAindex.txt"))

#On a besoin de récupérer les données depuis Openbugs concernant les I_juv_moy
#pour ne pas les réécrire à la main et risquer de faire des erreurs

library(coda) 
bugs2jags(str_c(datawd,"data.txt"),"data_4zones_Interaction.R")
source("data_4zones_Interaction.R")
head(I_juv_moy) #ça marche !! :D

sum=summary(d_juv_moy_L, probs=seq(0,1,0.1))
d_juv_moy_L_q<-sum$quantiles
#On ne conserve que les lignes quand il y a déversement car sinon = à un tirage
#à blanc
d_juv_moy_L_q_dev<-d_juv_moy_L_q[I_juv_moy[2:41,3]==1,]

#On récupère les lignes quand I_juv_moy=0 et on met des NA partout
d_juv_moy_L_q_ss_dev<-d_juv_moy_L_q[I_juv_moy[2:41,3]==0,]
d_juv_moy_L_q_ss_dev_2<-matrix(rep(NA,27*5),nrow=27,ncol=5)
dimnames(d_juv_moy_L_q_ss_dev_2)<-dimnames(d_juv_moy_L_q_ss_dev)

#On fusionne les 2
d_juv_moy_L_q_2<-rbind(d_juv_moy_L_q_dev,d_juv_moy_L_q_ss_dev_2)
ord<-c(seq(14,17,by=1),1,seq(18,27,by=1),2,seq(28,30,by=1),seq(3,6,by=1),31,seq(7,13,by=1),seq(32,40,
by=1))

d_juv_moy_L_q<-d_juv_moy_L_q_2[ord,]

#On calcule les moyennes pour les années sans dev et on met NA partout
mean_res_na<-cbind(sum$statistics[I_juv_moy[2:41,3]==0,"Mean"])
mean_res_na_2<-matrix(c(rep(NA,nrow(mean_res_na))),nrow=27,ncol=1)
dimnames(mean_res_na_2)<-dimnames(mean_res_na)
#On fusionne les années avec et sans dev
mean_res<-rbind(cbind(sum$statistics[I_juv_moy[2:41,3]==1,"Mean"]),mean_res_na_2)
mean_res<-as.matrix(mean_res[ord,])

png(filename=str_c(imgwd,"d_juv_moy_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(0,0.6),ylab="d_juv_moy_L")

# trace l'axe des ordonnées
axis(2,at = seq(0,0.6,by=0.1),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis =
0.9,las = 1,col = "grey55") # trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,d_juv_moy_L_q[i,5],i+0.15,d_juv_moy_L_q[i,5])
	segments(i,d_juv_moy_L_q[i,4],i,d_juv_moy_L_q[i,5])
	#5%
	segments(i-0.15,d_juv_moy_L_q[i,1],i+0.15,d_juv_moy_L_q[i,1])
	segments(i,d_juv_moy_L_q[i,2],i,d_juv_moy_L_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_juv_moy_L_q[i,2],d_juv_moy_L_q[i,2],d_juv_moy_L_q[i,4],d_juv_moy_L_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res,na.rm=TRUE),y1=mean(mean_res,na.rm=TRUE),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_juv_moy_L.png}%{a_juv.png}
     \caption{d\_juv\_moy\_L}
     \label{d_juv_moy_L} 
\end{figure}

\clearpage

%------------------------------------
\subsection{d\_juv\_moy\_Poutes}
%------------------------------------
<< d_juv_moy_P, echo=FALSE, eval=FALSE,results=hide >>=
d_juv_moy_P=read.coda(str_c(datawd,"stocking_juv_PCODAchain1.txt"),str_c(datawd,"stocking_juv_PCODAindex.txt"))


#On a besoin de récupérer les données depuis Openbugs concernant les I_juv_moy
#pour ne pas les réécrire à la main et risquer de faire des erreurs

library(coda) 
bugs2jags(str_c(datawd,"data.txt"),"data_4zones_Interaction.R")
source("data_4zones_Interaction.R")
head(I_juv_moy) #ça marche !! :D

sum=summary(d_juv_moy_P, probs=seq(0,1,0.1))
d_juv_moy_P_q<-sum$quantiles
#On ne conserve que les lignes quand il y a déversement car sinon = à un tirage
#à blanc
d_juv_moy_P_q_dev<-d_juv_moy_P_q[I_juv_moy[13:41,4]==1,]

#On récupère les lignes quand I_juv_moy=0 et on met des NA partout
d_juv_moy_P_q_ss_dev<-d_juv_moy_P_q[I_juv_moy[13:41,4]==0,]
d_juv_moy_P_q_ss_dev_2<-matrix(rep(NA,14*5),nrow=14,ncol=5)
dimnames(d_juv_moy_P_q_ss_dev_2)<-dimnames(d_juv_moy_P_q_ss_dev)

#On fusionne les 2
d_juv_moy_P_q_2<-rbind(d_juv_moy_P_q_dev,d_juv_moy_P_q_ss_dev_2)
ord<-c()

d_juv_moy_P_q<-d_juv_moy_P_q_2[ord,]

#On calcule les moyennes pour les années sans dev et on met NA partout
mean_res_na<-cbind(sum$statistics[I_juv_moy[2:41,4]==0,"Mean"])
mean_res_na_2<-matrix(c(rep(NA,nrow(mean_res_na))),nrow=27,ncol=1)
dimnames(mean_res_na_2)<-dimnames(mean_res_na)
#On fusionne les années avec et sans dev
mean_res<-rbind(cbind(sum$statistics[I_juv_moy[2:41,4]==1,"Mean"]),mean_res_na_2)
mean_res<-as.matrix(mean_res[ord,])


png(filename=str_c(imgwd,"d_juv_moy_P.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,28),xlab="Years",ylim=c(0,2),ylab="d_juv_moy_P")

# trace l'axe des ordonnées
axis(2,at = seq(0,2,by=0.4),labels=c(0,0.4,0.8,1.2,1.6,2),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1987,1990,2000,2010,1974+T)
axis(1,at = c(1,4,14,24,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:28){
	#whiskers
	#95%
	segments(i-0.15,d_juv_moy_P_q[i,5],i+0.15,d_juv_moy_P_q[i,5])
	segments(i,d_juv_moy_P_q[i,4],i,d_juv_moy_P_q[i,5])
	#5%
	segments(i-0.15,d_juv_moy_P_q[i,1],i+0.15,d_juv_moy_P_q[i,1])
	segments(i,d_juv_moy_P_q[i,2],i,d_juv_moy_P_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(d_juv_moy_P_q[i,2],d_juv_moy_P_q[i,2],d_juv_moy_P_q[i,4],d_juv_moy_P_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=29,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_juv_moy_P.png}%{a_juv.png}
     \caption{d\_juv\_moy\_P}
     \label{d_juv_moy_P} 
\end{figure}

\clearpage

%====================================
\section{d\_egg\_moy}
%====================================
%------------------------------------
\subsection{d\_egg\_moy\_Vichy}
%------------------------------------
<< d_egg_moy_V, echo=FALSE, eval=FALSE,results=hide >>=
d_egg_moy_V=read.coda(str_c(datawd,"stocking_egg_VCODAchain1.txt"),str_c(datawd,"stocking_egg_VCODAindex.txt"))

sum=summary(d_egg_moy_V, probs=seq(0,1,0.1))
d_egg_moy_V_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"d_egg_moy_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,19),xlab="Years",ylim=c(0,0.02),ylab="d_egg_moy_V")

# trace l'axe des ordonnées
axis(2,at = seq(0,0.02,by=0.01),labels=c(0,0.01,0.02),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1996,2000,2010,1974+T)
axis(1,at = c(1,4,14,(T-21)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 10:27){
	#whiskers
	#95%
	segments(i-9.15,d_egg_moy_V_q[i,5],i-9+0.15,d_egg_moy_V_q[i,5])
	segments(i-9,d_egg_moy_V_q[i,4],i-9,d_egg_moy_V_q[i,5])
	#5%
	segments(i-9.15,d_egg_moy_V_q[i,1],i-9+0.15,d_egg_moy_V_q[i,1])
	segments(i-9,d_egg_moy_V_q[i,2],i-9,d_egg_moy_V_q[i,1])
	#boxplot
	polygon(c(i-9.3,i-9+0.3,i-9+0.3,i-9.3),c(d_egg_moy_V_q[i,2],d_egg_moy_V_q[i,2],d_egg_moy_V_q[i,4],d_egg_moy_V_q[i,4]),col="green")
	#mean
	segments(i-9.3,mean_res[i,],i-9+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res[10:27]),y1=mean(mean_res[10:27]),x1=19,col="red")
mtext(round(mean(mean_res[10:27]),5),side=4,line=0,at=mean(mean_res[10:27]),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_egg_moy_V.png}%{a_juv.png}
     \caption{d\_egg\_moy\_V}
     \label{d_egg_moy_V} 
\end{figure}

\clearpage

%------------------------------------
\subsection{d\_egg\_moy\_Langeac}
%------------------------------------
<< d_egg_moy_L, echo=FALSE, eval=FALSE,results=hide >>=
d_egg_moy_L=read.coda(str_c(datawd,"stocking_egg_LCODAchain1.txt"),str_c(datawd,"stocking_egg_LCODAindex.txt"))

sum=summary(d_egg_moy_L, probs=seq(0,1,0.1))
d_egg_moy_L_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"d_egg_moy_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,12),xlab="Years",ylim=c(0,0.05),ylab="d_egg_moy_L")

# trace l'axe des ordonnées
axis(2,at = seq(0,0.05,by=0.01),labels=c(0,0.01,0.02,0.03,0.04,0.05),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,3,11),
		labels=c(1997,2000,2008),
		cex.axis = 0.9,las = 1,col = "grey55")


for(i in 12:22){
	#whiskers
	#95%
	segments(i-11.15,d_egg_moy_L_q[i,5],i-11+0.15,d_egg_moy_L_q[i,5])
	segments(i-11,d_egg_moy_L_q[i,4],i-11,d_egg_moy_L_q[i,5])
	#5%
	segments(i-11.15,d_egg_moy_L_q[i,1],i-11+0.15,d_egg_moy_L_q[i,1])
	segments(i-11,d_egg_moy_L_q[i,2],i-11,d_egg_moy_L_q[i,1])
	#boxplot
	polygon(c(i-11.3,i-11+0.3,i-11+0.3,i-11.3),c(d_egg_moy_L_q[i,2],d_egg_moy_L_q[i,2],d_egg_moy_L_q[i,4],d_egg_moy_L_q[i,4]),col="green")
	#mean
	segments(i-11.3,mean_res[i,],i-11+0.3,mean_res[i,])
}


segments(x0=0,y0=mean(mean_res[12:22]),y1=mean(mean_res[12:22]),x1=12,col="red")
mtext(round(mean(mean_res[12:22]),5),side=4,line=0,at=mean(mean_res[12:22]),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}d_egg_moy_L.png}%{a_juv.png}
     \caption{d\_egg\_moy\_L}
     \label{d_egg_moy_L} 
\end{figure}

\clearpage

%====================================
\section{res\_wild\_moy}
%====================================
%------------------------------------
\subsection{res\_wild\_moy\_Vichy}
%------------------------------------
<< res_wild_moy_V, echo=FALSE, eval=FALSE,results=hide >>=
res_wild_moy_V=read.coda(str_c(datawd,"res_wild_VCODAchain1.txt"),str_c(datawd,"res_wild_VCODAindex.txt"))

sum=summary(res_wild_moy_V, probs=seq(0,1,0.1))
res_wild_moy_V_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_wild_moy_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-2,2),ylab="res_wild_moy_V")

# trace l'axe des ordonnées
axis(2,at = seq(-2,2,by=0.5),labels=c(-2,-1.5,-1,-0.5,0,0.5,1,1.5,2),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_wild_moy_V_q[i,5],i+0.15,res_wild_moy_V_q[i,5])
	segments(i,res_wild_moy_V_q[i,4],i,res_wild_moy_V_q[i,5])
	#5%
	segments(i-0.15,res_wild_moy_V_q[i,1],i+0.15,res_wild_moy_V_q[i,1])
	segments(i,res_wild_moy_V_q[i,2],i,res_wild_moy_V_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_moy_V_q[i,2],res_wild_moy_V_q[i,2],res_wild_moy_V_q[i,4],res_wild_moy_V_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_wild_moy_V.png}%{a_juv.png}
     \caption{res\_wild\_moy\_V}
     \label{res_wild_moy_V} 
\end{figure}

\clearpage

%------------------------------------
\subsection{res\_wild\_moy\_Alagnon}
%------------------------------------
<< res_wild_moy_A, echo=FALSE, eval=FALSE,results=hide >>=
res_wild_moy_A=read.coda(str_c(datawd,"res_wild_ACODAchain1.txt"),str_c(datawd,"res_wild_ACODAindex.txt"))

sum=summary(res_wild_moy_A, probs=seq(0,1,0.1))
res_wild_moy_A_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_wild_moy_A.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-2,2),ylab="res_wild_moy_A")

# trace l'axe des ordonnées
axis(2,at = seq(-2,2,by=0.5),labels=c(-2,-1.5,-1,-0.5,0,0.5,1,1.5,2),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_wild_moy_A_q[i,5],i+0.15,res_wild_moy_A_q[i,5])
	segments(i,res_wild_moy_A_q[i,4],i,res_wild_moy_A_q[i,5])
	#5%
	segments(i-0.15,res_wild_moy_A_q[i,1],i+0.15,res_wild_moy_A_q[i,1])
	segments(i,res_wild_moy_A_q[i,2],i,res_wild_moy_A_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_moy_A_q[i,2],res_wild_moy_A_q[i,2],res_wild_moy_A_q[i,4],res_wild_moy_A_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_wild_moy_A.png}%{a_juv.png}
     \caption{res\_wild\_moy\_A}
     \label{res_wild_moy_A} 
\end{figure}

\clearpage

%------------------------------------
\subsection{res\_wild\_moy\_Langeac}
%------------------------------------
<< res_wild_moy_L, echo=FALSE, eval=FALSE,results=hide >>=
res_wild_moy_L=read.coda(str_c(datawd,"res_wild_LCODAchain1.txt"),str_c(datawd,"res_wild_LCODAindex.txt"))

sum=summary(res_wild_moy_L, probs=seq(0,1,0.1))
res_wild_moy_L_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_wild_moy_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-3,3),ylab="res_wild_moy_L")

# trace l'axe des ordonnées
axis(2,at = seq(-3,3,by=0.5),labels=TRUE,cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_wild_moy_L_q[i,5],i+0.15,res_wild_moy_L_q[i,5])
	segments(i,res_wild_moy_L_q[i,4],i,res_wild_moy_L_q[i,5])
	#5%
	segments(i-0.15,res_wild_moy_L_q[i,1],i+0.15,res_wild_moy_L_q[i,1])
	segments(i,res_wild_moy_L_q[i,2],i,res_wild_moy_L_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_moy_L_q[i,2],res_wild_moy_L_q[i,2],res_wild_moy_L_q[i,4],res_wild_moy_L_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_wild_moy_L.png}%{a_juv.png}
     \caption{res\_wild\_moy\_L}
     \label{res_wild_moy_L} 
\end{figure}

\clearpage

%------------------------------------
\subsection{res\_wild\_moy\_Poutes}
%------------------------------------
<< res_wild_moy_P, echo=FALSE, eval=FALSE,results=hide >>=
res_wild_moy_P=read.coda(str_c(datawd,"res_wild_PCODAchain1.txt"),str_c(datawd,"res_wild_PCODAindex.txt"))

sum=summary(res_wild_moy_P, probs=seq(0,1,0.1))
res_wild_moy_P_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_wild_moy_P.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,(T-12+1)),xlab="Years",ylim=c(-2,2),ylab="res_wild_moy_P")

# trace l'axe des ordonnées
axis(2,at = seq(-2,2,by=0.5),labels=TRUE,cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1987,1990,2000,2010,1974+T)
axis(1,at = c(1,4,14,24,(T-12)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-12)){                                                                                                                                                                                                                                                                               
	#whiskers
	#95%
	segments(i-0.15,res_wild_moy_P_q[i,5],i+0.15,res_wild_moy_P_q[i,5])
	segments(i,res_wild_moy_P_q[i,4],i,res_wild_moy_P_q[i,5])
	#5%
	segments(i-0.15,res_wild_moy_P_q[i,1],i+0.15,res_wild_moy_P_q[i,1])
	segments(i,res_wild_moy_P_q[i,2],i,res_wild_moy_P_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_moy_P_q[i,2],res_wild_moy_P_q[i,2],res_wild_moy_P_q[i,4],res_wild_moy_P_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=29,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_wild_moy_P.png}%{a_juv.png}
     \caption{res\_wild\_moy\_P}
     \label{res_wild_moy_P} 
\end{figure}

\clearpage

%====================================
\section{res\_juv\_moy}
%====================================
%------------------------------------
\subsection{res\_juv\_moy\_Vichy}
%------------------------------------
<< res_juv_moy_V, echo=FALSE, eval=FALSE,results=hide >>=
res_juv_moy_V=read.coda(str_c(datawd,"res_juv_VCODAchain1.txt"),str_c(datawd,"res_juv_VCODAindex.txt"))

sum=summary(res_juv_moy_V, probs=seq(0,1,0.1))
res_juv_moy_V_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_juv_moy_V.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-3,3),ylab="res_juv_moy_V")

# trace l'axe des ordonnées
axis(2,at = seq(-3,3,by=0.5),labels=TRUE,cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_juv_moy_V_q[i,5],i+0.15,res_juv_moy_V_q[i,5])
	segments(i,res_juv_moy_V_q[i,4],i,res_juv_moy_V_q[i,5])
	#5%
	segments(i-0.15,res_juv_moy_V_q[i,1],i+0.15,res_juv_moy_V_q[i,1])
	segments(i,res_juv_moy_V_q[i,2],i,res_juv_moy_V_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_juv_moy_V_q[i,2],res_juv_moy_V_q[i,2],res_juv_moy_V_q[i,4],res_juv_moy_V_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_juv_moy_V.png}%{a_juv.png}
     \caption{res\_juv\_moy\_V}
     \label{res_juv_moy_V} 
\end{figure}

\clearpage

%------------------------------------
\subsection{res\_juv\_moy\_Alagnon}
%------------------------------------
<< res_juv_moy_A, echo=FALSE, eval=FALSE,results=hide >>=
res_juv_moy_A=read.coda(str_c(datawd,"res_juv_ACODAchain1.txt"),str_c(datawd,"res_juv_ACODAindex.txt"))

sum=summary(res_juv_moy_A, probs=seq(0,1,0.1))
res_juv_moy_A_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_juv_moy_A.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-3,3),ylab="res_juv_moy_A")

# trace l'axe des ordonnées
axis(2,at = seq(-3,3,by=0.5),labels=TRUE,cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,2010,1974+T)
axis(1,at = c(1,5,15,25,35,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_juv_moy_A_q[i,5],i+0.15,res_juv_moy_A_q[i,5])
	segments(i,res_juv_moy_A_q[i,4],i,res_juv_moy_A_q[i,5])
	#5%
	segments(i-0.15,res_juv_moy_A_q[i,1],i+0.15,res_juv_moy_A_q[i,1])
	segments(i,res_juv_moy_A_q[i,2],i,res_juv_moy_A_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_juv_moy_A_q[i,2],res_juv_moy_A_q[i,2],res_juv_moy_A_q[i,4],res_juv_moy_A_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_juv_moy_A.png}%{a_juv.png}
     \caption{res\_juv\_moy\_A}
     \label{res_juv_moy_A} 
\end{figure}

\clearpage


%------------------------------------
\subsection{res\_juv\_moy\_Langeac}
%------------------------------------
<< res_juv_moy_L, echo=FALSE, eval=FALSE,results=hide >>=
res_juv_moy_L=read.coda(str_c(datawd,"res_juv_LCODAchain1.txt"),str_c(datawd,"res_juv_LCODAindex.txt"))

sum=summary(res_juv_moy_L, probs=seq(0,1,0.1))
res_juv_moy_L_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_juv_moy_L.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,T),xlab="Years",ylim=c(-3,3),ylab="res_juv_moy_L")

# trace l'axe des ordonnées
axis(2,at = seq(-3,3,by=0.5),labels=TRUE,cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1976,1980,1990,2000,1974+T)
axis(1,at = c(1,5,15,25,(T-1)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_juv_moy_L_q[i,5],i+0.15,res_juv_moy_L_q[i,5])
	segments(i,res_juv_moy_L_q[i,4],i,res_juv_moy_L_q[i,5])
	#5%
	segments(i-0.15,res_juv_moy_L_q[i,1],i+0.15,res_juv_moy_L_q[i,1])
	segments(i,res_juv_moy_L_q[i,2],i,res_juv_moy_L_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_juv_moy_L_q[i,2],res_juv_moy_L_q[i,2],res_juv_moy_L_q[i,4],res_juv_moy_L_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=T,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_juv_moy_L.png}%{a_juv.png}
     \caption{res\_juv\_moy\_L}
     \label{res_juv_moy_L} 
\end{figure}

\clearpage

%------------------------------------
\subsection{res\_juv\_moy\_Poutes}
%------------------------------------
<< res_juv_moy_P, echo=FALSE, eval=FALSE,results=hide >>=
res_juv_moy_P=read.coda(str_c(datawd,"res_juv_PCODAchain1.txt"),str_c(datawd,"res_juv_PCODAindex.txt"))

sum=summary(res_juv_moy_P, probs=seq(0,1,0.1))
res_juv_moy_P_q<-sum$quantiles
mean_res<-cbind(sum$statistics[,"Mean"])


png(filename=str_c(imgwd,"res_juv_moy_P.png"),width=800,height=800)

plot(1,1,type="n",axes=FALSE,xlim=c(0,29),xlab="Years",ylim=c(-3,3),ylab="res_juv_moy_P")

# trace l'axe des ordonnées
axis(2,at = seq(-3,3,by=0.5),labels=TRUE,cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
lab1=c(1987,1990,2000,2010,1974+T)
axis(1,at = c(1,4,14,24,(T-12)),
		labels=lab1,
		cex.axis = 0.9,las = 1,col = "grey55")

for(i in 1:28){
	#whiskers
	#95%
	segments(i-0.15,res_juv_moy_P_q[i,5],i+0.15,res_juv_moy_P_q[i,5])
	segments(i,res_juv_moy_P_q[i,4],i,res_juv_moy_P_q[i,5])
	#5%
	segments(i-0.15,res_juv_moy_P_q[i,1],i+0.15,res_juv_moy_P_q[i,1])
	segments(i,res_juv_moy_P_q[i,2],i,res_juv_moy_P_q[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_juv_moy_P_q[i,2],res_juv_moy_P_q[i,2],res_juv_moy_P_q[i,4],res_juv_moy_P_q[i,4]),col="green")
	#mean
	segments(i-0.3,mean_res[i,],i+0.3,mean_res[i,])
}

segments(x0=0,y0=mean(mean_res),y1=mean(mean_res),x1=29,col="red")
mtext(round(mean(mean_res),5),side=4,line=0,at=mean(mean_res),cex = 0.8,col="red",las=1)
dev.off()
@

\begin{figure}[ht]
     \includegraphics{\Sexpr{imgwd}res_juv_moy_P.png}%{a_juv.png}
     \caption{res\_juv\_moy\_P}
     \label{res_juv_moy_P} 
\end{figure}

\clearpage
\end{document}
