% 
\documentclass[a4paper]{article}
\usepackage{Sweave}
\usepackage[latin1]{inputenc} %encodage du fichier source
\usepackage[T1]{fontenc}  %gestion des accents (pour les pdf) 
\usepackage[francais]{babel}
\usepackage{float}
\usepackage[section]{placeins}%The placeins package provides the command \FloatBarrier 
\usepackage{amsmath} % equation numbering
\usepackage[colorlinks=true,urlcolor=blue,linkcolor=black,citecolor=black]{hyperref}
\usepackage{wrapfig}
\usepackage{subcaption} % pour les subfigures
\usepackage{vmargin}
\setpapersize{A4}
\setmarginsrb{15mm}{15mm}{15mm}{15mm}{12pt}{0mm}{0pt}{11mm}
\pagestyle{empty}
%1 est la marge gauche
%2 est la marge en haut
%3 est la marge droite
%4 est la marge en bas
%5 fixe la hauteur de l'entête
%6 fixe la distance entre l'entête et le texte
%7 fixe la hauteur du pied de page
%8 fixe la distance entre le texte et le pied de page

\title{Sortie des figures du modèle V_2014_12_05}
\author{Marion Legrand,\\Guillaume Dauphin,\\Etienne Prevost}

\begin{document}
\maketitle
\newpage

%=================================================================================
\section{Figures-Modèle}
%=================================================================================

<< init, echo=FALSE, eval=FALSE,results=hide >>=
	setwd("C:/Users/LOGRAMI/workspace/ModeleDynamiquePop")
	
	m2014_12_05<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/CODA/2014_12_05_Poutes/"#2014_12_05
	imgwd_2014_12_05<-"C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/img/2014_12_05_Poutes/"
	
	captrois<-iconv("Modèle 2014_12_05","UTF-8","LATIN1")

	

library(lattice)
library(coda)
library(boot)
require(stringr)

T=39

###################
# CHAP: SPAWNERS 
###################

N_vichy_real_m2014_12_05=read.coda(str_c(m2014_12_05,"N_vichyCODAchain1.txt"),str_c(m2014_12_05,"N_vichyCODAindex.txt"))

N_vichy_real_q_m2014_12_05=array(0,dim=c(42,5))

for (t in 1:42){
	N_vichy_real_q_m2014_12_05[t,]=quantile(N_vichy_real_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}

########################
# CHAP: SPAWNERS_REDDS 
########################
S_vichy_real_m2014_12_05=read.coda(str_c(m2014_12_05,"S_vichyCODAchain1.txt"),str_c(m2014_12_05,"S_vichyCODAindex.txt"))
S_langeac_real_m2014_12_05=read.coda(str_c(m2014_12_05,"S_langeacCODAchain1.txt"),str_c(m2014_12_05,"S_langeacCODAindex.txt"))

S_vichy_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
S_langeac_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

S_poutes_counter=c(
		0,0,
		0,0,0,0,0,
		0,0,0,0,10,
		43,110,21,4,3,
		11,9,23,6,67,
		35,31,130,112,53,
		40,154,89,74,153,
		53,39,14,26,118,59,45)

ratio_S_V_m2014_12_05=array(0,c(5000,T))
ratio_S_L_m2014_12_05=array(0,c(5000,T))
ratio_S_P_m2014_12_05=array(0,c(5000,T))


#ratio

for (t in 1:11){
	
	for(i in 1:5000){
		ratio_S_V_m2014_12_05[i,t] = S_vichy_real_m2014_12_05[i,t] / (S_vichy_real_m2014_12_05[i,t] + S_langeac_real_m2014_12_05[i,t])
		ratio_S_L_m2014_12_05[i,t] = 1 - ratio_S_V_m2014_12_05[i,t]
	}
}


for (t in 12:T){
	
	for( i in 1:5000){
		ratio_S_V_m2014_12_05[i,t] = S_vichy_real_m2014_12_05[i,t] / (S_vichy_real_m2014_12_05[i,t] + S_langeac_real_m2014_12_05[i,t] + S_poutes_counter[t])
		ratio_S_L_m2014_12_05[i,t] = S_langeac_real_m2014_12_05[i,t] / (S_vichy_real_m2014_12_05[i,t] + S_langeac_real_m2014_12_05[i,t] + S_poutes_counter[t])
		ratio_S_P_m2014_12_05[i,t] = 1 - ratio_S_V_m2014_12_05[i,t] -ratio_S_L_m2014_12_05[i,t]
	}
}

ratio_S_V_q_m2014_12_05=array(0,c(T,5))
ratio_S_L_q_m2014_12_05=array(0,c(T,5))
ratio_S_P_q_m2014_12_05=array(0,c(T,5))


for (t in 1:T){
	
	ratio_S_V_q_m2014_12_05[t,]=quantile(ratio_S_V_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	ratio_S_L_q_m2014_12_05[t,]=quantile(ratio_S_L_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	ratio_S_P_q_m2014_12_05[t,]=quantile(ratio_S_P_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}


for (i in 1:T){
	S_vichy_q_m2014_12_05[i,]=quantile(S_vichy_real_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	
}
for (i in 1:T){
	S_langeac_q_m2014_12_05[i,]=quantile(S_langeac_real_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}


###############
# CHAP: REDDS 
###############

#Chargement pour les 3 modèles
zone_effect_V_m2014_12_05=read.coda(str_c(m2014_12_05,"/zone_effect_VCODAchain1.txt"),str_c(m2014_12_05,"/zone_effect_VCODAindex.txt"))
zone_effect_L_m2014_12_05=read.coda(str_c(m2014_12_05,"/zone_effect_LCODAchain1.txt"),str_c(m2014_12_05,"/zone_effect_LCODAindex.txt"))
zone_effect_P_m2014_12_05=read.coda(str_c(m2014_12_05,"/zone_effect_PCODAchain1.txt"),str_c(m2014_12_05,"/zone_effect_PCODAindex.txt"))

zone_effect_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
zone_effect_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
zone_effect_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))


for (i in 1:T){
	zone_effect_V_q_m2014_12_05[i,]=quantile(zone_effect_V_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	zone_effect_L_q_m2014_12_05[i,]=quantile(zone_effect_L_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}

for (i in 12:T){
	zone_effect_P_q_m2014_12_05[i,]=quantile(zone_effect_P_m2014_12_05[,i-11],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}

mu_zone_m2014_12_05=read.coda(str_c(m2014_12_05,"/mu_zoneCODAchain1.txt"),str_c(m2014_12_05,"/mu_zoneCODAindex.txt"))
beta_zone_m2014_12_05=read.coda(str_c(m2014_12_05,"/beta_zoneCODAchain1.txt"),str_c(m2014_12_05,"/beta_zoneCODAindex.txt"))

mu_zone_q_m2014_12_05=array(rep(0,10),dim=c(1,5))
mu_zone_q_m2014_12_05[1,]=quantile(mu_zone_m2014_12_05[,1],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)

#mu_zone_q[2,]=quantile(mu_zone[,2],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
beta_zone_q_m2014_12_05=quantile(beta_zone_m2014_12_05,probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
N_langeac_m2014_12_05=read.coda(str_c(m2014_12_05,"/N_LCODAchain1.txt"),str_c(m2014_12_05,"/N_LCODAindex.txt"),5001,10000)

C_langeac=c(189,216,142,246,107,95)
p_count_L_m2014_12_05=array(rep(0,30000),dim=c(5000,6))

for (t in 1:6){
	p_count_L_m2014_12_05[,t]=C_langeac[t]/N_langeac_m2014_12_05[,26+t]
		
}

p_count_L_q_m2014_12_05=array(rep(0,35),dim=c(6,5))

for (t in 1:6){
	p_count_L_q_m2014_12_05[t,]=quantile(p_count_L_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}

##########################
# CHAP:Densité juvénile
##########################
dmoy_tot_V_m2014_12_05=read.coda(str_c(m2014_12_05,"dmoytot_VCODAchain1.txt"),str_c(m2014_12_05,"dmoytot_VCODAindex.txt"),5001,10000)
dmoy_tot_L_m2014_12_05=read.coda(str_c(m2014_12_05,"dmoytot_LCODAchain1.txt"),str_c(m2014_12_05,"dmoytot_LCODAindex.txt"),5001,10000)
dmoy_tot_P_m2014_12_05=read.coda(str_c(m2014_12_05,"dmoytot_PCODAchain1.txt"),str_c(m2014_12_05,"dmoytot_PCODAindex.txt"),5001,10000)

dmoy_wild_V_m2014_12_05=read.coda(str_c(m2014_12_05,"dmoywild_VCODAchain1.txt"),str_c(m2014_12_05,"dmoywild_VCODAindex.txt"),5001,10000)
dmoy_wild_L_m2014_12_05=read.coda(str_c(m2014_12_05,"dmoywild_LCODAchain1.txt"),str_c(m2014_12_05,"dmoywild_LCODAindex.txt"),5001,10000)
dmoy_wild_P_m2014_12_05=read.coda(str_c(m2014_12_05,"dmoywild_PCODAchain1.txt"),str_c(m2014_12_05,"dmoywild_PCODAindex.txt"),5001,10000)

stocking_juv_V_m2014_12_05=read.coda(str_c(m2014_12_05,"stocking_juv_VCODAchain1.txt"),str_c(m2014_12_05,"stocking_juv_VCODAindex.txt"),5001,10000)
stocking_juv_L_m2014_12_05=read.coda(str_c(m2014_12_05,"stocking_juv_LCODAchain1.txt"),str_c(m2014_12_05,"stocking_juv_LCODAindex.txt"),5001,10000)
stocking_juv_P_m2014_12_05=read.coda(str_c(m2014_12_05,"stocking_juv_PCODAchain1.txt"),str_c(m2014_12_05,"stocking_juv_PCODAindex.txt"),5001,10000)

stocking_egg_V_m2014_12_05=read.coda(str_c(m2014_12_05,"stocking_egg_VCODAchain1.txt"),str_c(m2014_12_05,"stocking_egg_VCODAindex.txt"),5001,10000)
stocking_egg_L_m2014_12_05=read.coda(str_c(m2014_12_05,"stocking_egg_LCODAchain1.txt"),str_c(m2014_12_05,"stocking_egg_LCODAindex.txt"),5001,10000)

res_wild_V_m2014_12_05=read.coda(str_c(m2014_12_05,"res_wild_VCODAchain1.txt"),str_c(m2014_12_05,"res_wild_VCODAindex.txt"))
res_wild_L_m2014_12_05=read.coda(str_c(m2014_12_05,"res_wild_LCODAchain1.txt"),str_c(m2014_12_05,"res_wild_LCODAindex.txt"))
res_wild_P_m2014_12_05=read.coda(str_c(m2014_12_05,"res_wild_PCODAchain1.txt"),str_c(m2014_12_05,"res_wild_PCODAindex.txt"))

res_juv_V_m2014_12_05=read.coda(str_c(m2014_12_05,"res_juv_VCODAchain1.txt"),str_c(m2014_12_05,"res_juv_VCODAindex.txt"))
res_juv_L_m2014_12_05=read.coda(str_c(m2014_12_05,"res_juv_LCODAchain1.txt"),str_c(m2014_12_05,"res_juv_LCODAindex.txt"))
res_juv_P_m2014_12_05=read.coda(str_c(m2014_12_05,"res_juv_PCODAchain1.txt"),str_c(m2014_12_05,"res_juv_PCODAindex.txt"))

res_egg_V_m2014_12_05=read.coda(str_c(m2014_12_05,"res_egg_VCODAchain1.txt"),str_c(m2014_12_05,"res_egg_VCODAindex.txt"))
res_egg_L_m2014_12_05=read.coda(str_c(m2014_12_05,"res_egg_LCODAchain1.txt"),str_c(m2014_12_05,"res_egg_LCODAindex.txt"))

dmoy_tot_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_tot_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_tot_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

dmoy_wild_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_wild_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_wild_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

dmoy_juv_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_juv_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_juv_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

dmoy_egg_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
dmoy_egg_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

res_wild_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
res_wild_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
res_wild_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

res_juv_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
res_juv_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
res_juv_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

res_egg_V_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
res_egg_L_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))


for (i in 1:(T-1)){
	dmoy_tot_V_q_m2014_12_05[i+1,]=quantile(dmoy_tot_V_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	dmoy_tot_L_q_m2014_12_05[i+1,]=quantile(dmoy_tot_L_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	dmoy_wild_V_q_m2014_12_05[i+1,]=quantile(dmoy_wild_V_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	
	dmoy_wild_L_q_m2014_12_05[i+1,]=quantile(dmoy_wild_L_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	dmoy_juv_V_q_m2014_12_05[i+1,]=quantile(stocking_juv_V_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	dmoy_juv_L_q_m2014_12_05[i+1,]=quantile(stocking_juv_L_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	
	res_wild_V_q_m2014_12_05[i+1,]=quantile(res_wild_V_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	res_wild_L_q_m2014_12_05[i+1,]=quantile(res_wild_L_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	res_juv_V_q_m2014_12_05[i+1,]=quantile(res_juv_V_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	res_juv_L_q_m2014_12_05[i+1,]=quantile(res_juv_L_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	
}


for (i in 1:(T-12)){
	dmoy_tot_P_q_m2014_12_05[i+12,]=quantile(dmoy_tot_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	dmoy_wild_P_q_m2014_12_05[i+12,]=quantile(dmoy_wild_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	dmoy_juv_P_q_m2014_12_05[i+12,]=quantile(stocking_juv_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	
	res_wild_P_q_m2014_12_05[i+12,]=quantile(res_wild_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	res_juv_P_q_m2014_12_05[i+12,]=quantile(res_juv_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	res_egg_V_q_m2014_12_05[i+12,]=quantile(res_egg_V_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	
	res_egg_L_q_m2014_12_05[i+12,]=quantile(res_egg_L_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
		
}

for (i in 21:(T-1)){
	dmoy_egg_V_q_m2014_12_05[i,]=quantile(stocking_egg_V_m2014_12_05[,i-11],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
	
}

for (i in 23:33){
	dmoy_egg_L_q_m2014_12_05[i,]=quantile(stocking_egg_L_m2014_12_05[,i-11],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

################################
# CHAP:Juvenile cohorte RATIO
################################
#===============
# SEC: ratio
#===============
#-----------------
# Ratio Géniteurs
#-----------------
ratio_S_V_m2014_12_05=array(0,c(5000,T))
ratio_S_L_m2014_12_05=array(0,c(5000,T))
ratio_S_P_m2014_12_05=array(0,c(5000,T))

for (t in 1:12){
	for(i in 1:5000){
		ratio_S_V_m2014_12_05[i,t] = S_vichy_real_m2014_12_05[i,t] / (S_vichy_real_m2014_12_05[i,t] + S_langeac_real_m2014_12_05[i,t])
		ratio_S_L_m2014_12_05[i,t] = 1 - ratio_S_V_m2014_12_05[i,t]
	}
}
for (t in 13:T){
	
	for( i in 1:5000){
		ratio_S_V_m2014_12_05[i,t] = S_vichy_real_m2014_12_05[i,t] / (S_vichy_real_m2014_12_05[i,t] + S_langeac_real_m2014_12_05[i,t] + S_poutes_counter[t])
		ratio_S_L_m2014_12_05[i,t] = S_langeac_real_m2014_12_05[i,t] / (S_vichy_real_m2014_12_05[i,t] + S_langeac_real_m2014_12_05[i,t] + S_poutes_counter[t])
		ratio_S_P_m2014_12_05[i,t] = 1 - ratio_S_V_m2014_12_05[i,t] -ratio_S_L_m2014_12_05[i,t]
	}
}

ratio_S_V_q_m2014_12_05=array(0,c(T,5))
ratio_S_L_q_m2014_12_05=array(0,c(T,5))
ratio_S_P_q_m2014_12_05=array(0,c(T,5))

for (t in 1:T){
	
	ratio_S_V_q_m2014_12_05[t,]=quantile(ratio_S_V_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	ratio_S_L_q_m2014_12_05[t,]=quantile(ratio_S_L_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	ratio_S_P_q_m2014_12_05[t,]=quantile(ratio_S_P_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	}

#------------------
# Ratio Juvénile
#------------------
juv_tot_V_m2014_12_05=read.coda(str_c(m2014_12_05,"simulation/juv_tot_VCODAchain1.txt"),str_c(m2014_12_05,"simulation/juv_tot_VCODAindex.txt"))
juv_tot_L_m2014_12_05=read.coda(str_c(m2014_12_05,"simulation/juv_tot_LCODAchain1.txt"),str_c(m2014_12_05,"simulation/juv_tot_LCODAindex.txt"))
juv_tot_P_m2014_12_05=read.coda(str_c(m2014_12_05,"simulation/juv_tot_PCODAchain1.txt"),str_c(m2014_12_05,"simulation/juv_tot_PCODAindex.txt"))

ratio_juv_tot_V_m2014_12_05=array(0,c(5000,T))
ratio_juv_tot_L_m2014_12_05=array(0,c(5000,T))
ratio_juv_tot_P_m2014_12_05=array(0,c(5000,T))

for (t in 7:15){			
	for(i in 1:5000){
		ratio_juv_tot_V_m2014_12_05[i,t] = juv_tot_V_m2014_12_05[i,t-6] / (juv_tot_V_m2014_12_05[i,t-6] + juv_tot_L_m2014_12_05[i,t-6])
		ratio_juv_tot_L_m2014_12_05[i,t] = 1 - ratio_juv_tot_V_m2014_12_05[i,t]
	}
}
for (t in 16:T){
	for(i in 1:5000){
		ratio_juv_tot_V_m2014_12_05[i,t] = juv_tot_V_m2014_12_05[i,t-6] / (juv_tot_V_m2014_12_05[i,t-6] + juv_tot_L_m2014_12_05[i,t-6] + juv_tot_P_m2014_12_05[i,t-15])
		ratio_juv_tot_L_m2014_12_05[i,t] = juv_tot_L_m2014_12_05[i,t-6] / (juv_tot_V_m2014_12_05[i,t-6] + juv_tot_L_m2014_12_05[i,t-6] + juv_tot_P_m2014_12_05[i,t-15])
		ratio_juv_tot_P_m2014_12_05[i,t] = 1 - ratio_juv_tot_V_m2014_12_05[i,t] - ratio_juv_tot_L_m2014_12_05[i,t]
	}
}

ratio_juv_tot_V_q_m2014_12_05=array(0,c(T,5))
ratio_juv_tot_L_q_m2014_12_05=array(0,c(T,5))
ratio_juv_tot_P_q_m2014_12_05=array(0,c(T,5))

for (t in 7:T){
	
	ratio_juv_tot_V_q_m2014_12_05[t,]=quantile(ratio_juv_tot_V_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	ratio_juv_tot_L_q_m2014_12_05[t,]=quantile(ratio_juv_tot_L_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}
for (t in 16:T){
	ratio_juv_tot_P_q_m2014_12_05[t,]=quantile(ratio_juv_tot_P_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}


surf=c(rep(c(916866,250441,0),11),rep(c(916866,250441,301101),12),rep(c(916866,250441,383049),6),rep(c(1202540,250441,383049),31))
S_juv_JP<-matrix(surf,nrow=3)	


#--------------------------------
# Diff ratio géniteurs/juvéniles
#--------------------------------
diff_ratio_V_m2014_12_05=ratio_S_V_m2014_12_05-ratio_juv_tot_V_m2014_12_05
diff_ratio_L_m2014_12_05=ratio_S_L_m2014_12_05-ratio_juv_tot_L_m2014_12_05
diff_ratio_P_m2014_12_05=ratio_S_P_m2014_12_05-ratio_juv_tot_P_m2014_12_05

diff_ratio_V_q_m2014_12_05=array(0,c(T,5))
diff_ratio_L_q_m2014_12_05=array(0,c(T,5))
diff_ratio_P_q_m2014_12_05=array(0,c(T,5))


for (t in 1:T){
	diff_ratio_V_q_m2014_12_05[t,]=quantile(diff_ratio_V_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	diff_ratio_L_q_m2014_12_05[t,]=quantile(diff_ratio_L_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	diff_ratio_P_q_m2014_12_05[t,]=quantile(diff_ratio_P_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}

####################
# CHAP:Relation DD
####################
#===========================
#courbes densité-dépendant
#===========================
S_vichy_m2014_12_05=read.coda(str_c(m2014_12_05,"S_vichyCODAchain1.txt"),str_c(m2014_12_05,"S_vichyCODAindex.txt"),5001,10000)
S_langeac_m2014_12_05=read.coda(str_c(m2014_12_05,"S_langeacCODAchain1.txt"),str_c(m2014_12_05,"S_langeacCODAindex.txt"),5001,10000)
a_m2014_12_05=read.coda(str_c(m2014_12_05,"aCODAchain1.txt"),str_c(m2014_12_05,"aCODAindex.txt"),5001,10000)

a_juv_m2014_12_05=read.coda(str_c(m2014_12_05,"a_juvCODAchain1.txt"),str_c(m2014_12_05,"a_juvCODAindex.txt"),5001,10000)

Rmax_m2014_12_05=read.coda(str_c(m2014_12_05,"RmaxCODAchain1.txt"),str_c(m2014_12_05,"RmaxCODAindex.txt"),5001,10000)

nu_wild_m2014_12_05=read.coda(str_c(m2014_12_05,"nu_wildCODAchain1.txt"),str_c(m2014_12_05,"nu_wildCODAindex.txt"),5001,10000)

I_juv_V=c(1,2,4,6,7,8,10,11,18,21,22,23,24,25,26,27,28,29,30,32,33,34,35,36,37,38,39)
I_juv_L=c(6,17,21,22,23,24,26,27,28,29,30,31,32)#Ajout de l'année 30 suite à ajout des données de déversement 2004
I_juv_P=c(1,9,10,18,19,20,21,22,23,24,25,27,28,29,30,31,32,33)#Ajout de l'année 30 suite à ajout des données de déversement 2004

stocked_juv_V=c( 
		30000,20000,0,80000,0,
		32000,20000,124950,0,20000,
		4000,0,0,0,0,
		0,0,17150,0,0,
		212500,410600,522600,611000,146500,
		597700,651793,92114,330480,351126,#MAJ déversement 2004
		0,210000,152560,417052,699594,
		660841,616289,611031,653043)


stocked_juv_L=c( 
		0,0,0,0,0,
		32000,0,0,0,0,
		0,0,0,0,0,
		0,58410,0,0,0,
		327000,311000,309000,103000,0,
		213000,236170,83144,174429,178214,#MAJ déversement 2004
		85929,96000,0,0,0,
		0,0,0,0)


stocked_juv_P=c( 
		20000,0,0,0,0,
		0,0,0,30000,40000,
		0,0,0,0,0,
		0,0,114350,125000,53600,
		414500,338000,253000,251000,254880,
		0,153610,363421,305126,268762,#MAJ déversement 2004
		146070,294000,52000,0,0,
		0,0,0,0)

Mat=cbind(stocked_juv_V,stocked_juv_L,stocked_juv_P)

stocked_juv_V_d_m2014_12_05=array(0,T)
stocked_juv_L_d_m2014_12_05=array(0,T)
stocked_juv_P_d_m2014_12_05=array(0,T)


for(t in 1:T){
stocked_juv_V_d_m2014_12_05[t]=Mat[t,1]/S_juv_JP[1,t]
}

for(t in 1:T){
	stocked_juv_L_d_m2014_12_05[t]=Mat[t,2]/S_juv_JP[2,t]
}
for(t in 1:T){
stocked_juv_P_d_m2014_12_05[t]=Mat[t,3]/S_juv_JP[3,t]
}

###############
# CHAP:ProbaPassage 
###############
L_mu_p_langeac_m2014_12_05=read.coda(str_c(m2014_12_05,"L_mu_p_langeacCODAchain1.txt"),str_c(m2014_12_05,"L_mu_p_langeacCODAindex.txt"))
L_mu_p_poutes_m2014_12_05=read.coda(str_c(m2014_12_05,"L_mu_p_poutesCODAchain1.txt"),str_c(m2014_12_05,"L_mu_p_poutesCODAindex.txt"))

mu_p_langeac_m2014_12_05=inv.logit(L_mu_p_langeac_m2014_12_05)
mu_p_poutes_m2014_12_05=inv.logit(L_mu_p_poutes_m2014_12_05)

mu_p_langeac_q_m2014_12_05=quantile(mu_p_langeac_m2014_12_05,probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
mu_p_poutes_q_m2014_12_05=quantile(mu_p_poutes_m2014_12_05,probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)

sigma_p_langeac_m2014_12_05=read.coda(str_c(m2014_12_05,"sigma_p_langeacCODAchain1.txt"),str_c(m2014_12_05,"sigma_p_langeacCODAindex.txt"))
sigma_p_poutes_m2014_12_05=read.coda(str_c(m2014_12_05,"sigma_p_poutesCODAchain1.txt"),str_c(m2014_12_05,"sigma_p_poutesCODAindex.txt"))

sigma_p_langeac_q_m2014_12_05=quantile(sigma_p_langeac_m2014_12_05,probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
sigma_p_poutes_q_m2014_12_05=quantile(sigma_p_poutes_m2014_12_05,probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)

p_langeac_m2014_12_05=read.coda(str_c(m2014_12_05,"p_langeacCODAchain1.txt"),str_c(m2014_12_05,"p_langeacCODAindex.txt"))
p_poutes_m2014_12_05=read.coda(str_c(m2014_12_05,"p_poutesCODAchain1.txt"),str_c(m2014_12_05,"p_poutesCODAindex.txt"))

p_langeac_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))
p_poutes_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

for (i in 1:T){
	p_langeac_q_m2014_12_05[i,]=quantile(p_langeac_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}


for (i in 12:T){
	p_poutes_q_m2014_12_05[i,]=quantile(p_poutes_m2014_12_05[,i-11],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
}

save.image(file = "C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/2014.12.05.RData")#file="C:/Users/LOGRAMI/workspace/ModeleDynamiquePop/data/wspace.RData")
@

<< init, echo=FALSE, eval=FALSE,results=hide >>=
	
	load("2014.10.13.RData")
	
library(lattice)
library(coda)
library(boot)
require(stringr)

T=39

@


  %--------------------------------------------------
  \subsection{retour à Vichy}
  %--------------------------------------------------
  % TotalReturns
  
<< Init_TotalReturns, echo=FALSE, eval=TRUE,results=hide >>=  
###################
# CHAP: SPAWNERS 
###################

	#===============================================================================================================
	# SEC : Adults returns at Vichy and 20 years projection without stocking (with and without 20 years projection)
	#===============================================================================================================

	CV_V_m2014_12_05=rep(0,42)
	for (t in 1:42){
		CV_V_m2014_12_05[t]=sd(N_vichy_real_m2014_12_05[,t])/mean(N_vichy_real_m2014_12_05[,t])
	}
	
	min(CV_V_m2014_12_05[3:22])
	max(CV_V_m2014_12_05[3:22])
	median(CV_V_m2014_12_05[3:22])
	mean(CV_V_m2014_12_05[3:22])
	par(mar=c(4,7.1,2,4),col.lab="grey25",col.axis="grey55",col.main="grey25")
		
	
		#----------------------
		# figure_m2014_12_05 : retours sans projections
		#----------------------
		
		png(file=str_c(imgwd_2014_12_05,"Spawners_ReturnsVichy_m2014_12_05.png"),width=800, height=800, units = "px",type="cairo")
		par(mar=c(4,7.1,2,4),col.lab="grey25",col.axis="grey55",col.main="grey25")
		
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,9000),ylab="Returns Vichy",main="Adults returns at Vichy",cex.lab=1.5)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,1000,2000,3000,4000,5000,6000,7000,8000,9000),labels=c(0,1000,2000,3000,4000,5000,6000,7000,8000,9000),cex.axis = 1.2,las = 1,lwd=2,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 1.2,las = 1,lwd=2,col = "grey55")
		
		for(i in 3:22){
			#whiskers
			#95%
			segments(i-0.15,N_vichy_real_q_m2014_12_05[i,5],i+0.15,N_vichy_real_q_m2014_12_05[i,5])
			segments(i,N_vichy_real_q_m2014_12_05[i,4],i,N_vichy_real_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,N_vichy_real_q_m2014_12_05[i,1],i+0.15,N_vichy_real_q_m2014_12_05[i,1])
			segments(i,N_vichy_real_q_m2014_12_05[i,2],i,N_vichy_real_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(N_vichy_real_q_m2014_12_05[i,2],N_vichy_real_q_m2014_12_05[i,2],N_vichy_real_q_m2014_12_05[i,4],N_vichy_real_q_m2014_12_05[i,4]),col="grey85")
			#median
			segments(i-0.3,N_vichy_real_q_m2014_12_05[i,3],i+0.3,N_vichy_real_q_m2014_12_05[i,3])
		}
		
		data_vichy=c(
				NA,NA,NA,NA,NA,
				NA,NA,NA,NA,NA,
				NA,NA,NA,NA,NA,
				NA,NA,NA,NA,NA,
				NA,NA,393,267,515,
				380,400,541,1238,657,
				510,950,572,421,491,
				227,755,861,819)
		
		points(x=seq(23,T,1),data_vichy[23:T],pch=16)
		
		par(new=TRUE)
		
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),ylab="",xlab="",ylim=c(0,1))
		
		axis(4,at = c(0,0.2,0.4,0.6,0.8,1),
				labels=c(0,0.2,0.4,0.6,0.8,1),
				cex.axis = 1.2,las = 1,lwd=2,col = "grey55")
		
		points(seq(3,22,1),CV_V_m2014_12_05[3:22],pch=16,col="darkorange")
		segments(seq(3,21,1),CV_V_m2014_12_05[3:21],seq(4,22,1),CV_V_m2014_12_05[4:22],lty=2,pch=16,col="darkorange")
		
		par(srt=-90) 
		mtext(side=4,"CV",line=2.5,cex = 1.5)
		
		dev.off()	
@

         \begin{figure}[ht]
          \begin{center} 
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Spawners_ReturnsVichy_m2014_12_05.png}
                  \caption[distribution a posteriori des 
  retours d'adultes à Vichy.]{distribution a posteriori des 
  retours d'adultes à Vichy. Les
  boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Les cercles pleins indiquent les années pour
  lesquelles la station de comptage à Vichy est opérationnelle et fournit le
  nombre de retours d'adultes. Les cercles orange représentent les
  coefficients de variation (CVs) associés aux estimations de retour d'adultes.}
                  \label{ReturnsVichy_m2014_12_05} 
                  \end{center}
        \end{figure}


\FloatBarrier 

 %--------------------------------------------------
  \subsection{Géniteurs potentiels et ratio}
  %--------------------------------------------------
  % SpawnersRedds_GeniteursPotentiels

<< Init_GeniteursPotentiels, echo=FALSE, eval=TRUE,results=hide >>=
	#=============================================================
	# SEC : Figure : SpawnersRedds_GeniteursPotentiels all years
	#=============================================================
		
		#---------------
		# Figure_m2014_12_05 : Spawners_ratio
		#--------------
		
		png(file=str_c(imgwd_2014_12_05,"SpawnersRedds_GeniteursPotentiels_m2014_12_05.png"),width=800, height=800, units = "px",type="cairo")
		
		par(mfrow=c(3,2),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
		#........
		# Vichy
		#........
		
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,6500),ylab=expression(italic(S["t,1"])),main="Vichy-Langeac",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,1000,2000,3000,4000,5000,6000),labels=c(0,1000,2000,3000,4000,5000,6000),cex.axis = 1.4,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,6500,labels=expression(italic("a.")),col = "grey55")
		
		for(i in 3:T){
			#whiskers
			#95%
			segments(i-0.15,S_vichy_q_m2014_12_05[i,5],i+0.15,S_vichy_q_m2014_12_05[i,5])
			segments(i,S_vichy_q_m2014_12_05[i,4],i,S_vichy_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,S_vichy_q_m2014_12_05[i,1],i+0.15,S_vichy_q_m2014_12_05[i,1])
			segments(i,S_vichy_q_m2014_12_05[i,2],i,S_vichy_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(S_vichy_q_m2014_12_05[i,2],S_vichy_q_m2014_12_05[i,2],S_vichy_q_m2014_12_05[i,4],S_vichy_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,S_vichy_q_m2014_12_05[i,3],i+0.3,S_vichy_q_m2014_12_05[i,3])
		}
		
		
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio Spawners")) ,main="Vichy-Langeac",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 1.4,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("d.")),col = "grey55")
		
		for(i in 3:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_S_V_q_m2014_12_05[i,5],i+0.15,ratio_S_V_q_m2014_12_05[i,5])
			segments(i,ratio_S_V_q_m2014_12_05[i,4],i,ratio_S_V_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_S_V_q_m2014_12_05[i,1],i+0.15,ratio_S_V_q_m2014_12_05[i,1])
			segments(i,ratio_S_V_q_m2014_12_05[i,2],i,ratio_S_V_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_S_V_q_m2014_12_05[i,2],ratio_S_V_q_m2014_12_05[i,2],ratio_S_V_q_m2014_12_05[i,4],ratio_S_V_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,ratio_S_V_q_m2014_12_05[i,3],i+0.3,ratio_S_V_q_m2014_12_05[i,3])
		}
		
		
		
		segments(0,S_juv_JP[1,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),11.5,S_juv_JP[1,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),col="grey35",lty=2,lwd=2)
		segments(11.5,S_juv_JP[1,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[1,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[1,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[1,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[1,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[1,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		
		abline(v=11.5,lty=3)
		
		#..........
		# Langeac
		#..........
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,1200),ylab=expression(italic(S["t,2"])),main="Langeac-Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,300,600,900,1200),labels=c(0,300,600,900,1200),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		
		text(T,1200,labels=expression(italic("b.")),col = "grey55")
		
		
		
		for(i in 3:T){
			#whiskers
			#95%
			segments(i-0.15,S_langeac_q_m2014_12_05[i,5],i+0.15,S_langeac_q_m2014_12_05[i,5])
			segments(i,S_langeac_q_m2014_12_05[i,4],i,S_langeac_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,S_langeac_q_m2014_12_05[i,1],i+0.15,S_langeac_q_m2014_12_05[i,1])
			segments(i,S_langeac_q_m2014_12_05[i,2],i,S_langeac_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(S_langeac_q_m2014_12_05[i,2],S_langeac_q_m2014_12_05[i,2],S_langeac_q_m2014_12_05[i,4],S_langeac_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,S_langeac_q_m2014_12_05[i,3],i+0.3,S_langeac_q_m2014_12_05[i,3])
		}
		
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio Spawners")) ,main="Langeac-Poutes")
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis =2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("e.")),col = "grey55")
		
		for(i in 3:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_S_L_q_m2014_12_05[i,5],i+0.15,ratio_S_L_q_m2014_12_05[i,5])
			segments(i,ratio_S_L_q_m2014_12_05[i,4],i,ratio_S_L_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_S_L_q_m2014_12_05[i,1],i+0.15,ratio_S_L_q_m2014_12_05[i,1])
			segments(i,ratio_S_L_q_m2014_12_05[i,2],i,ratio_S_L_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_S_L_q_m2014_12_05[i,2],ratio_S_L_q_m2014_12_05[i,2],ratio_S_L_q_m2014_12_05[i,4],ratio_S_L_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,ratio_S_L_q_m2014_12_05[i,3],i+0.3,ratio_S_L_q_m2014_12_05[i,3])
		}
		
		segments(0,S_juv_JP[2,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),11.5,S_juv_JP[2,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),col="grey35",lty=2,lwd=2)
		segments(11.5,S_juv_JP[2,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[2,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[2,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[2,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[2,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[2,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		abline(v=11.5,lty=3)
		
		#..........
		# Poutes
		#..........
		
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,200),ylab=expression(italic(S["t,3"])),main="Upstream Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,100,200),labels=c(0,100,200),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		points(x=seq(12,T,1),y=S_poutes_counter[12:T],pch=16,col="darkolivegreen3") 
		abline(v=11.5,lty=2)
		text(6,100,paste( "Amont Poutes\n inaccessible"),col = "grey55")
		
		
		text(T,200,labels=expression(italic("c.")),col = "grey55")
		
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio Spawners")) ,main="upstream Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis =2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis =2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("f.")),col = "grey55")
		text(6,0.55,paste( "Amont Poutes\n inaccessible"),col = "grey55")
		
		
		for(i in 12:22){
			#whiskers
			#95%
			segments(i-0.15,ratio_S_P_q_m2014_12_05[i,5],i+0.15,ratio_S_P_q_m2014_12_05[i,5])
			segments(i,ratio_S_P_q_m2014_12_05[i,4],i,ratio_S_P_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_S_P_q_m2014_12_05[i,1],i+0.15,ratio_S_P_q_m2014_12_05[i,1])
			segments(i,ratio_S_P_q_m2014_12_05[i,2],i,ratio_S_P_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_S_P_q_m2014_12_05[i,2],ratio_S_P_q_m2014_12_05[i,2],ratio_S_P_q_m2014_12_05[i,4],ratio_S_P_q_m2014_12_05[i,4]),col="darkolivegreen3")
			#median
			segments(i-0.3,ratio_S_P_q_m2014_12_05[i,3],i+0.3,ratio_S_P_q_m2014_12_05[i,3])
		}
		
		x=seq(23,T,1)
		points(x,ratio_S_P_q_m2014_12_05[23:T,3],pch=16,col="darkolivegreen3")
		
		segments(11.5,S_juv_JP[3,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[3,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[3,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[3,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[3,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[3,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		abline(v=11.5,lty=3)
		
		dev.off()

@
  
        \begin{figure}[ht]
          \begin{center} 
                  \includegraphics{\Sexpr{imgwd_2014_12_05}SpawnersRedds_GeniteursPotentiels_m2014_12_05.png}
                  \caption[distribution a posteriori
  des abondances annuelles absolues et relatives de géniteurs
  potentiels]{distribution a posteriori
  des abondances annuelles absolues et relatives de géniteurs
  potentiels dans chaque zone du bassin de l'Allier: Vichy-Langeac (a et d),
  Langeac-Poutès (b et e), Amont Poutès (c et f). Les boxplots indiquent les quantiles
  à 2.5$^{th}$, 25$^{th}$, 75$^{th}$ et 97.5$^{th}$. Les lignes pointillées
  horizontales pour d, e et f indiquent la disponibilité relative de l'habitat
  potnetiel pour les juvéniles. On notera que pour la zone à l'amont de Poutès
  il n'y a pas d'estimation des abondances absolues car le nombre exact de
  géniteurs est toujours connu (c) et l'abondance relative est connue lorsque
  les comptages à Vichy sont disponibles.}
                  \label{GenitPot_m2014_12_05}
    \end{center} 
  \end{figure}
  
\FloatBarrier 


 %--------------------------------------------------
  \subsection{ratio géniteurs potentiels:frayères}
  %--------------------------------------------------
  % Redds_Kappa
<< Init_Kappa, echo=FALSE, eval=TRUE,results=hide >>=
    #=============
	# SEC: Kappa
	#=============
		#------------------------------
		# Figure_m2014.12.05 : zone_effect /kappa
		#------------------------------
		#Figure du modèle guillaume déjà sortie on l'intégrera directement
		png(file=str_c(imgwd_2014_12_05,"Redds_kappa_m2014_12_05.png"),width=800, height=800, units = "px",type="cairo")
		
		par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
		
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,3),ylab=expression(italic( kappa["t,1"])),main="Vichy-Langeac",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,1,2,3),labels=c(0,1,2,3),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(T-T+1,T-T+1+5,T-T+1+15,T-T+1+25,T-T+1+35,T),
				labels=c(1975,1980,1990,2000,2010,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,3,labels=expression(italic("a.")),col = "grey55")
		
		xx=c(0:(T+1),(T+1):0)
		
		q_2_5=rep(mu_zone_q_m2014_12_05[1,1],(T+2))
		q_97_5=rep(mu_zone_q_m2014_12_05[1,5],(T+2))
		
		yy=c(q_2_5,rev(q_97_5))
		
		polygon(xx,yy,col="rosybrown1",border="NA")
		
		q_25=rep(mu_zone_q_m2014_12_05[1,2],(T+2))
		q_75=rep(mu_zone_q_m2014_12_05[1,4],(T+2))
		
		yy=c(q_25,rev(q_75))
		
		polygon(xx,yy,col="rosybrown3",border="NA")
		
		points(x=seq(0,(T+1),1),y=rep(mu_zone_q_m2014_12_05[1,3],(T+2)),type="l",col="white")
		
		for(i in 1:T){
			#whiskers
			#95%
			segments(i-0.15,zone_effect_V_q_m2014_12_05[i,5],i+0.15,zone_effect_V_q_m2014_12_05[i,5])
			segments(i,zone_effect_V_q_m2014_12_05[i,4],i,zone_effect_V_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,zone_effect_V_q_m2014_12_05[i,1],i+0.15,zone_effect_V_q_m2014_12_05[i,1])
			segments(i,zone_effect_V_q_m2014_12_05[i,2],i,zone_effect_V_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_V_q_m2014_12_05[i,2],zone_effect_V_q_m2014_12_05[i,2],zone_effect_V_q_m2014_12_05[i,4],zone_effect_V_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,zone_effect_V_q_m2014_12_05[i,3],i+0.3,zone_effect_V_q_m2014_12_05[i,3])
		}
		
		#####################
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,(T+0.5)),xlab="Years",ylim=c(0,4),ylab=expression(italic(kappa["t,2"])),main="Langeac-Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,1,2,3),labels=c(0,1,2,3),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(T-T+1,T-T+1+5,T-T+1+15,T-T+1+25,T-T+1+35,T),
				labels=c(1975,1980,1990,2000,2010,2013),
				cex.axis =2,las = 1,col = "grey55")
		
		text(T,4,labels=expression(italic("b.")),col = "grey55")
		
		xx=c(0:(T+1),(T+1):0)
		
		q_2_5=rep(mu_zone_q_m2014_12_05[1,1],T+2)
		q_97_5=rep(mu_zone_q_m2014_12_05[1,5],T+2)
		
		yy=c(q_2_5,rev(q_97_5))
		
		polygon(xx,yy,col="rosybrown1",border="NA")
		
		
		q_25=rep(mu_zone_q_m2014_12_05[1,2],T+2)
		q_75=rep(mu_zone_q_m2014_12_05[1,4],T+2)
		
		yy=c(q_25,rev(q_75))
		
		polygon(xx,yy,col="rosybrown3",border="NA")
		
		points(x=seq(0,T+1,1),y=rep(mu_zone_q_m2014_12_05[1,3],T+2),type="l",col="white")
		
		for(i in 1:T){
			#whiskers
			#95%
			segments(i-0.15,zone_effect_L_q_m2014_12_05[i,5],i+0.15,zone_effect_L_q_m2014_12_05[i,5])
			segments(i,zone_effect_L_q_m2014_12_05[i,4],i,zone_effect_L_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,zone_effect_L_q_m2014_12_05[i,1],i+0.15,zone_effect_L_q_m2014_12_05[i,1])
			segments(i,zone_effect_L_q_m2014_12_05[i,2],i,zone_effect_L_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_L_q_m2014_12_05[i,2],zone_effect_L_q_m2014_12_05[i,2],zone_effect_L_q_m2014_12_05[i,4],zone_effect_L_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,zone_effect_L_q_m2014_12_05[i,3],i+0.3,zone_effect_L_q_m2014_12_05[i,3])
		}
		
		####################
		plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,8),ylab=expression(italic(kappa["t,3"])),main="Upstream Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,1,2,3,4,5,6),labels=c(0,1,2,3,4,5,6),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(T-T+1,T-T+1+5,T-T+1+15,T-T+1+25,T-T+1+35,T),
				labels=c(1975,1980,1990,2000,2010,2013),
				cex.axis =2,las = 1,col = "grey55")
		
		text(T,6,labels=expression(italic("c.")),col = "grey55")
		
		
		temp=c(11.5,12:(T+1))
		temp1=c(rev(12:(T+1)),11.5)
		
		xx=c(temp,temp1)
		
		#q_2_5=rep(mu_zone_q[2,1],T+1-12+2)
		#q_97_5=rep(mu_zone_q[2,5],T+1-12+2)
		
		#yy=c(q_2_5,rev(q_97_5))
		
		#polygon(xx,yy,col="yellowgreen",border="NA")
		
		
		#q_25=rep(mu_zone_q[2,2],T+1-12+2)
		#q_75=rep(mu_zone_q[2,4],T+1-12+2)
		
		#yy=c(q_25,rev(q_75))
		
		#polygon(xx,yy,col="palegreen4",border="NA")
		
		#points(seq(11.5,T+1,0.5),rep(mu_zone_q[2,3],(T+1-11)*2),type="l",col="white")
		
		for(i in 12:T){
			#whiskers
			#95%
			segments(i-0.15,zone_effect_P_q_m2014_12_05[i,5],i+0.15,zone_effect_P_q_m2014_12_05[i,5])
			segments(i,zone_effect_P_q_m2014_12_05[i,4],i,zone_effect_P_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,zone_effect_P_q_m2014_12_05[i,1],i+0.15,zone_effect_P_q_m2014_12_05[i,1])
			segments(i,zone_effect_P_q_m2014_12_05[i,2],i,zone_effect_P_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(zone_effect_P_q_m2014_12_05[i,2],zone_effect_P_q_m2014_12_05[i,2],zone_effect_P_q_m2014_12_05[i,4],zone_effect_P_q_m2014_12_05[i,4]),col="darkolivegreen3")
			#median
			segments(i-0.3,zone_effect_P_q_m2014_12_05[i,3],i+0.3,zone_effect_P_q_m2014_12_05[i,3])
		}
		
		abline(v=11.5,lty=2)
		text(4,3,paste( "upstream Poutes\n inaccessible"))
		
		dev.off()
		
@  
 
       \begin{figure}[ht]
          \begin{center} 
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Redds_kappa_m2014_12_05.png}
                  \caption[distribution a posteriori du
  ratio géniteurs potentiels:frayères pour chaque zone du bassin]{distribution a posteriori du
  ratio géniteurs potentiels:frayères pour chaque zone du bassin de
  l'Allier: a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les
  boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Les bandes colorées en arrière-plan
  représentent la médiane et les quantiles à 2.5$^{th}$, 25$^{th}$, médiane,
  75$^{th}$ et 97.5$^{th}$ des hyper-paramètres \mu$^{K_{down}}$ (a et b)
  et \mu$^{K_{up}}$ (c).}
                  \label{Redds_kappa_m2014_12_05}
  \end{center} 
  \end{figure}
  
\FloatBarrier 

 %--------------------------------------------------
  \subsection{Densité de juvéniles - échelle macroscopique}
  %--------------------------------------------------
    %#############################
    % Dtot Vichy-Langeac-Poutès
    %############################

<< Init_DensiteTot, echo=FALSE, eval=TRUE,results=hide >>=    

	
	#===============================
	# Figure_m2014_12_05 : Juvénile production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"juvenile_production_totale_VLP_m2014_12_05.png"),width=800,height=800)

par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
### Vichy - Langeac ###
#plot(1,1,type="n",axes=FALSE,xlab="",ylab="")

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^tot*" (0+."*m^-2*")")),main="Vichy-Langeac (total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonn?es
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis=2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),cex.axis=2,
		las = 1,col = "grey55")

x=c(1,0,1,0,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,dmoy_tot_V_q_m2014_12_05[i+1,5],i+0.15,dmoy_tot_V_q_m2014_12_05[i+1,5])
	segments(i,dmoy_tot_V_q_m2014_12_05[i+1,4],i,dmoy_tot_V_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,dmoy_tot_V_q_m2014_12_05[i+1,1],i+0.15,dmoy_tot_V_q_m2014_12_05[i+1,1])
	segments(i,dmoy_tot_V_q_m2014_12_05[i+1,2],i,dmoy_tot_V_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_tot_V_q_m2014_12_05[i+1,2],dmoy_tot_V_q_m2014_12_05[i+1,2],dmoy_tot_V_q_m2014_12_05[i+1,4],dmoy_tot_V_q_m2014_12_05[i+1,4]),col="coral3")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_tot_V_q_m2014_12_05[i+1,2],dmoy_tot_V_q_m2014_12_05[i+1,2],dmoy_tot_V_q_m2014_12_05[i+1,4],dmoy_tot_V_q_m2014_12_05[i+1,4]),col="bisque")
	}
	#median
	segments(i-0.3,dmoy_tot_V_q_m2014_12_05[i+1,3],i+0.3,dmoy_tot_V_q_m2014_12_05[i+1,3])
}

#text(T-1+0.5,0.6,labels=expression(italic("a.")),col = "grey55")
text(T,0.6,labels=expression(italic("a.")),col = "grey55",cex=2)

### Langeac - Poutes ###

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^tot*" (0+."*m^-2*")")),main="Langeac-Poutes (total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonn?es
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0)


for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,dmoy_tot_L_q_m2014_12_05[i+1,5],i+0.15,dmoy_tot_L_q_m2014_12_05[i+1,5])
	segments(i,dmoy_tot_L_q_m2014_12_05[i+1,4],i,dmoy_tot_L_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,dmoy_tot_L_q_m2014_12_05[i+1,1],i+0.15,dmoy_tot_L_q_m2014_12_05[i+1,1])
	segments(i,dmoy_tot_L_q_m2014_12_05[i+1,2],i,dmoy_tot_L_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_tot_L_q_m2014_12_05[i+1,2],dmoy_tot_L_q_m2014_12_05[i+1,2],dmoy_tot_L_q_m2014_12_05[i+1,4],dmoy_tot_L_q_m2014_12_05[i+1,4]),col="darkolivegreen4")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_tot_L_q_m2014_12_05[i+1,2],dmoy_tot_L_q_m2014_12_05[i+1,2],dmoy_tot_L_q_m2014_12_05[i+1,4],dmoy_tot_L_q_m2014_12_05[i+1,4]),col="olivedrab2")
	}
	#median
	segments(i-0.3,dmoy_tot_L_q_m2014_12_05[i+1,3],i+0.3,dmoy_tot_L_q_m2014_12_05[i+1,3])
}

#text(T-1+0.5,0.6,labels=expression(italic("a.")),col = "grey55")
text(T,0.6,labels=expression(italic("b.")),col = "grey55",cex=2)

### upstream Poutes ###

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^tot*" (0+."*m^-2*")")),main="Upstream Poutes (total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonn?es
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,0,0)

abline(v=10,lty=2)

for(i in 12:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,dmoy_tot_P_q_m2014_12_05[i+1,5],i+0.15,dmoy_tot_P_q_m2014_12_05[i+1,5])
	segments(i,dmoy_tot_P_q_m2014_12_05[i+1,4],i,dmoy_tot_P_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,dmoy_tot_P_q_m2014_12_05[i+1,1],i+0.15,dmoy_tot_P_q_m2014_12_05[i+1,1])
	segments(i,dmoy_tot_P_q_m2014_12_05[i+1,2],i,dmoy_tot_P_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_tot_P_q_m2014_12_05[i+1,2],dmoy_tot_P_q_m2014_12_05[i+1,2],dmoy_tot_P_q_m2014_12_05[i+1,4],dmoy_tot_P_q_m2014_12_05[i+1,4]),col="darkolivegreen4")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_tot_P_q_m2014_12_05[i+1,2],dmoy_tot_P_q_m2014_12_05[i+1,2],dmoy_tot_P_q_m2014_12_05[i+1,4],dmoy_tot_P_q_m2014_12_05[i+1,4]),col="olivedrab2")
	}
	#median
	segments(i-0.3,dmoy_tot_P_q_m2014_12_05[i+1,3],i+0.3,dmoy_tot_P_q_m2014_12_05[i+1,3])
}

#text(T-1+0.5,0.6,labels=expression(italic("a.")),col = "grey55")
text(T,0.6,labels=expression(italic("c.")),col = "grey55",cex=2)

dev.off()

@

  %................................................................................
    \subsubsection{Densités en juvéniles 0+ total (somme de tous les compartiments)}
    %................................................................................

         \begin{figure}[ht]
          \begin{center} 
                  \includegraphics{\Sexpr{imgwd_2014_12_05}juvenile_production_totale_VLP_m2014_12_05.png}
                  \caption[distribution a posteriori
  des densités de juvéniles 0+ à l'échelle macroscopique]{distribution a posteriori
  des densités de juvéniles 0+ à l'échelle macroscopique D$^{tot}_{t+1,i}$
  dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Le remplissage en couleur foncée des boxplot
  indique les années durant lesquelles il y a eu du repeuplement.}
                  \label{Juvenile_densite_m2014_12_05}
  \end{center} 
  \end{figure}
  
\FloatBarrier 

    %#############################
    % Dtot WILD-JUV-EGG Vichy-Langeac-Poutès
    %############################

<< Init_DensiteTotWildJuvEgg, echo=FALSE, eval=TRUE,results=hide >>=    

	#===============================
	# Figure_m2014_12_05 : Juvénile sauvage production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"juvenile_wild_totale_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
	#----------------
	#Vichy-Langeac
	#----------------
		#..............
		#Wild
		#..............
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^wild*" (0+."*m^-2*")")),main="Vichy-Langeac (wild)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(1,0,1,0,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,dmoy_wild_V_q_m2014_12_05[i+1,5],i+0.15,dmoy_wild_V_q_m2014_12_05[i+1,5])
	segments(i,dmoy_wild_V_q_m2014_12_05[i+1,4],i,dmoy_wild_V_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,dmoy_wild_V_q_m2014_12_05[i+1,1],i+0.15,dmoy_wild_V_q_m2014_12_05[i+1,1])
	segments(i,dmoy_wild_V_q_m2014_12_05[i+1,2],i,dmoy_wild_V_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_wild_V_q_m2014_12_05[i+1,2],dmoy_wild_V_q_m2014_12_05[i+1,2],dmoy_wild_V_q_m2014_12_05[i+1,4],dmoy_wild_V_q_m2014_12_05[i+1,4]),col="coral3")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_wild_V_q_m2014_12_05[i+1,2],dmoy_wild_V_q_m2014_12_05[i+1,2],dmoy_wild_V_q_m2014_12_05[i+1,4],dmoy_wild_V_q_m2014_12_05[i+1,4]),col="bisque")
	}
	#median
	segments(i-0.3,dmoy_wild_V_q_m2014_12_05[i+1,3],i+0.3,dmoy_wild_V_q_m2014_12_05[i+1,3])
}

text(T-1+0.5,0.6,labels=expression(italic("a.")),col = "grey55",cex=2)
	#-------------------
	#Langeac-Poutès
	#-------------------
		#.....................
		#Graph wild density
		#.....................
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^wild*" (0+."*m^-2*")")),main="Langeac-Poutes (wild)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0)

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,dmoy_wild_L_q_m2014_12_05[i+1,5],i+0.15,dmoy_wild_L_q_m2014_12_05[i+1,5])
	segments(i,dmoy_wild_L_q_m2014_12_05[i+1,4],i,dmoy_wild_L_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,dmoy_wild_L_q_m2014_12_05[i+1,1],i+0.15,dmoy_wild_L_q_m2014_12_05[i+1,1])
	segments(i,dmoy_wild_L_q_m2014_12_05[i+1,2],i,dmoy_wild_L_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_wild_L_q_m2014_12_05[i+1,2],dmoy_wild_L_q_m2014_12_05[i+1,2],dmoy_wild_L_q_m2014_12_05[i+1,4],dmoy_wild_L_q_m2014_12_05[i+1,4]),col="darkolivegreen4")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_wild_L_q_m2014_12_05[i+1,2],dmoy_wild_L_q_m2014_12_05[i+1,2],dmoy_wild_L_q_m2014_12_05[i+1,4],dmoy_wild_L_q_m2014_12_05[i+1,4]),col="olivedrab2")
	}
	#median
	segments(i-0.3,dmoy_wild_L_q_m2014_12_05[i+1,3],i+0.3,dmoy_wild_L_q_m2014_12_05[i+1,3])
}

text(T-1+0.5,0.6,labels=expression(italic("b.")),col = "grey55",cex=2)

	#---------------
	#Amont Poutès
	#--------------
		#.....................
		#Graph wild density
		#.....................

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^wild*" (0+."*m^-2*")")),main="Upstream Poutes (wild)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis =2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,0,0)

abline(v=10,lty=2)

for(i in 12:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,dmoy_wild_P_q_m2014_12_05[i+1,5],i+0.15,dmoy_wild_P_q_m2014_12_05[i+1,5])
	segments(i,dmoy_wild_P_q_m2014_12_05[i+1,4],i,dmoy_wild_P_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,dmoy_wild_P_q_m2014_12_05[i+1,1],i+0.15,dmoy_wild_P_q_m2014_12_05[i+1,1])
	segments(i,dmoy_wild_P_q_m2014_12_05[i+1,2],i,dmoy_wild_P_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_wild_P_q_m2014_12_05[i+1,2],dmoy_wild_P_q_m2014_12_05[i+1,2],dmoy_wild_P_q_m2014_12_05[i+1,4],dmoy_wild_P_q_m2014_12_05[i+1,4]),col="darkolivegreen4")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(dmoy_wild_P_q_m2014_12_05[i+1,2],dmoy_wild_P_q_m2014_12_05[i+1,2],dmoy_wild_P_q_m2014_12_05[i+1,4],dmoy_wild_P_q_m2014_12_05[i+1,4]),col="olivedrab2")
	}
	#median
	segments(i-0.3,dmoy_wild_P_q_m2014_12_05[i+1,3],i+0.3,dmoy_wild_P_q_m2014_12_05[i+1,3])
}


text(T-1+0.5,0.6,labels=expression(italic("c.")),col = "grey55",cex=2)

dev.off()


	#===============================
	# Figure_m2014_12_05 : Juvénile élevage production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"juvenile_juv_totale_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")

	#-----------------
	#Vichy-Langeac
	#------------------
		#................
		#JUV
		#.................
x=c(1,3,5,6,7,9,10,17,20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^juv*" (0+."*m^-2*")")),main="Vichy-Langeac (juv stocking)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis =2,las = 1,col = "grey55")

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,dmoy_juv_V_q_m2014_12_05[x[i]+1,5],x[i]+0.15,dmoy_juv_V_q_m2014_12_05[x[i]+1,5])
	segments(x[i],dmoy_juv_V_q_m2014_12_05[x[i]+1,4],x[i],dmoy_juv_V_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,dmoy_juv_V_q_m2014_12_05[x[i]+1,1],x[i]+0.15,dmoy_juv_V_q_m2014_12_05[x[i]+1,1])
	segments(x[i],dmoy_juv_V_q_m2014_12_05[x[i]+1,2],x[i],dmoy_juv_V_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(dmoy_juv_V_q_m2014_12_05[x[i]+1,2],dmoy_juv_V_q_m2014_12_05[x[i]+1,2],dmoy_juv_V_q_m2014_12_05[x[i]+1,4],dmoy_juv_V_q_m2014_12_05[x[i]+1,4]),col="coral3")
	#median
	segments(x[i]-0.3,dmoy_juv_V_q_m2014_12_05[x[i]+1,3],x[i]+0.3,dmoy_juv_V_q_m2014_12_05[x[i]+1,3])
}


text(T-1+0.5,0.6,labels=expression(italic("a.")),col = "grey55",cex=2)

	#----------------
	#Langeac-Poutès
	#----------------
		#......................
		# graph stocking
		#......................
		#juvenile stocking vector

x=c(5,16,20,21,22,23,25,26,27,28,30,31)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^juv*" (0+."*m^-2*")")),main="Langeac-Poutes (juv stocking)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis =2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,dmoy_juv_L_q_m2014_12_05[x[i]+1,5],x[i]+0.15,dmoy_juv_L_q_m2014_12_05[x[i]+1,5])
	segments(x[i],dmoy_juv_L_q_m2014_12_05[x[i]+1,4],x[i],dmoy_juv_L_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,dmoy_juv_L_q_m2014_12_05[x[i]+1,1],x[i]+0.15,dmoy_juv_L_q_m2014_12_05[x[i]+1,1])
	segments(x[i],dmoy_juv_L_q_m2014_12_05[x[i]+1,2],x[i],dmoy_juv_L_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(dmoy_juv_L_q_m2014_12_05[x[i]+1,2],dmoy_juv_L_q_m2014_12_05[x[i]+1,2],dmoy_juv_L_q_m2014_12_05[x[i]+1,4],dmoy_juv_L_q_m2014_12_05[x[i]+1,4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,dmoy_juv_L_q_m2014_12_05[x[i]+1,3],x[i]+0.3,dmoy_juv_L_q_m2014_12_05[x[i]+1,3])
}

text(T-1+0.5,0.6,labels=expression(italic("b.")),col = "grey55",cex=2)

	#-----------------
	#Amont Poutès
	#----------------
		#..............
		#JUV
		#..............
		# graph stocking
		#juvenile stocking vector

x=c(8,9,17,18,19,20,21,22,23,24,26,27,28,30,31,32)


plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^juv*" (0+."*m^-2*")")),main="Upstream-Poutes (juv stocking)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")


abline(v=10,lty=2)

for(i in 3:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,dmoy_juv_P_q_m2014_12_05[x[i]+1,5],x[i]+0.15,dmoy_juv_P_q_m2014_12_05[x[i]+1,5])
	segments(x[i],dmoy_juv_P_q_m2014_12_05[x[i]+1,4],x[i],dmoy_juv_P_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,dmoy_juv_P_q_m2014_12_05[x[i]+1,1],x[i]+0.15,dmoy_juv_P_q_m2014_12_05[x[i]+1,1])
	segments(x[i],dmoy_juv_P_q_m2014_12_05[x[i]+1,2],x[i],dmoy_juv_P_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(dmoy_juv_P_q_m2014_12_05[x[i]+1,2],dmoy_juv_P_q_m2014_12_05[x[i]+1,2],dmoy_juv_P_q_m2014_12_05[x[i]+1,4],dmoy_juv_P_q_m2014_12_05[x[i]+1,4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,dmoy_juv_P_q_m2014_12_05[x[i]+1,3],x[i]+0.3,dmoy_juv_P_q_m2014_12_05[x[i]+1,3])
}

text(T-1+0.5,0.6,labels=expression(italic("c.")),col = "grey55",cex=2)
dev.off()

	
	#===============================
	# Figure_m2014_12_05 : Oeufs production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"juvenile_egg_totale_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(2,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
	#-----------------
	#Vichy-Langeac
	#------------------
		#..........
		#EGG
		#..........
x=c(21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^egg*" (0+."*m^-2*")")),main="Vichy-Langeac (egg stocking)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,dmoy_egg_V_q_m2014_12_05[x[i],5],x[i]+0.15,dmoy_egg_V_q_m2014_12_05[x[i],5])
	segments(x[i],dmoy_egg_V_q_m2014_12_05[x[i],4],x[i],dmoy_egg_V_q_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,dmoy_egg_V_q_m2014_12_05[x[i],1],x[i]+0.15,dmoy_egg_V_q_m2014_12_05[x[i],1])
	segments(x[i],dmoy_egg_V_q_m2014_12_05[x[i],2],x[i],dmoy_egg_V_q_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(dmoy_egg_V_q_m2014_12_05[x[i],2],dmoy_egg_V_q_m2014_12_05[x[i],2],dmoy_egg_V_q_m2014_12_05[x[i],4],dmoy_egg_V_q_m2014_12_05[x[i],4]),col="coral3")
	#median
	segments(x[i]-0.3,dmoy_egg_V_q_m2014_12_05[x[i]+1,3],x[i]+0.3,dmoy_egg_V_q_m2014_12_05[x[i]+1,3])
}


text(T-1+0.5,0.6,labels=expression(italic("a.")),col = "grey55",cex=2)

	#------------------
	#Langeac-Poutès
	#------------------
		#..........
		#EGG
		#..........
		#eggs stocking vector

x=c(23,24,25,26,27,28,29,30,31,32,33)



plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,0.6),ylab=expression(italic(D^egg*" (0+."*m^-2*")")),main="Langeac-Poutes (egg stocking)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6),labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,dmoy_egg_L_q_m2014_12_05[x[i],5],x[i]+0.15,dmoy_egg_L_q_m2014_12_05[x[i],5])
	segments(x[i],dmoy_egg_L_q_m2014_12_05[x[i],4],x[i],dmoy_egg_L_q_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,dmoy_egg_L_q_m2014_12_05[x[i],1],x[i]+0.15,dmoy_egg_L_q_m2014_12_05[x[i],1])
	segments(x[i],dmoy_egg_L_q_m2014_12_05[x[i],2],x[i],dmoy_egg_L_q_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(dmoy_egg_L_q_m2014_12_05[x[i],2],dmoy_egg_L_q_m2014_12_05[x[i],2],dmoy_egg_L_q_m2014_12_05[x[i],4],dmoy_egg_L_q_m2014_12_05[x[i],4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,dmoy_egg_L_q_m2014_12_05[x[i],3],x[i]+0.3,dmoy_egg_L_q_m2014_12_05[x[i],3])
}


text(T-1+0.5,0.5,labels=expression(italic("b.")),col = "grey55",cex=2)

dev.off()

@
    %..................................................
    \subsubsection{Densités en juvéniles sauvages}
    %..................................................

        \begin{figure}[ht]
          \begin{center} 
                  \includegraphics{\Sexpr{imgwd_2014_12_05}juvenile_wild_totale_VLP_m2014_12_05.png}
                  \caption[distribution a posteriori
  des densités de juvéniles sauvages 0+ à l'échelle macroscopique]{
  distribution a posteriori
  des densités de juvéniles sauvages 0+ à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Le remplissage en couleur foncée des boxplot
  indique les années durant lesquelles il y a eu du repeuplement.}
                  \label{Juvenile_wild_densite_m2014_12_05}
 \end{center} 
  \end{figure}
  
\FloatBarrier 

 %....................................................
    \subsubsection{Densités en juvéniles d'élevage}
    %....................................................

        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}juvenile_juv_totale_VLP_m2014_12_05.png}
                  \caption[distribution a posteriori
  des densités de juvéniles d'élevage 0+ à l'échelle macroscopique]{
  distribution a posteriori
  des densités de juvéniles d'élevage 0+ à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Le remplissage en couleur foncée des boxplot
  indique les années durant lesquelles il y a eu du repeuplement.}
                  \label{Juvenile_juv_densite_m2014_12_05}
    \end{center} 
  \end{figure}
  
\FloatBarrier 

    %....................................................
    \subsubsection{Densités en juvéniles issus des incubateurs de terrain}
    %....................................................

       \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}juvenile_egg_totale_VLP_m2014_12_05.png}
                  \caption[distribution a posteriori
  des densités de juvéniles 0+ issus des incubateurs de terrain à l'échelle
  macroscopique]{
  distribution a posteriori
  des densités de juvéniles 0+ issus des incubateurs de terrain à l'échelle
  macroscopique D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Il n'y a jamais eu d'incubateurs en amont de
  Poutès.}
                  \label{Juvenile_egg_densite_m2014_12_05}
    \end{center} 
  \end{figure}
  
\FloatBarrier 
    

<< Init_ResidusWildJuvEgg, echo=FALSE, eval=TRUE,results=hide >>=    

	
	#===============================
	# Figure_m2014_12_05 : Juvénile sauvage production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"Residus_Wild_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
	#----------------
	#Vichy-Langeac
	#----------------
		#..............
		#Wild
		#..............

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals density dependence",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(1,0,1,0,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)


abline(h=0,lty=2)

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_wild_V_q_m2014_12_05[i+1,5],i+0.15,res_wild_V_q_m2014_12_05[i+1,5])
	segments(i,res_wild_V_q_m2014_12_05[i+1,4],i,res_wild_V_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,res_wild_V_q_m2014_12_05[i+1,1],i+0.15,res_wild_V_q_m2014_12_05[i+1,1])
	segments(i,res_wild_V_q_m2014_12_05[i+1,2],i,res_wild_V_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_V_q_m2014_12_05[i+1,2],res_wild_V_q_m2014_12_05[i+1,2],res_wild_V_q_m2014_12_05[i+1,4],res_wild_V_q_m2014_12_05[i+1,4]),col="coral3")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_V_q_m2014_12_05[i+1,2],res_wild_V_q_m2014_12_05[i+1,2],res_wild_V_q_m2014_12_05[i+1,4],res_wild_V_q_m2014_12_05[i+1,4]),col="bisque")
	}
	#median
	segments(i-0.3,res_wild_V_q_m2014_12_05[i+1,3],i+0.3,res_wild_V_q_m2014_12_05[i+1,3])
}


text(T-1+0.5,4,labels=expression(italic("a.")),col = "grey55",cex=2)

	#-------------------
	#Langeac-Poutès
	#-------------------
		#.....................
		#Graph wild density
		#.....................

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals density dependence",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0)


abline(h=0,lty=2)

for(i in 1:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_wild_L_q_m2014_12_05[i+1,5],i+0.15,res_wild_L_q_m2014_12_05[i+1,5])
	segments(i,res_wild_L_q_m2014_12_05[i+1,4],i,res_wild_L_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,res_wild_L_q_m2014_12_05[i+1,1],i+0.15,res_wild_L_q_m2014_12_05[i+1,1])
	segments(i,res_wild_L_q_m2014_12_05[i+1,2],i,res_wild_L_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_L_q_m2014_12_05[i+1,2],res_wild_L_q_m2014_12_05[i+1,2],res_wild_L_q_m2014_12_05[i+1,4],res_wild_L_q_m2014_12_05[i+1,4]),col="darkolivegreen4")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_L_q_m2014_12_05[i+1,2],res_wild_L_q_m2014_12_05[i+1,2],res_wild_L_q_m2014_12_05[i+1,4],res_wild_L_q_m2014_12_05[i+1,4]),col="olivedrab2")
	}
	#median
	segments(i-0.3,res_wild_L_q_m2014_12_05[i+1,3],i+0.3,res_wild_L_q_m2014_12_05[i+1,3])
}

text(T-1+0.5,4,labels=expression(italic("b.")),col = "grey55",cex=2)

	#---------------
	#Amont Poutès
	#--------------
		#.....................
		#Graph wild residus
		#.....................

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals density dependence",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 0.9,las = 1,col = "grey55")

x=c(0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,0,0)


abline(h=0,lty=2)

abline(v=10,lty=2)

for(i in 12:(T-1)){
	#whiskers
	#95%
	segments(i-0.15,res_wild_P_q_m2014_12_05[i+1,5],i+0.15,res_wild_P_q_m2014_12_05[i+1,5])
	segments(i,res_wild_P_q_m2014_12_05[i+1,4],i,res_wild_P_q_m2014_12_05[i+1,5])
	#5%
	segments(i-0.15,res_wild_P_q_m2014_12_05[i+1,1],i+0.15,res_wild_P_q_m2014_12_05[i+1,1])
	segments(i,res_wild_P_q_m2014_12_05[i+1,2],i,res_wild_P_q_m2014_12_05[i+1,1])
	#boxplot
	if (x[i] == 1){
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_P_q_m2014_12_05[i+1,2],res_wild_P_q_m2014_12_05[i+1,2],res_wild_P_q_m2014_12_05[i+1,4],res_wild_P_q_m2014_12_05[i+1,4]),col="darkolivegreen4")
	}
	else{
		polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(res_wild_P_q_m2014_12_05[i+1,2],res_wild_P_q_m2014_12_05[i+1,2],res_wild_P_q_m2014_12_05[i+1,4],res_wild_P_q_m2014_12_05[i+1,4]),col="olivedrab2")
	}
	#median
	segments(i-0.3,res_wild_P_q_m2014_12_05[i+1,3],i+0.3,res_wild_P_q_m2014_12_05[i+1,3])
}

text(T-1+0.5,4,labels=expression(italic("c.")),col = "grey55",cex=2)

dev.off()

	
	#===============================
	# Figure_m2014_12_05 : Juvénile élevage production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"Residus_juv_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
	#-----------------
	#Vichy-Langeac
	#------------------
		#................
		#JUV
		#.................

x=c(1,3,5,6,7,9,10,17,20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals stocking juv",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

abline(h=0,lty=2)

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,res_juv_V_q_m2014_12_05[x[i]+1,5],x[i]+0.15,res_juv_V_q_m2014_12_05[x[i]+1,5])
	segments(x[i],res_juv_V_q_m2014_12_05[x[i]+1,4],x[i],res_juv_V_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,res_juv_V_q_m2014_12_05[x[i]+1,1],x[i]+0.15,res_juv_V_q_m2014_12_05[x[i]+1,1])
	segments(x[i],res_juv_V_q_m2014_12_05[x[i]+1,2],x[i],res_juv_V_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(res_juv_V_q_m2014_12_05[x[i]+1,2],res_juv_V_q_m2014_12_05[x[i]+1,2],res_juv_V_q_m2014_12_05[x[i]+1,4],res_juv_V_q_m2014_12_05[x[i]+1,4]),col="coral3")
	#median
	segments(x[i]-0.3,res_juv_V_q_m2014_12_05[x[i]+1,3],x[i]+0.3,res_juv_V_q_m2014_12_05[x[i]+1,3])
}


text(T-1+0.5,4,labels=expression(italic("a.")),col = "grey55",cex=2)

#----------------
#Langeac-Poutès
#----------------
#......................
# graph stocking
#......................
#juvenile stocking vector
x=c(5,16,20,21,22,23,25,26,27,28,30,31)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals stocking juv",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

abline(h=0,lty=2)

for(i in 1:12){
	#whiskers
	#95%
	segments(x[i]-0.15,res_juv_L_q_m2014_12_05[x[i]+1,5],x[i]+0.15,res_juv_L_q_m2014_12_05[x[i]+1,5])
	segments(x[i],res_juv_L_q_m2014_12_05[x[i]+1,4],x[i],res_juv_L_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,res_juv_L_q_m2014_12_05[x[i]+1,1],x[i]+0.15,res_juv_L_q_m2014_12_05[x[i]+1,1])
	segments(x[i],res_juv_L_q_m2014_12_05[x[i]+1,2],x[i],res_juv_L_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(res_juv_L_q_m2014_12_05[x[i]+1,2],res_juv_L_q_m2014_12_05[x[i]+1,2],res_juv_L_q_m2014_12_05[x[i]+1,4],res_juv_L_q_m2014_12_05[x[i]+1,4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,res_juv_L_q_m2014_12_05[x[i]+1,3],x[i]+0.3,res_juv_L_q_m2014_12_05[x[i]+1,3])
}

text(T-1+0.5,4,labels=expression(italic("b.")),col = "grey55",cex=2)

#-----------------
#Amont Poutès
#----------------
#..............
#JUV
#..............
x=c(17,18,19,20,21,22,23,24,26,27,28,30,31,32)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals stocking juv",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

abline(h=0,lty=2)

abline(v=10,lty=2)

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,res_juv_P_q_m2014_12_05[x[i]+1,5],x[i]+0.15,res_juv_P_q_m2014_12_05[x[i]+1,5])
	segments(x[i],res_juv_P_q_m2014_12_05[x[i]+1,4],x[i],res_juv_P_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,res_juv_P_q_m2014_12_05[x[i]+1,1],x[i]+0.15,res_juv_P_q_m2014_12_05[x[i]+1,1])
	segments(x[i],res_juv_P_q_m2014_12_05[x[i]+1,2],x[i],res_juv_P_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(res_juv_P_q_m2014_12_05[x[i]+1,2],res_juv_P_q_m2014_12_05[x[i]+1,2],res_juv_P_q_m2014_12_05[x[i]+1,4],res_juv_P_q_m2014_12_05[x[i]+1,4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,res_juv_P_q_m2014_12_05[x[i]+1,3],x[i]+0.3,res_juv_P_q_m2014_12_05[x[i]+1,3])
}


text(T-1+0.5,4,labels=expression(italic("c.")),col = "grey55",cex=2)
dev.off()

	#===============================
	# Figure_m2014_12_05 : Oeufs production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"Residus_egg_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(2,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
#-----------------
#Vichy-Langeac
#------------------
#..........
#EGG
#..........

x=c(21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals stocking egg",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 0.9,las = 1,col = "grey55")

abline(h=0,lty=2)

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,res_egg_V_q_m2014_12_05[x[i]+1,5],x[i]+0.15,res_egg_V_q_m2014_12_05[x[i]+1,5])
	segments(x[i],res_egg_V_q_m2014_12_05[x[i]+1,4],x[i],res_egg_V_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,res_egg_V_q_m2014_12_05[x[i]+1,1],x[i]+0.15,res_egg_V_q_m2014_12_05[x[i]+1,1])
	segments(x[i],res_egg_V_q_m2014_12_05[x[i]+1,2],x[i],res_egg_V_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(res_egg_V_q_m2014_12_05[x[i]+1,2],res_egg_V_q_m2014_12_05[x[i]+1,2],res_egg_V_q_m2014_12_05[x[i]+1,4],res_egg_V_q_m2014_12_05[x[i]+1,4]),col="coral3")
	#median
	segments(x[i]-0.3,res_egg_V_q_m2014_12_05[x[i]+1,3],x[i]+0.3,res_egg_V_q_m2014_12_05[x[i]+1,3])
}

text(T-1+0.5,4,labels=expression(italic("a.")),col = "grey55",cex=2)

#------------------
#Langeac-Poutès
#------------------
#..........
#EGG
#..........
x=c(23,24,25,26,27,28,29,30,31,32,33)

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(-4,4),ylab="",main="residuals stocking egg",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(-4,-3,-2,-1,0,1,2,3,4),labels=c(-4,-3,-2,-1,0,1,2,3,4),cex.axis = 0.9,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 0.9,las = 1,col = "grey55")

abline(h=0,lty=2)


for(i in 1:11){
	#whiskers
	#95%
	segments(x[i]-0.15,res_egg_L_q_m2014_12_05[x[i]+1,5],x[i]+0.15,res_egg_L_q_m2014_12_05[x[i]+1,5])
	segments(x[i],res_egg_L_q_m2014_12_05[x[i]+1,4],x[i],res_egg_L_q_m2014_12_05[x[i]+1,5])
	#5%
	segments(x[i]-0.15,res_egg_L_q_m2014_12_05[x[i]+1,1],x[i]+0.15,res_egg_L_q_m2014_12_05[x[i]+1,1])
	segments(x[i],res_egg_L_q_m2014_12_05[x[i]+1,2],x[i],res_egg_L_q_m2014_12_05[x[i]+1,1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(res_egg_L_q_m2014_12_05[x[i]+1,2],res_egg_L_q_m2014_12_05[x[i]+1,2],res_egg_L_q_m2014_12_05[x[i]+1,4],res_egg_L_q_m2014_12_05[x[i]+1,4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,res_egg_L_q_m2014_12_05[x[i]+1,3],x[i]+0.3,res_egg_L_q_m2014_12_05[x[i]+1,3])
}

text(T-1+0.5,4,labels=expression(italic("b.")),col = "grey55")

dev.off()
@

    %--------------------------------------------------
    \subsubsection{Résidus des juvéniles sauvages}
    %--------------------------------------------------

        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Residus_wild_VLP_m2014_12_05.png}
                  \caption[Résidus
  des densités de juvéniles sauvages 0+ à l'échelle macroscopique]{
  Résidus
  des densités de juvéniles sauvages 0+ à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Le remplissage en couleur foncée des boxplot
  indique les années durant lesquelles il y a eu du repeuplement.}
     \end{center}
  \end{figure}
  
\FloatBarrier 

 %--------------------------------------------------
    \subsubsection{Résidus des juvéniles d'élevage}
    %--------------------------------------------------

      \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Residus_juv_VLP_m2014_12_05.png}
                  \caption[Résidus
  des densités de juvéniles 0+ issus des repeuplements à l'échelle
  macroscopique]{
  Résidus
  des densités de juvéniles 0+ issus des repeuplements à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Le remplissage en couleur foncée des boxplot
  indique les années durant lesquelles il y a eu du repeuplement.}
    \end{center}
  \end{figure}
  
\FloatBarrier 
    %--------------------------------------------------
    \subsubsection{Résidus des juvéniles issus des incubateurs}
    %--------------------------------------------------

         \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Residus_egg_VLP_m2014_12_05.png}
                  \caption[Résidus
  des densités de juvéniles 0+ issus des incubateurs terrain à l'échelle
  macroscopique]{
  Résidus
  des densités de juvéniles 0+ issus des incubateurs terrain à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Le remplissage en couleur foncée des boxplot
  indique les années durant lesquelles il y a eu du repeuplement. Il n'y a
  jamais eu d'incubateurs en amont de Poutès.}
    \end{center}
  \end{figure}
  
\FloatBarrier 
    
<< Init_RatioWildJuvEgg, echo=FALSE, eval=TRUE,results=hide >>=    

	
	#===============================
	# Figure_m2014_12_05 : Ratio sauvage / production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"Ratio_Wild_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
#-----------------
#Vichy-Langeac
#-----------------
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Vichy-Langeac (ratio wild/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(1,3,5,6,7,9,10,17,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

ratio_V_wild_m2014_12_05=array(rep(0,T*5000),dim=c(5000,T))

ratio_V_q_wild_m2014_12_05=array(rep(0,T*5),dim=c(T,5))


for(i in 1:(T-1)){
	ratio_V_wild_m2014_12_05[,i]=dmoy_wild_V_m2014_12_05[,i]/dmoy_tot_V_m2014_12_05[,i]
}

for (i in 1:(T-1)){
	ratio_V_q_wild_m2014_12_05[i,]=quantile(ratio_V_wild_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

x=c(1,3,5,6,7,9,10,17,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_V_q_wild_m2014_12_05[x[i],5],x[i]+0.15,ratio_V_q_wild_m2014_12_05[x[i],5])
	segments(x[i],ratio_V_q_wild_m2014_12_05[x[i],4],x[i],ratio_V_q_wild_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_V_q_wild_m2014_12_05[x[i],1],x[i]+0.15,ratio_V_q_wild_m2014_12_05[x[i],1])
	segments(x[i],ratio_V_q_wild_m2014_12_05[x[i],2],x[i],ratio_V_q_wild_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_V_q_wild_m2014_12_05[x[i],2],ratio_V_q_wild_m2014_12_05[x[i],2],ratio_V_q_wild_m2014_12_05[x[i],4],ratio_V_q_wild_m2014_12_05[x[i],4]),col="coral3")
	#median
	segments(x[i]-0.3,ratio_V_q_wild_m2014_12_05[x[i],3],x[i]+0.3,ratio_V_q_wild_m2014_12_05[x[i],3])
}

text(T-1+0.5,1,labels=expression(italic("a.")),col = "grey55",cex=2)

x=c(2,4,8,11,12,13,14,15,16,18,19)

points(x,y=rep(1,length(x)),pch=21,bg="bisque")

#-------------------
#Langeac-Poutès
#------------------
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Langeac-Poutes (ratio wild/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(5,16,20,21,22,23,24,25,26,27,28,29,30,31,32,33)

ratio_L_wild_m2014_12_05=array(0,dim=c(5000,T))

ratio_L_q_wild_m2014_12_05=array(0,dim=c(T,5))

for(i in 1:(T-1)){
	ratio_L_wild_m2014_12_05[,i]=dmoy_wild_L_m2014_12_05[,i]/dmoy_tot_L_m2014_12_05[,i]
}

for (i in 1:(T-1)){
	ratio_L_q_wild_m2014_12_05[i,]=quantile(ratio_L_wild_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_L_q_wild_m2014_12_05[x[i],5],x[i]+0.15,ratio_L_q_wild_m2014_12_05[x[i],5])
	segments(x[i],ratio_L_q_wild_m2014_12_05[x[i],4],x[i],ratio_L_q_wild_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_L_q_wild_m2014_12_05[x[i],1],x[i]+0.15,ratio_L_q_wild_m2014_12_05[x[i],1])
	segments(x[i],ratio_L_q_wild_m2014_12_05[x[i],2],x[i],ratio_L_q_wild_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_L_q_wild_m2014_12_05[x[i],2],ratio_L_q_wild_m2014_12_05[x[i],2],ratio_L_q_wild_m2014_12_05[x[i],4],ratio_L_q_wild_m2014_12_05[x[i],4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,ratio_L_q_wild_m2014_12_05[x[i],3],x[i]+0.3,ratio_L_q_wild_m2014_12_05[x[i],3])
}
x=c(1,2,3,4,6,7,8,9,10,11,12,13,14,15,17,18,19,34,35,36,37,38)

points(x,y=rep(1,length(x)),pch=21,bg="grey90")

text(T-1+0.5,1,labels=expression(italic("b.")),col = "grey55",cex=2)

#--------------------
# Amont Poutès
#--------------------
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Upstream Poutes (ratio wild/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(17,18,19,20,21,22,23,24,26,27,28,30,31,32)

abline(v=10,lty=2)

ratio_P_m2014_12_05=array(rep(0,5000*T),dim=c(5000,T))
ratio_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

mean(ratio_P_q_m2014_12_05[(T-9):T,3])

for(i in 1:length(x)){
	ratio_P_m2014_12_05[,x[i]]=dmoy_wild_P_m2014_12_05[,x[i]-11]/dmoy_tot_P_m2014_12_05[,x[i]-11]
}



for (i in 2:(T-1)){
	ratio_P_q_m2014_12_05[i,]=quantile(ratio_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_P_q_m2014_12_05[x[i],5],x[i]+0.15,ratio_P_q_m2014_12_05[x[i],5])
	segments(x[i],ratio_P_q_m2014_12_05[x[i],4],x[i],ratio_P_q_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_P_q_m2014_12_05[x[i],1],x[i]+0.15,ratio_P_q_m2014_12_05[x[i],1])
	segments(x[i],ratio_P_q_m2014_12_05[x[i],2],x[i],ratio_P_q_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_P_q_m2014_12_05[x[i],2],ratio_P_q_m2014_12_05[x[i],2],ratio_P_q_m2014_12_05[x[i],4],ratio_P_q_m2014_12_05[x[i],4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,ratio_P_q_m2014_12_05[x[i],3],x[i]+0.3,ratio_P_q_m2014_12_05[x[i],3])
}
x=c(12,13,14,15,16,25,29,33,34,35,36,37,38)

points(x,y=rep(1,length(x)),pch=21,bg="olivedrab2")
text(T-1+0.5,1,labels=expression(italic("c.")),col = "grey55",cex=2)

dev.off()

	#===============================
	# Figure_m2014_12_05 : Ration Juvénile élevage / production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"Ratio_juv_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(3,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")

#----------------------
# Vichy-Langeac
#---------------------
#juveniles
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Vichy-Langeac (ratio stocked juv/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")
x=c(1,3,5,6,7,9,10,17,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

ratio_V_juv_m2014_12_05=array(rep(0,T*5000),dim=c(5000,T))

ratio_V_q_juv_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

mean(ratio_V_q_juv_m2014_12_05[(T-9):T,3])


for(i in 1:(T-1)){
	ratio_V_juv_m2014_12_05[,i]=stocking_juv_V_m2014_12_05[,i]/dmoy_tot_V_m2014_12_05[,i]
}

for (i in 1:(T-1)){
	ratio_V_q_juv_m2014_12_05[i,]=quantile(ratio_V_juv_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

x=c(1,3,5,6,7,9,10,17,20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38)

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_V_q_juv_m2014_12_05[x[i],5],x[i]+0.15,ratio_V_q_juv_m2014_12_05[x[i],5])
	segments(x[i],ratio_V_q_juv_m2014_12_05[x[i],4],x[i],ratio_V_q_juv_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_V_q_juv_m2014_12_05[x[i],1],x[i]+0.15,ratio_V_q_juv_m2014_12_05[x[i],1])
	segments(x[i],ratio_V_q_juv_m2014_12_05[x[i],2],x[i],ratio_V_q_juv_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_V_q_juv_m2014_12_05[x[i],2],ratio_V_q_juv_m2014_12_05[x[i],2],ratio_V_q_juv_m2014_12_05[x[i],4],ratio_V_q_juv_m2014_12_05[x[i],4]),col="coral3")
	#median
	segments(x[i]-0.3,ratio_V_q_juv_m2014_12_05[x[i],3],x[i]+0.3,ratio_V_q_juv_m2014_12_05[x[i],3])
}


text(T-1+0.5,1,labels=expression(italic("a.")),col = "grey55",cex=2)

x=c(2,4,8,11,12,13,14,15,16,18,19,30)
points(x,y=rep(0,length(x)),pch=21,bg="bisque")

#-------------------
#Langeac-Poutès
#------------------
#juveniles
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Langeac-Poutes (ratio stocked juv/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(5,16,20,21,22,23,25,26,27,28,30,31)

ratio_L_juv_m2014_12_05=array(0,dim=c(5000,T))

ratio_L_q_juv_m2014_12_05=array(0,dim=c(T,5))

for(t in 1:(T-1)){
	
	ratio_L_juv_m2014_12_05[,t]=stocking_juv_L_m2014_12_05[,t]/dmoy_tot_L_m2014_12_05[,t]
}

for (i in 1:(T-1)){
	ratio_L_q_juv_m2014_12_05[i,]=quantile(ratio_L_juv_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_L_q_juv_m2014_12_05[x[i],5],x[i]+0.15,ratio_L_q_juv_m2014_12_05[x[i],5])
	segments(x[i],ratio_L_q_juv_m2014_12_05[x[i],4],x[i],ratio_L_q_juv_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_L_q_juv_m2014_12_05[x[i],1],x[i]+0.15,ratio_L_q_juv_m2014_12_05[x[i],1])
	segments(x[i],ratio_L_q_juv_m2014_12_05[x[i],2],x[i],ratio_L_q_juv_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_L_q_juv_m2014_12_05[x[i],2],ratio_L_q_juv_m2014_12_05[x[i],2],ratio_L_q_juv_m2014_12_05[x[i],4],ratio_L_q_juv_m2014_12_05[x[i],4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,ratio_L_q_juv_m2014_12_05[x[i],3],x[i]+0.3,ratio_L_q_juv_m2014_12_05[x[i],3])
}

text(T-1+0.5,1,labels=expression(italic("b.")),col = "grey55",cex=2)

x=c(1,2,3,4,6,7,8,9,10,11,12,13,14,15,17,18,19,24,29,32,33,34,35,36,37,38)
points(x,y=rep(0,length(x)),pch=21,bg="olivedrab2")

#--------------------
# Amont Poutès
#--------------------
#juveniles
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Upstream Poutes (ratio stocked juv/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(17,18,19,20,21,22,23,24,26,27,28,30,31,32)
abline(v=10,lty=2)

ratio_P_m2014_12_05=array(rep(0,T*5000),dim=c(5000,T))

ratio_P_q_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

mean(ratio_P_q_m2014_12_05[(T-9):T,3])

for(i in 1:length(x)){
	ratio_P_m2014_12_05[,x[i]]=stocking_juv_P_m2014_12_05[,x[i]-11]/dmoy_tot_P_m2014_12_05[,x[i]-11]
	
	#ratio_P[,i+11]=stocking_juv_P[,i]/dmoy_tot_P[,i]
}

for (i in 1:(T-1)){
	ratio_P_q_m2014_12_05[i,]=quantile(ratio_P_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_P_q_m2014_12_05[x[i],5],x[i]+0.15,ratio_P_q_m2014_12_05[x[i],5])
	segments(x[i],ratio_P_q_m2014_12_05[x[i],4],x[i],ratio_P_q_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_P_q_m2014_12_05[x[i],1],x[i]+0.15,ratio_P_q_m2014_12_05[x[i],1])
	segments(x[i],ratio_P_q_m2014_12_05[x[i],2],x[i],ratio_P_q_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_P_q_m2014_12_05[x[i],2],ratio_P_q_m2014_12_05[x[i],2],ratio_P_q_m2014_12_05[x[i],4],ratio_P_q_m2014_12_05[x[i],4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,ratio_P_q_m2014_12_05[x[i],3],x[i]+0.3,ratio_P_q_m2014_12_05[x[i],3])
}

x=c(12,13,14,15,16,25,29,33,34,35,36,37,38)
points(x,y=rep(0,length(x)),pch=21,bg="olivedrab2")
text(T-1+0.5,1,labels=expression(italic("c.")),col = "grey55",cex=2)

dev.off()

	

	#===============================
	# Figure_m2014_12_05 : Ratio Oeufs / production totale
	#===============================
png(filename=str_c(imgwd_2014_12_05,"Ratio_egg_VLP_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(2,1),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")

#-----------------
#Vichy-Langeac
#-----------------
plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Vichy-Langeac (ratio stocked eggs/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")

x=c(21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

ratio_V_egg_m2014_12_05=array(0,dim=c(5000,T))

ratio_V_q_egg_m2014_12_05=array(rep(0,T*5),dim=c(T,5))

mean(ratio_V_q_egg_m2014_12_05[(T-9):T,3])#0.05320079


for(i in 1:length(x)){
	ratio_V_egg_m2014_12_05[,i+20]=stocking_egg_V_m2014_12_05[,i+9]/dmoy_tot_V_m2014_12_05[,i+20]
}


for (i in 1:(T-1)){
	ratio_V_q_egg_m2014_12_05[i,]=quantile(ratio_V_egg_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

x=c(21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38)

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_V_q_egg_m2014_12_05[x[i],5],x[i]+0.15,ratio_V_q_egg_m2014_12_05[x[i],5])
	segments(x[i],ratio_V_q_egg_m2014_12_05[x[i],4],x[i],ratio_V_q_egg_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_V_q_egg_m2014_12_05[x[i],1],x[i]+0.15,ratio_V_q_egg_m2014_12_05[x[i],1])
	segments(x[i],ratio_V_q_egg_m2014_12_05[x[i],2],x[i],ratio_V_q_egg_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_V_q_egg_m2014_12_05[x[i],2],ratio_V_q_egg_m2014_12_05[x[i],2],ratio_V_q_egg_m2014_12_05[x[i],4],ratio_V_q_egg_m2014_12_05[x[i],4]),col="coral3")
	#median
	segments(x[i]-0.3,ratio_V_q_egg_m2014_12_05[x[i],3],x[i]+0.3,ratio_V_q_egg_m2014_12_05[x[i],3])
}

text(T-1+0.5,1,labels=expression(italic("a.")),col = "grey55",cex=2)

x=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
points(x,y=rep(0,length(x)),pch=21,bg="bisque")

#-------------------
#Langeac-Poutès
#------------------

plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T-1+0.5),xlab="Years",ylim=c(0,1),ylab="ratio",main="Langeac-Poutes (ratio stocked eggs/total)",cex.main=2,cex.lab=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,5,15,25,38),
		labels=c(1976,1980,1990,2000,2013),
		cex.axis = 2,las = 1,col = "grey55")
x=c(23,24,25,26,27,28,29,30,31,32,33)
ratio_L_egg_m2014_12_05=array(0,dim=c(5000,T))

ratio_L_q_egg_m2014_12_05=array(0,dim=c(T,5))

for(i in 1:length(x)){
	ratio_L_egg_m2014_12_05[,i+22]=stocking_egg_L_m2014_12_05[,i+9]/dmoy_tot_L_m2014_12_05[,i+22]
}


for (i in 1:(T-1)){
	ratio_L_q_egg_m2014_12_05[i,]=quantile(ratio_L_egg_m2014_12_05[,i],probs=c(0.05,0.25,0.5,0.75,0.95),names=FALSE)
}

for(i in 1:length(x)){
	#whiskers
	#95%
	segments(x[i]-0.15,ratio_L_q_egg_m2014_12_05[x[i],5],x[i]+0.15,ratio_L_q_egg_m2014_12_05[x[i],5])
	segments(x[i],ratio_L_q_egg_m2014_12_05[x[i],4],x[i],ratio_L_q_egg_m2014_12_05[x[i],5])
	#5%
	segments(x[i]-0.15,ratio_L_q_egg_m2014_12_05[x[i],1],x[i]+0.15,ratio_L_q_egg_m2014_12_05[x[i],1])
	segments(x[i],ratio_L_q_egg_m2014_12_05[x[i],2],x[i],ratio_L_q_egg_m2014_12_05[x[i],1])
	#boxplot
	polygon(c(x[i]-0.3,x[i]+0.3,x[i]+0.3,x[i]-0.3),c(ratio_L_q_egg_m2014_12_05[x[i],2],ratio_L_q_egg_m2014_12_05[x[i],2],ratio_L_q_egg_m2014_12_05[x[i],4],ratio_L_q_egg_m2014_12_05[x[i],4]),col="darkolivegreen4")
	#median
	segments(x[i]-0.3,ratio_L_q_egg_m2014_12_05[x[i],3],x[i]+0.3,ratio_L_q_egg_m2014_12_05[x[i],3])
}
text(T-1+0.5,1,labels=expression(italic("b.")),col = "grey55",cex=2)

x=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,34,35,36,37,38)
points(x,y=rep(0,length(x)),pch=21,bg="olivedrab2")	

dev.off()
@

    %--------------------------------------------------
    \subsubsection{Ratio entre les densités sauvages et les densités totales}
    %--------------------------------------------------

        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Ratio_wild_VLP_m2014_12_05.png}
                  \caption[contribution relative des juvéniles
  sauvages par rapport aux juvéniles totales produits à l'échelle macroscopique]{
  contribution relative des juvéniles
  sauvages par rapport aux juvéniles totales produits à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Les cercles colorés indiquent les années sans
  repeuplement.}
                  \label{Ratio_wild_densite_m2014_12_05}
   \end{center}
  \end{figure}
  
\FloatBarrier    

%--------------------------------------------------
    \subsubsection{Ratio entre les densités issus des juvéniles déversés et
    les densités totales}
    %--------------------------------------------------

         \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Ratio_juv_VLP_m2014_12_05.png}
                  \caption[contribution relative des juvéniles
  issus des déversements par rapport aux juvéniles totales produits à l'échelle
  macroscopique]{
  contribution relative des juvéniles
  issus des déversements par rapport aux juvéniles totales produits à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Les cercles colorés indiquent les années sans
  repeuplement.}
                  \label{Ratio_juv_densite_m2014_12_05}
   \end{center}
  \end{figure}
  
\FloatBarrier 
    %--------------------------------------------------
    \subsubsection{Ratio entre les densités issus des incubateurs de terrain et
    les densités totales}
    %--------------------------------------------------

        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Ratio_egg_VLP_m2014_12_05.png}
                  \caption[contribution relative des juvéniles
  issus des incubateurs de terrain par rapport aux juvéniles totales produits à
  l'échelle macroscopique]{
  contribution relative des juvéniles
  issus des incubateurs de terrain par rapport aux juvéniles totales produits à l'échelle macroscopique
  D$^{tot}_{t+1,i}$ dans les bassin de l'Allier:
  a)Vichy-Langeac, b)Langeac-Poutès, c)Amont Poutès. Les boxplots indiquent les quantiles à 2.5$^{th}$, 25$^{th}$,
  75$^{th}$ et 97.5$^{th}$. Les cercles colorés indiquent les années sans
  repeuplement.}
                  \label{Ratio_egg_densite_m2014_12_05}
    \end{center}
  \end{figure}
  
\FloatBarrier  
    
    
  %--------------------------------------
  \subsection{Production relative de juvéniles 0+ pour une année donnée (J$^{coh}_{t,i}$)}

<< Init_ProdJuvCoh, echo=FALSE, eval=TRUE,results=hide >>=
		
		#=============================================
		#Figure_m2014_12_05 : Spawners Production Juvenile
		#=============================================
		
		png(file=str_c(imgwd_2014_12_05,"SpawnersProdJuvRatio_m2014_12_05.png"),width=800, height=800, units = "px",type="cairo")
		par(mfrow=c(3,3),mar=c(4,6.1,2,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
		
		surf=c(rep(c(916866,250441,0),11),rep(c(916866,250441,301101),12),rep(c(916866,250441,383049),6),rep(c(1202540,250441,383049),31))
		S_juv_JP<-matrix(surf,nrow=3)
		#----------
		# Vichy
		#---------
		#.................
		# Prod juveniles
		#.................
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio juvenile prod")) ,main="Vichy-Langeac",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("a.")),col = "grey55",cex=2)
		
		for(i in 7:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_juv_tot_V_q_m2014_12_05[i,5],i+0.15,ratio_juv_tot_V_q_m2014_12_05[i,5])
			segments(i,ratio_juv_tot_V_q_m2014_12_05[i,4],i,ratio_juv_tot_V_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_juv_tot_V_q_m2014_12_05[i,1],i+0.15,ratio_juv_tot_V_q_m2014_12_05[i,1])
			segments(i,ratio_juv_tot_V_q_m2014_12_05[i,2],i,ratio_juv_tot_V_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_juv_tot_V_q_m2014_12_05[i,2],ratio_juv_tot_V_q_m2014_12_05[i,2],ratio_juv_tot_V_q_m2014_12_05[i,4],ratio_juv_tot_V_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,ratio_juv_tot_V_q_m2014_12_05[i,3],i+0.3,ratio_juv_tot_V_q_m2014_12_05[i,3])
		}
		
		segments(0,S_juv_JP[1,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),11.5,S_juv_JP[1,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),col="grey35",lty=2,lwd=2)
		segments(11.5,S_juv_JP[1,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[1,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[1,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[1,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[1,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[1,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		#segments(7,mean(ratio_juv_tot_V[,7:12]),12.5,mean(ratio_juv_tot_V[,7:12]),col="grey25",lty=2,lwd=2)
		#segments(12.5,mean(ratio_juv_tot_V[,13:37]),37.5,mean(ratio_juv_tot_V[,13:37]),col="grey25",lty=2,lwd=2)
		
		abline(v=12.5,lty=3,col = "grey55")
		
		#............
		# Spawners
		#............
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio Spawners")) ,main="Vichy-Langeac",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("b.")),col = "grey55",cex=2)
		
		for(i in 1:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_S_V_q_m2014_12_05[i,5],i+0.15,ratio_S_V_q_m2014_12_05[i,5])
			segments(i,ratio_S_V_q_m2014_12_05[i,4],i,ratio_S_V_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_S_V_q_m2014_12_05[i,1],i+0.15,ratio_S_V_q_m2014_12_05[i,1])
			segments(i,ratio_S_V_q_m2014_12_05[i,2],i,ratio_S_V_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_S_V_q_m2014_12_05[i,2],ratio_S_V_q_m2014_12_05[i,2],ratio_S_V_q_m2014_12_05[i,4],ratio_S_V_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,ratio_S_V_q_m2014_12_05[i,3],i+0.3,ratio_S_V_q_m2014_12_05[i,3])
		}
		
		segments(0,S_juv_JP[1,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),11.5,S_juv_JP[1,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),col="grey35",lty=2,lwd=2)
		segments(11.5,S_juv_JP[1,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[1,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[1,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[1,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[1,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[1,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		
		#segments(0,mean(ratio_S_V[,1:12]),12.5,mean(ratio_S_V[,1:12]),col="grey25",lty=2,lwd=2)
		#segments(12.5,mean(ratio_S_V[,13:37]),37.5,mean(ratio_S_V[,13:37]),col="grey25",lty=2,lwd=2)
		
		abline(v=12.5,lty=3,col = "grey55")
		
		#............. 
		# diff ratio
		#.............
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(-0.5,0.5), ylab=expression(italic("difference ratio S - ratio juv")) ,main="Vichy-Langeac",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(-0.5,-0.25,0,0.25,0.5),labels=c(-0.5,-0.25,0,0.25,0.5),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,0.5,labels=expression(italic("c.")),col = "grey55",cex=2)
		
		for(i in 7:T){
			#whiskers
			#95%
			segments(i-0.15,diff_ratio_V_q_m2014_12_05[i,5],i+0.15,diff_ratio_V_q_m2014_12_05[i,5])
			segments(i,diff_ratio_V_q_m2014_12_05[i,4],i,diff_ratio_V_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,diff_ratio_V_q_m2014_12_05[i,1],i+0.15,diff_ratio_V_q_m2014_12_05[i,1])
			segments(i,diff_ratio_V_q_m2014_12_05[i,2],i,diff_ratio_V_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(diff_ratio_V_q_m2014_12_05[i,2],diff_ratio_V_q_m2014_12_05[i,2],diff_ratio_V_q_m2014_12_05[i,4],diff_ratio_V_q_m2014_12_05[i,4]),col="coral3")
			#median
			segments(i-0.3,diff_ratio_V_q_m2014_12_05[i,3],i+0.3,diff_ratio_V_q_m2014_12_05[i,3])
		}
		
		abline(h=0,lty=2,col = "grey55")
		abline(v=12.5,lty=3,col = "grey55")
		
		#----------
		# Langeac
		#---------
		#...................
		# Prod juveniles
		#...................
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio juvenile prod")) ,main="Langeac-Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("d.")),col = "grey55",cex=2)
		
		for(i in 7:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_juv_tot_L_q_m2014_12_05[i,5],i+0.15,ratio_juv_tot_L_q_m2014_12_05[i,5])
			segments(i,ratio_juv_tot_L_q_m2014_12_05[i,4],i,ratio_juv_tot_L_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_juv_tot_L_q_m2014_12_05[i,1],i+0.15,ratio_juv_tot_L_q_m2014_12_05[i,1])
			segments(i,ratio_juv_tot_L_q_m2014_12_05[i,2],i,ratio_juv_tot_L_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_juv_tot_L_q_m2014_12_05[i,2],ratio_juv_tot_L_q_m2014_12_05[i,2],ratio_juv_tot_L_q_m2014_12_05[i,4],ratio_juv_tot_L_q_m2014_12_05[i,4]),col="darkolivegreen4")
			#median
			segments(i-0.3,ratio_juv_tot_L_q_m2014_12_05[i,3],i+0.3,ratio_juv_tot_L_q_m2014_12_05[i,3])
		}
		
		segments(0,S_juv_JP[2,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),11.5,S_juv_JP[2,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),col="grey35",lty=2,lwd=2)
		segments(11.5,S_juv_JP[2,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[2,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[2,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[2,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[2,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[2,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		abline(v=12.5,lty=3,col = "grey55")
		
		#............
		# Spawners
		#............
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio Spawners")) ,main="Langeac-Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("e.")),col = "grey55",cex=2)
		
		for(i in 1:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_S_L_q_m2014_12_05[i,5],i+0.15,ratio_S_L_q_m2014_12_05[i,5])
			segments(i,ratio_S_L_q_m2014_12_05[i,4],i,ratio_S_L_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_S_L_q_m2014_12_05[i,1],i+0.15,ratio_S_L_q_m2014_12_05[i,1])
			segments(i,ratio_S_L_q_m2014_12_05[i,2],i,ratio_S_L_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_S_L_q_m2014_12_05[i,2],ratio_S_L_q_m2014_12_05[i,2],ratio_S_L_q_m2014_12_05[i,4],ratio_S_L_q_m2014_12_05[i,4]),col="darkolivegreen4")
			#median
			segments(i-0.3,ratio_S_L_q_m2014_12_05[i,3],i+0.3,ratio_S_L_q_m2014_12_05[i,3])
		}
		
		segments(0,S_juv_JP[2,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),11.5,S_juv_JP[2,1]/(S_juv_JP[1,1]+S_juv_JP[2,1]),col="grey35",lty=2,lwd=2)
		segments(11.5,S_juv_JP[2,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[2,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[2,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[2,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[2,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[2,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		#segments(0,mean(ratio_S_L[,1:12]),12.5,mean(ratio_S_L[,1:12]),col="grey25",lty=2,lwd=2)
		#segments(12.5,mean(ratio_S_L[,13:37]),37.5,mean(ratio_S_L[,13:37]),col="grey25",lty=2,lwd=2)
		
		abline(v=12.5,lty=3,col = "grey55")
		
		#..............
		# diff ratio
		#..............
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(-0.5,0.5), ylab=expression(italic("difference ratio S - ratio juv")) ,main="Langeac-Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(-0.5,-0.25,0,0.25,0.5),labels=c(-0.5,-0.25,0,0.25,0.5),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,0.5,labels=expression(italic("f.")),col = "grey55",cex=2)
		
		for(i in 7:T){
			#whiskers
			#95%
			segments(i-0.15,diff_ratio_L_q_m2014_12_05[i,5],i+0.15,diff_ratio_L_q_m2014_12_05[i,5])
			segments(i,diff_ratio_L_q_m2014_12_05[i,4],i,diff_ratio_L_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,diff_ratio_L_q_m2014_12_05[i,1],i+0.15,diff_ratio_L_q_m2014_12_05[i,1])
			segments(i,diff_ratio_L_q_m2014_12_05[i,2],i,diff_ratio_L_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(diff_ratio_L_q_m2014_12_05[i,2],diff_ratio_L_q_m2014_12_05[i,2],diff_ratio_L_q_m2014_12_05[i,4],diff_ratio_L_q_m2014_12_05[i,4]),col="darkolivegreen4")
			#median
			segments(i-0.3,diff_ratio_L_q_m2014_12_05[i,3],i+0.3,diff_ratio_L_q_m2014_12_05[i,3])
		}
		
		abline(h=0,lty=2,col = "grey55")
		abline(v=12.5,lty=3,col = "grey55")
		
		
		#----------
		# Poutes
		#----------
		#.................
		# Prod juveniles
		#.................
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio juvenile prod")) ,main="upstream Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("g.")),col = "grey55",cex=2)
		
		for(i in 16:T){
			#whiskers
			#95%
			segments(i-0.15,ratio_juv_tot_P_q_m2014_12_05[i,5],i+0.15,ratio_juv_tot_P_q_m2014_12_05[i,5])
			segments(i,ratio_juv_tot_P_q_m2014_12_05[i,4],i,ratio_juv_tot_P_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_juv_tot_P_q_m2014_12_05[i,1],i+0.15,ratio_juv_tot_P_q_m2014_12_05[i,1])
			segments(i,ratio_juv_tot_P_q_m2014_12_05[i,2],i,ratio_juv_tot_P_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_juv_tot_P_q_m2014_12_05[i,2],ratio_juv_tot_P_q_m2014_12_05[i,2],ratio_juv_tot_P_q_m2014_12_05[i,4],ratio_juv_tot_P_q_m2014_12_05[i,4]),col="darkolivegreen3")
			#median
			segments(i-0.3,ratio_juv_tot_P_q_m2014_12_05[i,3],i+0.3,ratio_juv_tot_P_q_m2014_12_05[i,3])
		}
		
		points(x=c(13,14,15),y=c(0,0,0),pch=16,col="darkolivegreen3")
		
		segments(11.5,S_juv_JP[3,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[3,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[3,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[3,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[3,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[3,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		abline(v=12.5,lty=3,col = "grey55")
		
		#............
		# Spawners
		#............			
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(0,1), ylab=expression(italic("ratio Spawners")) ,main="upstream Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,1,labels=expression(italic("h.")),col = "grey55",cex=2)
		
		for(i in 13:23){
			#whiskers
			#95%
			segments(i-0.15,ratio_S_P_q_m2014_12_05[i,5],i+0.15,ratio_S_P_q_m2014_12_05[i,5])
			segments(i,ratio_S_P_q_m2014_12_05[i,4],i,ratio_S_P_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,ratio_S_P_q_m2014_12_05[i,1],i+0.15,ratio_S_P_q_m2014_12_05[i,1])
			segments(i,ratio_S_P_q_m2014_12_05[i,2],i,ratio_S_P_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(ratio_S_P_q_m2014_12_05[i,2],ratio_S_P_q_m2014_12_05[i,2],ratio_S_P_q_m2014_12_05[i,4],ratio_S_P_q_m2014_12_05[i,4]),col="darkolivegreen3")
			#median
			segments(i-0.3,ratio_S_P_q_m2014_12_05[i,3],i+0.3,ratio_S_P_q_m2014_12_05[i,3])
		}
		
		x=seq(24,T,1)
		points(x,ratio_S_P_q_m2014_12_05[24:T,3],pch=16,col="darkolivegreen3")
		
		segments(11.5,S_juv_JP[3,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),23.5,S_juv_JP[3,12]/(S_juv_JP[1,12]+S_juv_JP[2,12]+S_juv_JP[3,12]),col="grey35",lty=2,lwd=2)
		segments(23.5,S_juv_JP[3,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),29.5,S_juv_JP[3,24]/(S_juv_JP[1,24]+S_juv_JP[2,24]+S_juv_JP[3,24]),col="grey35",lty=2,lwd=2)
		segments(29.5,S_juv_JP[3,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),(T+0.5),S_juv_JP[3,30]/(S_juv_JP[1,30]+S_juv_JP[2,30]+S_juv_JP[3,30]),col="grey35",lty=2,lwd=2)
		
		abline(v=12.5,lty=3,col = "grey55")
		
		#.............. 
		# diff ratio
		#..............
		plot(1,1,type="n",axes=FALSE, xlim=c(0.5,T+0.5), xlab="Years", ylim=c(-0.5,0.5), ylab=expression(italic("difference ratio S - ratio juv")) ,main="upstream Poutes",cex.main=2,cex.lab=2)
		
		# trace l'axe des ordonnées
		axis(2,at = c(-0.5,-0.25,0,0.25,0.5),labels=c(-0.5,-0.25,0,0.25,0.5),cex.axis = 2,las = 1,col = "grey55")
		# trace l'axe des abscisses
		axis(1,at = c(1,6,16,26,T),
				labels=c(1975,1980,1990,2000,2013),
				cex.axis = 2,las = 1,col = "grey55")
		
		text(T,0.5,labels=expression(italic("i.")),cex=2)
		
		for(i in 13:T){
			#whiskers
			#95%
			segments(i-0.15,diff_ratio_P_q_m2014_12_05[i,5],i+0.15,diff_ratio_P_q_m2014_12_05[i,5])
			segments(i,diff_ratio_P_q_m2014_12_05[i,4],i,diff_ratio_P_q_m2014_12_05[i,5])
			#5%
			segments(i-0.15,diff_ratio_P_q_m2014_12_05[i,1],i+0.15,diff_ratio_P_q_m2014_12_05[i,1])
			segments(i,diff_ratio_P_q_m2014_12_05[i,2],i,diff_ratio_P_q_m2014_12_05[i,1])
			#boxplot
			polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(diff_ratio_P_q_m2014_12_05[i,2],diff_ratio_P_q_m2014_12_05[i,2],diff_ratio_P_q_m2014_12_05[i,4],diff_ratio_P_q_m2014_12_05[i,4]),col="darkolivegreen3")
			#median
			segments(i-0.3,diff_ratio_P_q_m2014_12_05[i,3],i+0.3,diff_ratio_P_q_m2014_12_05[i,3])
		}
		
		abline(h=0,lty=2,col = "grey55")
		abline(v=12.5,lty=3,col = "grey55")
		
		for (i in 1:T){
			S_vichy_q_m2014_12_05[i,]=quantile(S_vichy_real_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
			S_langeac_q_m2014_12_05[i,]=quantile(S_langeac_real_m2014_12_05[,i],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
		}
		
		dev.off()
@


        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}SpawnersProdJuvRatio_m2014_12_05.png}
                  \caption[production relative de
  juvéniles 0+ pour une année donnée (J$^{coh}_{t,i}$)]{
  production relative de
  juvéniles 0+ pour une année donnée (J$^{coh}_{t,i}$) pour chaque zone du
  bassin de l'Allier (panneaux a,d et g), distribution a posteriori des
  abondances relatives de géniteurs potentiels (panneaux b,e et h) et
  distribution a posteriori de la différence entre les abondances relatives de
  géniteurs potentiels et de production de juvéniles 0+ (panneaux c,f et
  i).Les lignes pointillées horizontales indiquent la disponibilité relative
  de l'habitat potentiel pour les juvéniles. Les boxplots indiquent les
  quantiles à 2.5$^{th}$, 25$^{th}$, 75$^{th}$ et 97.5$^{th}$. }
                  \label{Juv_Coh_Ratio_m2014_12_05}
   \end{center}
  \end{figure}
  
\FloatBarrier  


%--------------------------------------------------
  \subsection{Relation de densité dépendance}
  %--------------------------------------------------

<< Init_RelationDD, echo=FALSE, eval=TRUE,results=hide >>=
#====================
# figure_m2014_12_05 : dd
#====================
png(filename=str_c(imgwd_2014_12_05,"dd_m2014_12_05.png"),width=800,height=800)
par(mfrow=c(2,1),mar=c(4,5.5,2,1.5))

#Graphe densite dependence juvenile sauvage
plot(1,1,type="n",axes=FALSE,xlim=c(0,0.0025),xlab=expression(paste(S," ",(spawners.m^-2))),ylim=c(0,0.35),ylab=expression(paste(d^wild," (0+",.m^-2,")")),main="wild 0+ density dependence relationship",cex.main=1.5,cex.lab=1.8)
# trace l'axe des ordonnées
axis(1,at = c(0,0.00050,0.0010,0.0015, 0.002, 0.0025),
		labels=c(0,expression(paste(0.5," x ",10^-3)),expression(10^-3),expression(paste(1.5," x ",10^-3)),expression(paste(2," x ",10^-3)),expression(paste(2.5," x ",10^-3)) ),
		cex.axis = 1.2,las = 1,lwd=2)
# trace l'axe des abscisses
axis(2,at = c(0,0.05,0.10,0.15,0.20,0.25,0.30,0.35),
		labels=c(0,0.05,0.10,0.15,0.20,0.25,0.30,0.35),
		cex.axis = 1.2,las = 1,lwd=2)

points(S_vichy_q_m2014_12_05[1:38,3]/S_juv_JP[1,1:38],dmoy_wild_V_q_m2014_12_05[2:39,3],pch=16,col="coral3")#"gray15")

points(S_langeac_q_m2014_12_05[1:38,3]/S_juv_JP[2,1:38],dmoy_wild_L_q_m2014_12_05[2:39,3],pch=16,col="darkolivegreen4")#"gray45")

points(S_poutes_counter[12:38]/S_juv_JP[3,12:38],dmoy_wild_P_q_m2014_12_05[13:39,3],pch=16,col="darkolivegreen3")#"gray75")

x=seq(0,0.0025,0.0000001)

y=exp(log(x/(1/median(a_m2014_12_05) + x * 1/median(Rmax_m2014_12_05))) + median(nu_wild_m2014_12_05[,1]))
points(x,y,type="l",col="coral3")#"gray15")

y=exp(log(x/(1/median(a_m2014_12_05) + x * 1/median(Rmax_m2014_12_05))) + median(nu_wild_m2014_12_05[,2]))
points(x,y,type="l",col="darkolivegreen4")#"gray45")

text(0.0025,0.35,labels=expression(italic("a.")),col = "grey55",cex=1.5)

#legend(0,0.35,legend=c("Vichy-Langeac","Langeac-Poutes","upstream Poutes","downstream Langeac","upstream Langeac"),lty=c(NA,NA,NA,1,1),pch=c(16,16,16,NA,NA),col=c("gray15","gray45","gray75","gray15","gray75"))

#legend(0.00065,0.34,legend=c("Vichy-Langeac","average density dependence relationship downstream Langeac  ","Langeac-Poutes","upstream Poutes","average density dependence relationship upstream Langeac") ,
#box.col="grey65",pch=c(16,NA,16,16,NA),col=c("coral3","coral3","darkolivegreen4","darkolivegreen3","darkolivegreen"),lty=c(NA,1,NA,NA,1),text.col="grey25")


#Graphe densite dependence juvenile repeuplement

plot(1,1,type="n",axes=FALSE,xlim=c(0,1.4),xlab=expression(paste(Stock^juv," ",(0+.m^-2))),ylim=c(0,0.35),ylab=expression(paste(d^juv," (0+",.m^-2,")")),main="stocked 0+ density dependence relationship",cex.main=1.5,cex.lab=1.8)
# trace l'axe des abcisses
axis(1,at = c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1,1.2,1.3,1.4),
		labels=c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1,1.2,1.3,1.4),
		cex.axis = 1.2,las = 1)
# trace l'axe des ordonnées
axis(2,at = c(0,0.05,0.10,0.15,0.2,0.25,0.3,0.35),
		labels=c(0,0.05,0.10,0.15,0.20,0.25,0.3,0.35),
		cex.axis = 1.2,las = 1)

points(stocked_juv_V_d_m2014_12_05[I_juv_V],dmoy_juv_V_q_m2014_12_05[I_juv_V,3],pch=15,col="coral3")

points(stocked_juv_L_d_m2014_12_05[I_juv_L],dmoy_juv_L_q_m2014_12_05[I_juv_L,3],pch=15,col="darkolivegreen4")

points(stocked_juv_P_d_m2014_12_05[I_juv_P],dmoy_juv_P_q_m2014_12_05[I_juv_P,3],pch=15,col="darkolivegreen3")

x=seq(0,0.35,0.0001)

points(x,x,type="l",lty=2,col="gray15")

x=seq(0,1.4,0.0001)

y=  x / ( ( 1 / exp(median(nu_wild_m2014_12_05[,1]))) * 1/median(a_juv_m2014_12_05) + x * 1/median(Rmax_m2014_12_05)  )   
points(x,y,type="l",col="coral3")


y=  x / ( ( 1 / exp(median(nu_wild_m2014_12_05[,2]))) * 1/median(a_juv_m2014_12_05) + x * 1/median(Rmax_m2014_12_05)  )   
points(x,y,type="l",col="darkolivegreen4")


text(1.4,0.35,labels=expression(italic("b.")),col = "grey55",cex=1.5)

#legend(0,0.2,bg="white",legend=c("Vichy-Langeac","Langeac-Poutes","upstream Poutes","downstream Langeac","upstream Langeac"),lty=c(NA,NA,NA,1,1),pch=c(15,15,15,NA,NA),col=c("gray15","gray45","gray75","gray15","gray75"))

dev.off()

@


        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}dd_m2014_12_05.png}
                  \caption[Relation de densité
  dépendance moyenne pour le compartiment sauvage et élevage]{
  Relation de densité
  dépendance moyenne entre a) les géniteurs potentiels d'une année
  donnée t et la densité de juvéniles 0+ sauvage l'année suivante
  t+1 et entre b) le nombre de juvéniles 0+ déversés au printemps
  et la densité de juvéniles issus du repeuplement à l'automne. Les
  différences spatiales à l'aval et l'amont de Langeac sont
  représentées par deux courbes de couleurs différentes (rouge pour l'aval et
  vert pour l'amont). Les cercles et les carrés colorés
  représentent les "données" pour chaque zone du bassin de l'Allier
  : rouge pour la zone Vichy-Langeac, vert foncé pour la zone
  Langeac-Poutès et vert clair pour la zone à l'amont de Poutès. La
  ligne pointillée dans le panneau b représente la fonction
  identité.}
                  \label{dd_m2014_12_05}
    \end{center}
  \end{figure}
  
\FloatBarrier  

 %--------------------------------------------------
  \subsection{Survie du 0+ à l'adulte}
  %--------------------------------------------------
<< Init_Survival, echo=FALSE, eval=TRUE,results=hide >>=
#========================#
# CODE_R_SURVIVAL_JUV2AD #
#========================#

I_surv_m2014_12_05=read.coda(str_c(m2014_12_05,"simulation/I_survCODAchain1.txt"),str_c(m2014_12_05,"simulation/I_survCODAindex.txt"),5001,10000)
s_juv2ad_m2014_12_05=read.coda(str_c(m2014_12_05,"simulation/s_juv2adCODAchain1.txt"),str_c(m2014_12_05,"simulation/s_juv2adCODAindex.txt"),5001,10000)
level_s_m2014_12_05=read.coda(str_c(m2014_12_05,"simulation/level_sCODAchain1.txt"),str_c(m2014_12_05,"simulation/level_sCODAindex.txt"),5001,10000)

s_m2014_12_05=array(0,c(5000,39))
s_smolt_m2014_12_05=array(0,c(5000,39))

mu_s_smolt=0.000545


for (t in 1:7){
	s_m2014_12_05[,t]=s_juv2ad_m2014_12_05*exp(level_s_m2014_12_05)
	s_smolt_m2014_12_05[,t]=mu_s_smolt*exp(level_s_m2014_12_05)
}

for (t in 8:39){
	s_m2014_12_05[,t]=s_juv2ad_m2014_12_05*exp(level_s_m2014_12_05*I_surv_m2014_12_05[,t-7])
	s_smolt_m2014_12_05[,t]=mu_s_smolt*exp(level_s_m2014_12_05*I_surv_m2014_12_05[,t-7])
	
}


s_q_m2014_12_05=array(0,c(39,5))
s_smolt_q_m2014_12_05=array(0,c(39,5))

I_surv_q_m2014_12_05=array(0,c(39,5))

for (t in 1:39){
	s_q_m2014_12_05[t,]=quantile(s_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	s_smolt_q_m2014_12_05[t,]=quantile(s_smolt_m2014_12_05[,t],probs=c(0.025,0.25,0.5,0.75,0.975),names=FALSE)
	
	I_surv_q_m2014_12_05[t,]=quantile(I_surv_m2014_12_05[,t],probs=c(0.01,0.25,0.5,0.75,0.99),names=FALSE)
}

max(s_q_m2014_12_05)

palette_s=rainbow(15,start=0.1,end=2/6)
palette_s=rev(palette_s)


#########################"
#Fig_m2014_12_05
############################
png(file=str_c(imgwd_2014_12_05,"SurvivalJuv2Ad_m2014_12_05.png"),width=800, height=800, units = "px",type="cairo")

par(mfrow=c(2,1),mar=c(4,7.1,2,0.5),col.lab="grey25",col.axis="grey55",col.main="grey25")

plot(1,1,type="n",axes=FALSE, xlim=c(0.5,39.5), xlab="Years", ylim=c(0,0.04), ylab="",main="average 0+ to returning adult survival",cex.lab=1.5,cex.main=2 )

# trace l'axe des ordonnées
axis(2,at = c(0,0.01,0.02,0.03,0.04),labels=c(0,0.01,0.02,0.03,0.04),cex.axis = 1.5,las = 1,lwd=2,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,6,16,26,39),
		labels=c(1975,1980,1990,2000,2013),
		cex.axis = 1.5,las = 1,lwd=2,col = "grey55")


for(i in 7:21){
	#whiskers
	#95%
	segments(i-0.15,s_q_m2014_12_05[i,5],i+0.15,s_q_m2014_12_05[i,5])
	segments(i,s_q_m2014_12_05[i,4],i,s_q_m2014_12_05[i,5])
	#5%
	segments(i-0.15,s_q_m2014_12_05[i,1],i+0.15,s_q_m2014_12_05[i,1])
	segments(i,s_q_m2014_12_05[i,2],i,s_q_m2014_12_05[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(s_q_m2014_12_05[i,2],s_q_m2014_12_05[i,2],s_q_m2014_12_05[i,4],s_q_m2014_12_05[i,4]),col=palette_s[i-6])
	#median
	segments(i-0.3,s_q_m2014_12_05[i,3],i+0.3,s_q_m2014_12_05[i,3])
}



for(i in 22:39){
	#whiskers
	#95%
	segments(i-0.15,s_q_m2014_12_05[i,5],i+0.15,s_q_m2014_12_05[i,5])
	segments(i,s_q_m2014_12_05[i,4],i,s_q_m2014_12_05[i,5])
	#5%
	segments(i-0.15,s_q_m2014_12_05[i,1],i+0.15,s_q_m2014_12_05[i,1])
	segments(i,s_q_m2014_12_05[i,2],i,s_q_m2014_12_05[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(s_q_m2014_12_05[i,2],s_q_m2014_12_05[i,2],s_q_m2014_12_05[i,4],s_q_m2014_12_05[i,4]),col=palette_s[15])
	#median
	segments(i-0.3,s_q_m2014_12_05[i,3],i+0.3,s_q_m2014_12_05[i,3])
}





plot(1,1,type="n",axes=FALSE, xlim=c(0.5,39.5), xlab="Years", ylim=c(0,0.04), ylab="",main="average stocked smolts to returning adult survival",cex.lab=1.5 ,cex.main=2)

# trace l'axe des ordonnées
axis(2,at = c(0,0.01,0.02,0.03,0.04),labels=c(0,0.01,0.02,0.03,0.04),cex.axis = 1.5,las = 1,lwd=2,col = "grey55")
# trace l'axe des abscisses
axis(1,at = c(1,6,16,26,39),
		labels=c(1975,1980,1990,2000,2013),
		cex.axis = 1.5,las = 1,lwd=2,col = "grey55")


for(i in 7:21){
	#whiskers
	#95%
	segments(i-0.15,s_smolt_q_m2014_12_05[i,5],i+0.15,s_smolt_q_m2014_12_05[i,5])
	segments(i,s_smolt_q_m2014_12_05[i,4],i,s_smolt_q_m2014_12_05[i,5])
	#5%
	segments(i-0.15,s_smolt_q_m2014_12_05[i,1],i+0.15,s_smolt_q_m2014_12_05[i,1])
	segments(i,s_smolt_q_m2014_12_05[i,2],i,s_smolt_q_m2014_12_05[i,1])
	#boxplot
	polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(s_smolt_q_m2014_12_05[i,2],s_smolt_q_m2014_12_05[i,2],s_smolt_q_m2014_12_05[i,4],s_smolt_q_m2014_12_05[i,4]),col=palette_s[i-6])
	#median
	segments(i-0.3,s_smolt_q_m2014_12_05[i,3],i+0.3,s_smolt_q_m2014_12_05[i,3])
}



for(i in 22:39){
	
	points(i,s_smolt_q_m2014_12_05[i,3],pch=16,col=palette_s[15])
	#whiskers
	#95%
	#segments(i-0.15,s_smolt_q_un[i,5],i+0.15,s_smolt_q_un[i,5])
	#segments(i,s_smolt_q_un[i,4],i,s_smolt_q_un[i,5])
	#5%
	#segments(i-0.15,s_smolt_q_un[i,1],i+0.15,s_smolt_q_un[i,1])
	#segments(i,s_smolt_q_un[i,2],i,s_smolt_q_un[i,1])
	#boxplot
	#polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(s_smolt_q_un[i,2],s_smolt_q_un[i,2],s_smolt_q_un[i,4],s_smolt_q_un[i,4]),col=palette_s[15])
	#median
	#segments(i-0.3,s_smolt_q_un[i,3],i+0.3,s_smolt_q_un[i,3])
}

dev.off()
@

   \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}SurvivalJuv2Ad_m2014_12_05.png}
                  \caption[évolution du taux de retour
  du juvénile 0+ à l'adulte]{
  évolution du taux de retour
  du juvénile 0+ à l'adulte \mu$^{s_J}$ (a) et du taux de retour du smolt issu
  du repeuplement à l'adulte \mu$^{s_Sm}$. Les points indiquent la survie
  moyenne du smolt issu du repeuplement à l'adulte fixée à partir des données
  de marquage (\mu$^{s_Sm}$=5.45 x10^$^{-4}$)}
                  \label{SurvivalJuv2Ad_m2014_12_05}
     \end{center}
  \end{figure}

\FloatBarrier  
 %--------------------------------------------------
  \subsection{Probabilité de passage à Langeac et Poutès}
  %--------------------------------------------------

<< Init_ProbaPassage, echo=FALSE, eval=TRUE,results=hide >>=
    #==========================================================================
	# SEC : Calcul des probas de passer aux differentes stations de comptage
	#========================================================================== 
		
			#----------------------------------------------------
			# Figure_m2014_12_05 : Redds_probaPassageStation with all years
			#----------------------------------------------------
			#...........
			# p_langeac
			#...........
			
			png(file=str_c(imgwd_2014_12_05,"Redds_ProbaPassageStation_m2014_12_05.png"),width=800, height=800, units = "px",type="cairo")
			
			par(mfrow=c(2,1),mar=c(4,6.1,0,0.5),cex.lab=1.4, cex.lab=1.4,col.lab="grey25",col.axis="grey55",col.main="grey25")
			
			plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="",ylim=c(0,1),ylab=expression(italic(p^L)),main="",cex.lab=2)
			text(T+0.5,1,labels=expression(italic("a.")),col = "grey55",cex=2)
			
			# trace l'axe des ordonnées
			axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
			# trace l'axe des abscisses
			axis(1,at = c(1,6,16,26,T),
					labels=c(1975,1980,1990,2000,2013),
					cex.axis = 2,las = 1,col = "grey55")
			
			xx=c(0:(T+1),(T+1):0)
			
			q_2_5=rep(mu_p_langeac_q_m2014_12_05[1],T+2)
			q_97_5=rep(mu_p_langeac_q_m2014_12_05[5],T+2)
			
			yy=c(q_2_5,rev(q_97_5))
			
			polygon(xx,yy,col="slategray1",border="NA")
			
			
			q_25=rep(mu_p_langeac_q_m2014_12_05[2],T+2)
			q_75=rep(mu_p_langeac_q_m2014_12_05[4],T+2)
			
			yy=c(q_25,rev(q_75))
			
			polygon(xx,yy,col="slategray3",border="NA")
			
			points(x=seq(0,T+1,1),y=rep(mu_p_langeac_q_m2014_12_05[3],T+2),type="l",col="white")
			
			for(i in 1:T){
				#whiskers
				#95%
				segments(i-0.15,p_langeac_q_m2014_12_05[i,5],i+0.15,p_langeac_q_m2014_12_05[i,5])
				segments(i,p_langeac_q_m2014_12_05[i,4],i,p_langeac_q_m2014_12_05[i,5])
				#5%
				segments(i-0.15,p_langeac_q_m2014_12_05[i,1],i+0.15,p_langeac_q_m2014_12_05[i,1])
				segments(i,p_langeac_q_m2014_12_05[i,2],i,p_langeac_q_m2014_12_05[i,1])
				#boxplot
				polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(p_langeac_q_m2014_12_05[i,2],p_langeac_q_m2014_12_05[i,2],p_langeac_q_m2014_12_05[i,4],p_langeac_q_m2014_12_05[i,4]),col="steelblue4")
				#median
				segments(i-0.3,p_langeac_q_m2014_12_05[i,3],i+0.3,p_langeac_q_m2014_12_05[i,3])
			}
			
			#..........
			#p_poutes
			#..........
			plot(1,1,type="n",axes=FALSE,xlim=c(0.5,T+0.5),xlab="Years",ylim=c(0,1),ylab=expression(italic(p^P)),main="",cex.lab=2)
			
			text(T+0.5,1,labels=expression(italic("b.")),col = "grey55",cex=2)
			
			# trace l'axe des ordonnées
			axis(2,at = c(0,0.2,0.4,0.6,0.8,1),labels=c(0,0.2,0.4,0.6,0.8,1),cex.axis = 2,las = 1,col = "grey55")
			# trace l'axe des abscisses
			axis(1,at = c(1,6,16,26,T),
					labels=c(1975,1980,1990,2000,2013),
					cex.axis = 2,las = 1,col = "grey55")
			
			temp=c(11.5,12:(T+1))
			temp1=c(rev(12:(T+1)),11.5)
			
			xx=c(temp,temp1)
			
			q_2_5=rep(mu_p_poutes_q_m2014_12_05[1],T+1-12+2)
			q_97_5=rep(mu_p_poutes_q_m2014_12_05[5],T+1-12+2)
			
			yy=c(q_2_5,rev(q_97_5))
			
			polygon(xx,yy,col="slategray1",border="NA")
			
			q_25=rep(mu_p_poutes_q_m2014_12_05[2],T+1-12+2)
			q_75=rep(mu_p_poutes_q_m2014_12_05[4],T+1-12+2)
			
			yy=c(q_25,rev(q_75))
			
			polygon(xx,yy,col="slategray3",border="NA")
			
			points(seq(11.5,T+1,0.5),rep(mu_p_poutes_q_m2014_12_05[3],(T+1-12+1)*2),type="l",col="white")
			
			for(i in 12:T){
				#whiskers
				#95%
				segments(i-0.15,p_poutes_q_m2014_12_05[i,5],i+0.15,p_poutes_q_m2014_12_05[i,5])
				segments(i,p_poutes_q_m2014_12_05[i,4],i,p_poutes_q_m2014_12_05[i,5])
				#5%
				segments(i-0.15,p_poutes_q_m2014_12_05[i,1],i+0.15,p_poutes_q_m2014_12_05[i,1])
				segments(i,p_poutes_q_m2014_12_05[i,2],i,p_poutes_q_m2014_12_05[i,1])
				#boxplot
				polygon(c(i-0.3,i+0.3,i+0.3,i-0.3),c(p_poutes_q_m2014_12_05[i,2],p_poutes_q_m2014_12_05[i,2],p_poutes_q_m2014_12_05[i,4],p_poutes_q_m2014_12_05[i,4]),col="steelblue4")
				#median
				segments(i-0.3,p_poutes_q_m2014_12_05[i,3],i+0.3,p_poutes_q_m2014_12_05[i,3])
			}
			
			abline(v=11.5,lty=2)
			
			text(6,0.55,paste( "upstream Poutes\n inaccessible"),col = "grey25",cex=2)
			
			dev.off()
			
@


        \begin{figure}[ht]
          \begin{center}
                  \includegraphics{\Sexpr{imgwd_2014_12_05}Redds_ProbaPassageStation_m2014_12_05.png}
                  \caption[ probabilité de passer en
  amont de Langeac et Poutès]{
  probabilité de passer en
  amont de Langeac et Poutès.}
  \label{Redds_ProbaPassageStation}
           \end{center}
  \end{figure}

\FloatBarrier  



%=================================================================================
\section{Paramètres à comparer}
%=================================================================================
<< Init_SortieOpenBugs, echo=FALSE, eval=TRUE,results=hide >>=
a_juv_m2014_12_05=read.coda(str_c(m2014_12_05,"a_juvCODAchain1.txt"),str_c(m2014_12_05,"a_juvCODAindex.txt"))
png(filename=str_c(imgwd_2014_12_05,"Parametres/a_juv_m2014_12_05.png"),width=800,height=800)
plot(a_juv_m2014_12_05)
dev.off()

plot(s_juv2ad_m2014_12_05)
median(s_juv2ad_m2014_12_05)


@
  %-------------------------
  \subsection{a_juv}
  %-------------------------
      \begin{figure}[ht]
          \begin{center} 
          \includegraphics{\Sexpr{imgwd_2014_12_05}/Parametres/a_juv_m2014_12_05.png}
          \caption[Comparaison du paramètres a_juv de chacun des 3 modèles]{Comparaison du paramètres a_juv de chacun des 3 modèles}
          \label{a_juv_m2014_12_05}
           \end{center}
       \end{figure}
  
\FloatBarrier  


\maketitle


\end{document}
